### ISSUE TITLE
Separate Lua l3-load-latency.lua test 

### ISSUE THREAD

**Issue by wenhuizhang** [emmericp/MoonGen#100]
Hi, is it possible to separate lua l3-load-latency.lua and l2-load-latency.lua into clients and servers, instead of all together? 

As if maybe sending and receiving are sharing the same up/down link, they will have some interference for calculating?

More specifically, a separate server on the other side of the switch/bridge/router will be preferred. 

Thanks, 

wenhui

**Comment by emmericp** [comment]
No, this isn't possible because of timestamping/clock synchronization.
Just use two ports on one server if you are worried about issues when using the same port twice.

**Comment by wenhuizhang** [comment]
Good solution, thanks!

On Thu, Oct 29, 2015 at 7:40 PM, Paul Emmerich <notifications@github.com>
wrote:

> Closed #100 <https://github.com/emmericp/MoonGen/issues/100>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emmericp/MoonGen/issues/100#event-449871129>.
>



-- 
V/R,

Wenhui Zhang

Email: wenhui@gwmail.gwu.edu
           Telephone: 1-(703) 424 3193
