### ISSUE TITLE
How to fill in UDP data for UDP packet?

### ISSUE THREAD

**Issue by vincentmli** [emmericp/MoonGen#102]
Hi 

in lua/include/proto/udp.lua, I couldn't figure out how to fill in the UDP data other than the UDP headers. for example, I copied examples/l3-tcp-syn-flood.lua and changed it to use UDP as some kind of UDP flooding test, but I also want to be able to fill in some UDP data bytes like some canned bytes and send that UDP packet out, can you give me clue how to to do that?

with the modified l3-tcp-syn-flood for UDP as below:
<pre>
local dpdk              = require "dpdk"
local memory    = require "memory"
local device    = require "device"
local stats             = require "stats"

function master(txPorts, minIp, numIps, rate)
        if not txPorts then
                printf("usage: txPort1[,txPort2[,...]] [minIP numIPs rate]")
                return
        end
        txPorts = tostring(txPorts)
        minIp = minIp or "10.0.0.1"
        numIps = numIps or 100
        rate = rate or 0
        for currentTxPort in txPorts:gmatch("(%d+),?") do
                currentTxPort = tonumber(currentTxPort)
                local txDev = device.config({ port = currentTxPort })
                txDev:wait()
                txDev:getTxQueue(0):setRate(rate)
                dpdk.launchLua("loadSlave", currentTxPort, 0, minIp, numIps)
        end
        dpdk.waitForSlaves()
end

function loadSlave(port, queue, minA, numIPs)
        --- parse and check ip addresses

        local minIP, ipv4 = parseIPAddress(minA)
        if minIP then
                printf("INFO: Detected an %s address.", minIP and "IPv4" or "IPv6")
        else
                errorf("ERROR: Invalid minIP: %s", minA)
        end

        -- min TCP packet size for IPv6 is 74 bytes (+ CRC)
        local packetLen = ipv4 and 60 or 74

        --continue normally
        local queue = device.get(port):getTxQueue(queue)
        local mem = memory.createMemPool(function(buf)
                buf:getUdpPacket(ipv4):fill{
                        ethSrc="a0:36:9f:a1:4d:6d", ethDst="52:54:00:2E:62:A2",
                        --- ip4Dst="10.9.1.2",
                        ip4Dst="10.9.3.6",
                        ip6Dst="fd06::1",
                        udpDst="9999",
                        udpSrc="1029",
                        pktLength=packetLen }
        end)

        local lastPrint = dpdk.getTime()
        local totalSent = 0
        local lastTotal = 0
        local lastSent = 0
        local bufs = mem:bufArray(128)
        local counter = 0
        local c = 0

        local txStats = stats:newDevTxCounter(queue, "plain")
        while dpdk.running() do
                -- faill packets and set their size
                bufs:alloc(packetLen)
                for i, buf in ipairs(bufs) do
                        local pkt = buf:getUdpPacket(ipv4)

                        --increment IP
                        if ipv4 then
                                pkt.ip4.src:set(minIP)
                                pkt.ip4.src:add(counter)
                                --random udp source port
--                              pkt.udp.src = math.random(0, 2^16 - 1)
                        else
                                pkt.ip6.src:set(minIP)
                                pkt.ip6.src:add(counter)
                        end
                        counter = incAndWrap(counter, numIPs)

                        -- dump first 3 packets
                        if c < 3 then
                                buf:dump()
                                c = c + 1
                        end
                end
                --offload checksums to NIC
                bufs:offloadTcpChecksums(ipv4)

                totalSent = totalSent + queue:send(bufs)
                txStats:update()
        end
        txStats:finalize()
end
</pre>

 from wireshark, I see there is 

User Datagram Protocol, Src Port: 1029 (1029), Dst Port: 9999 (9999)
Data (18 bytes)
Data: 0000000000000000bd910000000000000000

I am wondering if I can fill in data bytes I wanted to fill in UDP packet.

**Comment by emmericp** [comment]
All packets have a "payload" field which contains a uint8/16/32 union, so you can do something like this:

pkt.payload.uint32[offset] = foo


Example: https://github.com/emmericp/MoonGen/blob/master/examples/benchmark/heavy-workload.lua?ts=4

**Comment by emmericp** [comment]
(the example obviously isn't optimal, you probably want to do this in the packet initialization callback instead of the main loop)
