### ISSUE TITLE
example icmp-arp-responder not working

### ISSUE THREAD

**Issue by vincentmli** [emmericp/MoonGen#103]
Hi,

I am trying to run the icmp-arp-responder example and it seems stuck there:

EAL: Master core 0 is ready (tid=147e2880) <==========Master core 0
EAL: Core 1 is ready (tid=8d3f2700)
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL:   0000:04:00.0 not managed by UIO driver, skipping
EAL: PCI device 0000:04:00.1 on NUMA socket -1 <==========managed by UIO
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL:   PCI memory mapped at 0x7f1e1472b000
EAL:   PCI memory mapped at 0x7f1e14727000
EAL: PCI device 0000:07:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10e8 rte_igb_pmd
EAL:   0000:07:00.0 not managed by UIO driver, skipping
EAL: PCI device 0000:07:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10e8 rte_igb_pmd
EAL:   0000:07:00.1 not managed by UIO driver, skipping
EAL: PCI device 0000:08:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10e8 rte_igb_pmd
EAL:   0000:08:00.0 not managed by UIO driver, skipping
EAL: PCI device 0000:08:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10e8 rte_igb_pmd
EAL:   0000:08:00.1 not managed by UIO driver, skipping
Found 1 usable ports:
   Ports 0: E8:EA:6A:06:1B:1B (82599EB 10-Gigabit SFI/SFP+ Network Connection)
[WARNING] You are using a deprecated method for invoking device.config. config(...) should be used with named arguments. For details: see documentation
Waiting for ports to come up...
Port 0 (E8:EA:6A:06:1B:1B) is up: full-duplex 10000 MBit/s
1 ports are up.
[WARNING] You are trying to use [Device: id=0] (attached to the CPU socket 0) from a thread on core 1 on socket 1!
[WARNING] This can significantly impact the performance or even not work at all
[WARNING] You can change the used CPU cores in dpdk-conf.lua or by using dpdk.launchLuaOnCore(core, ...)

----HANGING HERE, NO MORE OUTPUT------

I get the same warning of changing CPU cores in dpdk-conf.lua when run other example script like the tcp syn flooding and the tcp syn flooding works fine. so the warning should be irrelevant here. but I went ahead to change the CPU cores in dpdk-conf.lua to ' cores = { 0 }', then I got:

Port 0 (E8:EA:6A:06:1B:1B) is up: full-duplex 10000 MBit/s
1 ports are up.
[ERROR] Lua error in task master
lua/include/dpdk.lua:197: not enough cores to start this lua task
Stack Traceback
===============
(2) Lua field 'launchLua' at file 'lua/include/dpdk.lua:197'
(3) Lua function 'master' at file 'examples/icmp-arp-responder.lua:24' (best guess)
        Local variables:
         funny = nil
         port = number: 0
         dev = [Device: id=0]  {initialized:true, rxQueues:table: 0x40611858, txQueues:table: 0x40611880 (more...)}
(4) global C function 'xpcall'
(5) Lua upvalue 'slave' at file 'lua/include/main.lua:69'
        Local variables:
         _ = string: "build/MoonGen"
         file = string: "examples/icmp-arp-responder.lua"
         devices = table: 0x40612300  {1:table: 0x406118c8}
         args = table: 0x402154f0  {1:0, 2:10.3.3.249}
(6) Lua function 'main' at file 'lua/include/main.lua:105' (best guess)
        Local variables:
         task = string: "master"
        lua/include/dpdk.lua:197: not enough cores to start this lua task

so my question is:

1, how to change the core id so the lua script can be run on specified CPU core? tried dpdk-conf.lua and  dpdk.launchLuaOnCore(core, ...). seems no effect.

2, any clue why icmp-arp-responder silently hanging there?

Thanks and appreciate the answer.

**Comment by vincentmli** [comment]
sorry here is the actual script command

#build/MoonGen examples/icmp-arp-responder.lua 0 10.3.3.249 

MoonGen was run on DPDK box with ip address 10.3.3.9 on dpdk0 interface

here is the tcpdump I run at the target server that has ip 10.3.3.249:

09:50:36.300333 arp who-has 10.3.3.249 (ff:ff:ff:ff:ff:ff) tell 10.3.3.249
09:50:36.302757 arp reply 10.3.3.249 is-at e8:ea:6a:06:1b:1b

why the arp request source ip is 10.3.3.249, not 10.3.3.9 

it seems pingResponder in icmp-arp-responder.lua isn't properly running?

**Comment by emmericp** [comment]
This script needs two cores: one for the master core and one for the slave. (This could be optimized by replacing launchLua() with a direct call, but it doesn't really matter).

No idea why your NICs NUMA association shows up as "-1", it shouldn't do that. Which Linux distribution are you using?
A bad NUMA mapping could indeed cause RX to fail on some systems. Other scripts works because they don't try to receive packets.

> MoonGen was run on DPDK box with ip address 10.3.3.9 on dpdk0 interface

DPDK interfaces do not have IP addresses.
