### ISSUE TITLE
RSS hash for TCP/UDP in IPv6 variant misspelled

### ISSUE THREAD

**Issue by ilozgach** [emmericp/MoonGen#105]
From device.c file, it looks like tcp/udp misspelled...

if(hash_functions->udp_ipv6){
      rss_hash_functions |= ETH_RSS_IPV6_TCP;
      //printf("ipv6 udp\n");
    }
    if(hash_functions->tcp_ipv6){
      rss_hash_functions |= ETH_RSS_IPV6_UDP;
      //printf("ipv6 tcp\n");
    }

**Comment by emmericp** [comment]
Oops. Fixed by commit a16039cd1e912f645b8ccf2e72516af6b3e422df
