### ISSUE TITLE
0.1 Release

### ISSUE THREAD

**Issue by emmericp** [emmericp/MoonGen#110]
Let's do a proper release with a version number and all that stuff.

- [x] DPDK 2.1 support
- [ ] shared cores for BG task (ARP...)
- [x] better XL710 10/40G support
- [ ] better i350 support (HW filter)
- [ ] better VirtIO support
- [x] software timestamping
- [x] detailed precision evaluation of timestamping and rate control
- [ ] TCP stack
- [x] new test framework/infrastructure

**Comment by emmericp** [comment]
This will be part of a bigger refactoring and will thus take longer.

**Comment by jmhelt** [comment]
Out of curiosity, what's the current status of a TCP stack implementation for Moongen?

**Comment by emmericp** [comment]
i've a student working on it in a private branch, we've implementations with both mtcp and lwip


we are probably not going to implement any advanced pcap stuff for the simple reason that we don't need this feature - we simply cannot maintain everything, which is why we prefer to focus on framework features such that you can build your own scripts.
