### ISSUE TITLE
Tx stats incorrect for XL710 40Gbps

### ISSUE THREAD

**Issue by atheurer** [emmericp/MoonGen#112]
There seems to be a problem with the way Tx stats are reported for Intel XL710 (fortville) 40Gbps adapters.  Below is output which shows both Tx and Rx stats, with the device-under-test simply forwarding packets back to the MoonGen packet generator:

[Device: id=3] Received 14121100 packets, current rate 14.12 Mpps, 7229.98 MBit/s, 9489.35 MBit/s wire rate.
[Device: id=2] Sent 12844125 packets, current rate 12.84 Mpps, 7149.29 MBit/s, 9204.31 MBit/s wire rate.
[Device: id=3] Received 28245004 packets, current rate 14.12 Mpps, 7231.41 MBit/s, 9491.23 MBit/s wire rate.
[Device: id=2] Sent 25703720 packets, current rate 12.86 Mpps, 7158.05 MBit/s, 9215.57 MBit/s wire rate.
[Device: id=3] Received 42368237 packets, current rate 14.12 Mpps, 7231.13 MBit/s, 9490.85 MBit/s wire rate.

Generally one would not expect the packets forwarded back to exceed the transmitted packets :)

The device-under-test is using ovs-dpdk, and the stats reported from ovs-vsctl dump-ports <bridge> agree with the Rx stats from MoonGen.

This is with dpdk2.0 branch and lau script found here: https://github.com/atheurer/MoonGen/blob/dpdk2.x-opnfv/examples/opnfv-vsperf.lua

**Comment by atheurer** [comment]
This may only be a problem when using software rate control, investigating...

**Comment by emmericp** [comment]
The i40e statistics are unfortunately weird and might be buggy, especially when used with the "software" rate control.

**Comment by emmericp** [comment]
I checked this with the l2-poisson-load-latency script and got these results:

XL710
 [Device: id=2] Received 29986524 packets with 1919137536 bytes payload (including CRC).
 [[Device: id=0]] Sent 29979936 packets with 1918715904 bytes payload (including CRC).

X540
 [Device: id=4] Received 4784842 packets with 306229888 bytes payload (including CRC).
 [[Device: id=3]] Sent 4781700 packets with 306028800 bytes payload (including CRC).

So this is not specific to the XL710 NIC but some other bug in the DPDK2.0 branch.

**Comment by maryamtahhan** [comment]
I think there are a bunch of fixes for stats in the latest version of DPDK, http://dpdk.org/dev/patchwork/project/dpdk/list/?submitter=317&state=*&q=stats&archive=true, if you can't find a fix in that list, can you please submit a bug to the DPDK mailing list

**Comment by emmericp** [comment]
fixed in https://github.com/emmericp/MoonGen/commit/4353d3e3e554498d0ee66013e06f7dd3773c1d92
