### ISSUE TITLE
issue running pcap examples

### ISSUE THREAD

**Issue by zhangxutlky** [emmericp/MoonGen#119]
sudo ./build/MoonGen ./examples/pcap/rx-to-pcap.lua 0
pcapSinkSlave is running
[FATAL] Lua error in task pcapSinkSlave
lua/include/pcap.lua:137: attempt to perform arithmetic on 'uint64_t' and 'nil'
Stack Traceback
===============
(2) Lua function 'pcapSinkSlave' at file './examples/pcap/rx-to-pcap.lua:52' (best guess)
        Local variables:
         queue = [RxQueue: id=1, qid=0]  {qid:0, dev:[Device: id=1], id:1}
         sink = string: "pcap-port-1.pcap"
         maxp = number: 0
         numbufs = number: 100
         bufs = table: 0x405a19c0  {array:cdata<struct rte_mbuf *[?]>: 0x405a1c38, maxSize:100, size:100, alloc:function: 0x41c68e00 (more...)}
         pcapSinkWriter = table: 0x405a22f8  {file:file (0x7f06a0000980)}
         pkts = number: 0
         rxnum = number: 100
         rx = number: 1
         (for index) = number: 1
         (for limit) = number: 1
         (for step) = number: 1
         i = number: 1
(3) global C function 'xpcall'
(4) Lua upvalue 'slave' at file 'lua/include/main.lua:128'
        Local variables:
         taskId = number: 1
         userscript = string: "./examples/pcap/rx-to-pcap.lua"
         args = table: 0x406598d8  {1:pcapSinkSlave, 2:[RxQueue: id=1, qid=0], 3:pcap-port-1.pcap, 4:0}
         (*temporary) = table: 0x405a1720  {}
         (*temporary) = C function: select
         (*temporary) = number: 2
(5) Lua function 'main' at file 'lua/include/main.lua:143' (best guess)
        Local variables:
         task = string: "slave"
        lua/include/pcap.lua:137: attempt to perform arithmetic on 'uint64_t' and 'nil'

**Comment by duk3luk3** [comment]
Hi,

very sorry you're experiencing this, something must have been merged prematurely. Please try commit adf5e97ab9aaa442f0540d73c2036f2657b9961e from https://github.com/duk3luk3/MoonGen/tree/pcap-timestamping while we sort this out!

**Comment by zhangxutlky** [comment]
this new update crashes other examples too. 
sudo ./build/MoonGen ./examples/l3-tcp-syn-flood.lua 0

[FATAL] Lua error in task loadSlave
lua/include/utils.lua:317: bad argument #1 to 'floor' (number expected, got cdata)
Stack Traceback
===============
(2) Lua global 'getTimeMicros' at file 'lua/include/utils.lua:317'
	Local variables:
	 h = nil
	 m = nil
	 s = nil
	 u = nil
(3) Lua method 'dump' at file 'lua/include/packet.lua:388'
	Local variables:
	 bytes = number: 60
	 stream = file (0x7f4ca2617400)
	 (*temporary) = C function: builtin#99
	 (*temporary) = file (0x7f4ca2617400)
(4) Lua method 'dump' at file 'lua/include/packet.lua:126'
	Local variables:
	 bytes = nil
	 stream = nil
(5) Lua function 'loadSlave' at file './examples/l3-tcp-syn-flood.lua:75' (best guess)
	Local variables:
	 port = number: 0
	 queue = number: 0
	 minA = string: "198.83.85.200"
	 numIPs = number: 100
	 minIP = number: -9.67617e+08
	 ipv4 = boolean: true
	 packetLen = number: 60
	 queue = [TxQueue: id=0, qid=0]  {id:0, rate:9600.375014649, qid:0, dev:[Device: id=0], speed:10000}
	 bufs = table: 0x413b9760  {array:cdata<struct rte_mbuf *[?]>: 0x417b6dc0, maxSize:128, size:128, mem:cdata<struct mempool *>: 0x7f4c96ad9100 (more...)}
	 counter = number: 1
	 c = number: 0
	 txStats = table: 0x413b9840  {format:plain, mbit:table: 0x413b9890, file:file (0x7f4ca2617400), total:0 (more...)}
	 (for generator) = Lua function 'it' (defined at line 365 of chunk lua/include/memory.lua)
	 (for state) = table: 0x413b9760  {array:cdata<struct rte_mbuf *[?]>: 0x417b6dc0, maxSize:128, size:128, mem:cdata<struct mempool *>: 0x7f4c96ad9100 (more...)}
	 (for control) = number: 1
	 i = number: 1
(6) global C function 'xpcall'
(7) Lua upvalue 'slave' at file 'lua/include/main.lua:128'
	Local variables:
	 taskId = number: 1
	 userscript = string: "./examples/l3-tcp-syn-flood.lua"
	 args = table: 0x40d61f70  {1:loadSlave, 2:0, 3:0, 4:198.83.85.200, 5:100}
	 (*temporary) = table: 0x40d62080  {}
	 (*temporary) = C function: select
	 (*temporary) = number: 2
(8) Lua function 'main' at file 'lua/include/main.lua:143' (best guess)
	Local variables:
	 task = string: "slave"
	lua/include/utils.lua:317: bad argument #1 to 'floor' (number expected, got cdata)

**Comment by zhangxutlky** [comment]
the problem still exists in "l3-tcp-syn-flood.lua" after the fix

**Comment by emmericp** [comment]
fixed

**Comment by zhangxutlky** [comment]
thx
