### ISSUE TITLE
DPDK dep fails compilation on Fedora 23

### ISSUE THREAD

**Issue by ashokez** [emmericp/MoonGen#121]
Looks like the old DPDK version fails to build with newer gcc (or other build tool versions/issues). This issue may happen on other newer distros possibly.

I tried replacing the dpdk director under deps with newer version, just to see if the dpdk build passes. It correctly built with DPDK 16.04 

http://dpdk.org/browse/dpdk/snapshot/dpdk-16.04.tar.gz

as expected, i ran into issues compiling MoonGen sources. Any plans to update to new DPDK version ?

**Comment by vincentmli** [comment]
I am running MoonGen on VMware ESXi VM that it requires the most recent DPDK build for vmxnet3 works properly, I agree it would be great to update the MoonGen DPDK to newer version

**Comment by emmericp** [comment]
I just updated the master branch to DPDK 2.2

upgrade to 16.04 coming soon

**Comment by ashokez** [comment]
thank you, i verified it builds fine on Fedora 23.
