### ISSUE TITLE
MoonGen coredump in ESXi VM after DPDK-2.2 merge

### ISSUE THREAD

**Issue by vincentmli** [emmericp/MoonGen#122]
Hi,

I am able to run MoonGen on ESXi VM before the MoonGen DPDK-2.2 merge with following diff:
```
diff --git a/examples/l3-tcp-syn-flood.lua b/examples/l3-tcp-syn-flood.lua
index 306393f..01b6d4a 100644
--- a/examples/l3-tcp-syn-flood.lua
+++ b/examples/l3-tcp-syn-flood.lua
@@ -15,7 +15,7 @@ function master(txPorts, minIp, numIps, rate)
        rate = rate or 0
        for currentTxPort in txPorts:gmatch("(%d+),?") do
                currentTxPort = tonumber(currentTxPort)
-               local txDev = device.config{ port = currentTxPort }
+               local txDev = device.config{ port = currentTxPort, rxQueues = 1, txQueues = 1 }

diff --git a/lua/include/device.lua b/lua/include/device.lua
index 4d8f8dc..5e8e617 100644
--- a/lua/include/device.lua
+++ b/lua/include/device.lua
@@ -148,8 +148,8 @@ function mod.config(...)

        args.rxQueues = args.rxQueues or 1
        args.txQueues = args.txQueues or 1
-       args.rxDescs  = args.rxDescs or 512
-       args.txDescs  = args.txDescs or 1024
+       args.rxDescs  = args.rxDescs or 128
+       args.txDescs  = args.txDescs or 512

@@ -203,7 +203,7 @@ function mod.config(...)
        local isi40e = dpdkc.get_pci_id(args.port) == mod.PCI_ID_XL710
                        or dpdkc.get_pci_id(args.port) == mod.PCI_ID_X710
        -- TODO: support options
-       local rc = dpdkc.configure_device(args.port, args.rxQueues, args.txQueues, args.rxDescs, args.txDescs, args.speed, args.mempool, args.dropEnable, rss_enabled, rss_hash_mask, args.disableOffloads or false, isi40e)
+       local rc = dpdkc.configure_device(args.port, args.rxQueues, args.txQueues, args.rxDescs, args.txDescs, args.speed, args.mempool, args.dropEnable, rss_enabled, rss_hash_mask, args.disableOffloads or true, isi40e)

@@ -586,7 +586,7 @@ function txQueue:setRate(rate)
                return
        end
        if id ~= mod.PCI_ID_82599 and id ~= mod.PCI_ID_X540 and id ~= mod.PCI_ID_X520 and id ~= mod.PCI_ID_X520_T2 then
-               log:fatal("TX rate control not yet implemented for this NIC")
+               --- log:fatal("TX rate control not yet implemented for this NIC")

```

with the new DPDK-2.2 merge, the the core dump backtrace as below:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `build/MoonGen examples/l3-tcp-syn-flood.lua 0 10.0.0.1 128 100'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004223c2 in read_reg32 (reg=16960, port=0 '\000') at /usr/src/MoonGen/src/device.c:53
53              return *(volatile uint32_t*)(registers[port] + reg);
(gdb) bt
#0  0x00000000004223c2 in read_reg32 (reg=16960, port=0 '\000') at /usr/src/MoonGen/src/device.c:53
#1  configure_device (port=0, rx_queues=1, tx_queues=<optimized out>, rx_descs=128, tx_descs=<optimized out>, link_speed=<optimized out>, mempool=0x7f8380933ec0, drop_en=1,
    rss_enable=0 '\000', hash_functions=0x408e14e0, disable_offloads=1, is_i40e_device=0) at /usr/src/MoonGen/src/device.c:229
#2  0x00007f83c4253674 in ?? () from /usr/src/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#3  0x00007f83c4291f34 in ?? () from /usr/src/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#4  0x00007f83c42a5df6 in ?? () from /usr/src/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#5  0x00007f83c4251583 in ?? () from /usr/src/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#6  0x00007f83c426184d in lua_pcall () from /usr/src/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#7  0x000000000042016c in main (argc=6, argv=<optimized out>) at /usr/src/MoonGen/src/main.c:37

any clue?

**Comment by emmericp** [comment]
Probably related to #106 
This will probably be fixed this week

**Comment by emmericp** [comment]
did the DPDK 16.04 upgrade fix this?
