### ISSUE TITLE
Fatal error when try to write to pcap file.

### ISSUE THREAD

**Issue by adolia** [emmericp/MoonGen#127]
Fatal Error "lua/include/packet.lua:118: 'struct rte_mbuf' has no member named 'pkt'" when it try to write to pcap file.

**Comment by emmericp** [comment]
@duk3luk3

**Comment by scholzd** [comment]
If I am correct I fixed that issue with this commit some days ago https://github.com/emmericp/MoonGen/commit/6d48c37e8151a2f3e79264f55c765047318f6aeb

Try it with the new version.

**Comment by adolia** [comment]
Thanks!

**Comment by adolia** [comment]
I get this error when try to send pcap file:
[FATAL] Lua error in task master
lua/include/packet.lua:118: 'struct rte_mbuf' has no member named 'pkt'
Stack Traceback
===============
(2) Lua global 'writeRecordHeader' at file 'lua/include/pcap.lua:62'
	Local variables:
	 file = file (0x01282110)
	 ts = number: 0
(3) Lua method 'write' at file 'lua/include/pcap.lua:140'
	Local variables:
	 self = table: 0x41245028  {file:file (0x01282110)}
	 bufs = table: 0x41251308  {array:cdata<struct rte_mbuf *[?]>: 0x412513a8, maxSize:12, size:12, mem:cdata<struct mempool *>: 0x7ff4f9a5e700 (more...)}
	 n = number: 12
	 ts = nil
	 noflush = nil
	 (for index) = number: 1
	 (for limit) = number: 12
	 (for step) = number: 1
	 i = number: 1
(4) Lua global 'simplePcapStoreAndLoadTestSlave' at file 'examples/pcap/pcap-test.lua:67'
	Local variables:
	 source = string: "test.pcap"
	 sink = string: "test-sink.pcap"
	 bufs = table: 0x41251308  {array:cdata<struct rte_mbuf *[?]>: 0x412513a8, maxSize:12, size:12, mem:cdata<struct mempool *>: 0x7ff4f9a5e700 (more...)}
	 rx = number: 12
	 pcapWriter = table: 0x41245028  {file:file (0x01282110)}
(5) Lua function 'master' at file 'examples/pcap/pcap-test.lua:31' (best guess)
	Local variables:
	 source = string: "test.pcap"
	 sink = string: "test-sink.pcap"
(6) global C function 'xpcall'
(7) Lua upvalue 'slave' at file 'lua/include/main.lua:108'
	Local variables:
	 _ = string: "build/./MoonGen"
	 file = string: "examples/pcap/pcap-test.lua"
	 _ = nil
	 cfgfile = nil
	 devices = table: 0x404676d0  {1:table: 0x40467878}
	 args = table: 0x40467c60  {1:test.pcap}
(8) Lua function 'main' at file 'lua/include/main.lua:144' (best guess)
	Local variables:
	 task = string: "master"
	lua/include/packet.lua:118: 'struct rte_mbuf' has no member named 'pkt'
