### ISSUE TITLE
MoonGen can't reach line rate with 82599EB 10-Gigabit SFI/SFP+ Network Connection

### ISSUE THREAD

**Issue by hristotrifonov** [emmericp/MoonGen#130]
Hi,

I'm running MoonGen on a development machine with core i7-3770K, 16GB Ram, CentOS 7 with 3.10.0-327.18.2.el7.x86_64 kernel, DPDK 16.04 and NIC 82599EB 10-Gigabit SFI/SFP+ Dual port and the performance is very low 1.98 Mpps. Here is an output:

[pktgen@pktgen MoonGen]$ sudo ./build/MoonGen ./examples/l2-poisson-load-latency.lua 0 1
[INFO]  Initializing DPDK. This will take a few seconds...
[INFO]  Found 2 usable devices:
   Device 0: 00:1B:21:91:39:EC (82599EB 10-Gigabit SFI/SFP+ Network Connection)
   Device 1: 00:1B:21:91:39:ED (82599EB 10-Gigabit SFI/SFP+ Network Connection)
[WARN]  You are using a deprecated method for invoking device.config. config(...) should be used with named arguments. For details: see documentation
[WARN]  You are using a deprecated method for invoking device.config. config(...) should be used with named arguments. For details: see documentation
[INFO]  Waiting for devices to come up...
[INFO]  Device 0 (00:1B:21:91:39:EC) is up: full-duplex 10000 MBit/s
[INFO]  Device 1 (00:1B:21:91:39:ED) is up: full-duplex 10000 MBit/s
[INFO]  2 devices are up.
[WARN]  l2 filter error: -22
[[Device: id=0]] Sent 1983681 packets, current rate 1.98 Mpps, 1015.60 MBit/s, 1332.98 MBit/s wire rate.
[Device: id=1] Received 1983034 packets, current rate 1.98 Mpps, 1015.27 MBit/s, 1332.54 MBit/s wire rate.
[[Device: id=0]] Sent 3966921 packets, current rate 1.98 Mpps, 1015.41 MBit/s, 1332.73 MBit/s wire rate.

Can you please point out what the problem might be here. 
I can reproduce exactly the same problem with Fedora 22, 4.0.4 kernel and DPDK 16.04 on the same machine.
Pktgen-dpdk runs fine with current configurations reaching 14.88 Mpps.

**Comment by emmericp** [comment]
The rate is a command line argument and defaults to 2 mpps. Start the script without arguments to see all available options.
