### ISSUE TITLE
MoonGen can't reach line rate when sending pcap file

### ISSUE THREAD

**Issue by adolia** [emmericp/MoonGen#132]
Hi, 
when I'm running MoonGen to send pcap file it can't reach line rate.

[HH PktGen /home/celare/MoonGen]#build/./MoonGen examples/pcap/tx-from-pcap.lua 1 0 test.pcap 
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: 10 hugepages of size 1073741824 reserved, but no mounted hugetlbfs found for that size
[INFO]  Found 2 usable devices:
   Device 0: 90:E2:BA:C0:5A:AC (82599EB 10-Gigabit SFI/SFP+ Network Connection)
   Device 1: 90:E2:BA:C0:5A:AD (82599EB 10-Gigabit SFI/SFP+ Network Connection)
pcapLoadSlave is running
[Device: id=1] Sent 1918720 packets, current rate 1.91 Mpps, 980.29 MBit/s, 1286.64 MBit/s wire rate.
[Device: id=1] Sent 3798912 packets, current rate 1.88 Mpps, 962.60 MBit/s, 1263.41 MBit/s wire rate.
[Device: id=1] Sent 5787776 packets, current rate 1.99 Mpps, 1018.29 MBit/s, 1336.51 MBit/s wire rate.
[Device: id=1] Sent 7748992 packets, current rate 1.96 Mpps, 1004.13 MBit/s, 1317.92 MBit/s wire rate.
[Device: id=1] Sent 9509760 packets, current rate 1.76 Mpps, 901.50 MBit/s, 1183.22 MBit/s wire rate.
[Device: id=1] Sent 11328896 packets, current rate 1.82 Mpps, 931.18 MBit/s, 1222.17 MBit/s wire rate.
[Device: id=1] Sent 13179520 packets, current rate 1.85 Mpps, 947.51 MBit/s, 1243.61 MBit/s wire rate.
[Device: id=1] Sent 15119616 packets, current rate 1.94 Mpps, 993.31 MBit/s, 1303.73 MBit/s wire rate.
[Device: id=1] Sent 16910592 packets, current rate 1.79 Mpps, 916.95 MBit/s, 1203.50 MBit/s wire rate.
[Device: id=1] Sent 18715648 packets, current rate 1.81 Mpps, 924.19 MBit/s, 1212.99 MBit/s wire rate.
[Device: id=1] Sent 20491904 packets, current rate 1.78 Mpps, 909.33 MBit/s, 1193.50 MBit/s wire rate.
[Device: id=1] Sent 22287232 packets, current rate 1.79 Mpps, 918.13 MBit/s, 1205.05 MBit/s wire rate.
[Device: id=1] Sent 24083968 packets, current rate 1.80 Mpps, 919.91 MBit/s, 1207.38 MBit/s wire rate.
[Device: id=1] Sent 25917056 packets, current rate 1.83 Mpps, 938.51 MBit/s, 1231.79 MBit/s wire rate.
[Device: id=1] Sent 27714304 packets, current rate 1.80 Mpps, 920.16 MBit/s, 1207.71 MBit/s wire rate.
[Device: id=1] Sent 29481472 packets, current rate 1.76 Mpps, 903.67 MBit/s, 1186.06 MBit/s wire rate.
[Device: id=1] Sent 31244672 packets, current rate 1.76 Mpps, 900.13 MBit/s, 1181.42 MBit/s wire rate.
[Device: id=1] Sent 32979968 packets, current rate 1.74 Mpps, 888.43 MBit/s, 1166.06 MBit/s wire rate.
^C[Device: id=1] Sent 34642176 packets with 2217099264 bytes payload (including CRC).
[Device: id=1] Sent 1.826509 (StdDev 0.074668) Mpps, 935.172512 (StdDev 38.229935) MBit/s, 1227.413922 (StdDev 50.176790) MBit/s wire rate on average.
pcapLoadSlave: end

**Comment by emmericp** [comment]
does the pcap contain packets at line rate?

**Comment by adolia** [comment]
do you mean at what rate packets was captured?

**Comment by emmericp** [comment]
the script replays the pcap at the rate specified in the pcap

**Comment by adolia** [comment]
ok, thanks, I'll check this issue!
and I have another problem when I try to send pcap file I've got segmentation fault:
from gdb:
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb0be7700 (LWP 22714)]
0x00000000004de0e4 in ixgbe_xmit_pkts ()

have you any suggestion to solve this problem?

**Comment by adolia** [comment]
The traffic was captured to pcap file with 10 Gbit/s rate using 82599EB 10-Gigabit SFI/SFP+ Network Connection.

**Comment by emmericp** [comment]
the code of the example and pcap implementation does not look optimized enough (small file IOs) to cope with line-rate pcaps, that could be the problem

I guess the pcap reader is meant to load a pcap once and then replay it for such high rates, so I'd suggest to try that


(I wrote neither the pcap reader nor the example you are using, so I might be wrong here)

**Comment by adolia** [comment]
I'll check, thanks!
and what about seg fault?

**Comment by emmericp** [comment]
looks like a null paket got into the driver, i forwarded it to the dev who wrote that code

**Comment by adolia** [comment]
ok, thanks a lot!

**Comment by duk3luk3** [comment]
Hello!

1) Can you give us a minimal pcap sample that reproduces the segfault?

2) I've reproduced your sending rate issue - I will see what we can do about it!

**Comment by adolia** [comment]
Hi!
I'am attaching pcap file that reproduces segfault.

**Comment by adolia** [comment]
Hi!
I'm attaching pcap file that reproduces the segfault!

**Comment by adolia** [comment]
Hi,
I`m attaching pcap file that reproduced segfault.
Please, rename test.pdf file to test.pcap.
[test.pdf](https://github.com/emmericp/MoonGen/files/271229/test.pdf)

**Comment by duk3luk3** [comment]
I've narrowed the crash down to `pkt:setRawPacket` in [packet.lua](https://github.com/emmericp/MoonGen/blob/master/lua/include/packet.lua#L688). It seems the `ffi.copy` fails. But I have no idea why and don't know how to debug into that.

**Comment by adolia** [comment]
So, the problem with pcap file or MoonGen module. Because I was tested a lot of pcaps and got segfault.

**Comment by duk3luk3** [comment]
I've done all my tests with pcaps generated by tcpdump and tshark, as well as pcaps converted using tshark from pcapng files generated by wireshark. I've never encountered a segfault with those.

**Comment by adolia** [comment]
Ok, thanks!
My test.pcap genereted by wireshark, maybe that is the problem. Can you send me a pcap sample that never produced segfault, that I'll check my MoonGen.

**Comment by adolia** [comment]
And what about pcap sending rate, do you have any suggestion?

**Comment by duk3luk3** [comment]
To clarify about the segfault - this is pretty clearly a bug in MoonGen. I hope @emmericp can say something about it.

As for the pcap sending rate, I've tried some things including a naive buffered file reader implementation and it's unclear to me where exactly the latency is. Some profiling is required to figure that out. Ideally, pcap files should just be mmap'ed for replaying - but mmap'ing isn't implemented in MoonGen. If you just want to replay pcaps, I'd suggest you use the tcpreplay application.

**Comment by adolia** [comment]
Hi!
I have one more question!
Can I replay pcap traffic at original pcap captured rate (base on pcap timestamps)?

**Comment by duk3luk3** [comment]
The pcap module can do that and it's used in one of the example scripts.

**Comment by emmericp** [comment]
the example has been removed from moongen in https://github.com/emmericp/MoonGen/commit/4353d3e3e554498d0ee66013e06f7dd3773c1d92 because the current pcap implementation is inherently slow; we've hence decided to not include this example any longer

replaying pcaps is not a design goal of moongen

however, pull requests for a proper pcap reader based on mmap() are welcome

**Comment by emmericp** [comment]
I've rewritten the pcap implementation to something more reasonable. You can now capture and replay pcaps at line rate.

**Comment by adolia** [comment]
Many thanks for this feature. I have another question, can I modify pcap packets on runtime (let say, change ip or port)?
