### ISSUE TITLE
DDIO/DPDK performance issue verification?

### ISSUE THREAD

**Issue by jlixfeld** [emmericp/MoonGen#133]
I presume based on the output below, I'm running into the performance impact issues mentioned in the WARN notices.  I'm running 3.16 on Debian 8, but is there any way to tell definitively if this is my issue?

root@pgen:/home/jlixfeld/MoonGen# ./build/MoonGen ./examples/quality-of-service-test.lua 4 1 10000 10000
[INFO]  Initializing DPDK. This will take a few seconds...
[INFO]  Found 6 usable devices:
   Device 0: 00:0C:BD:08:80:9C (82599EB 10-Gigabit SFI/SFP+ Network Connection)
   Device 1: 00:0C:BD:08:80:9D (82599EB 10-Gigabit SFI/SFP+ Network Connection)
   Device 2: 00:0C:BD:08:80:9A (82599EB 10-Gigabit SFI/SFP+ Network Connection)
   Device 3: 00:0C:BD:08:80:9B (82599EB 10-Gigabit SFI/SFP+ Network Connection)
   Device 4: 00:0C:BD:08:80:98 (82599EB 10-Gigabit SFI/SFP+ Network Connection)
   Device 5: 00:0C:BD:08:80:99 (82599EB 10-Gigabit SFI/SFP+ Network Connection)
[WARN]  You are running Linux >= 3.14, DDIO might not be working with DPDK in this setup!
[WARN]  This can cause a huge performance impact (one memory access per packet!) preventing MoonGen from reaching line rate.
[WARN]  Try using an older kernel (we recommend 3.13) if you see a low performance or huge cache miss ratio.
[INFO]  Waiting for devices to come up...
[INFO]  Device 1 (00:0C:BD:08:80:9D) is up: full-duplex 10000 MBit/s
[INFO]  Device 4 (00:0C:BD:08:80:98) is up: full-duplex 10000 MBit/s
[INFO]  2 devices are up.
[INFO]  Sending 10000 MBit/s background traffic to UDP port 43
[INFO]  Sending 10000 MBit/s foreground traffic to UDP port 42
[Port 43] Sent 4271022 packets, current rate 4.27 Mpps, 4373.43 MBit/s, 5056.77 MBit/s wire rate.
[Port 43] Received 4266435 packets, current rate 4.27 Mpps, 4368.77 MBit/s, 5051.39 MBit/s wire rate.
...
...
...
^C[Port 42] Sent 132866559 packets with 17006919552 bytes payload (including CRC).
[Port 42] Sent 4.222271 (StdDev 0.000014) Mpps, 4323.604997 (StdDev 0.014079) MBit/s, 4999.168278 (StdDev 0.016279) MBit/s wire rate on average.
[Port 43] Sent 132961815 packets with 17019112320 bytes payload (including CRC).
[Port 43] Sent 4.222271 (StdDev 0.000014) Mpps, 4323.605062 (StdDev 0.014015) MBit/s, 4999.168353 (StdDev 0.016205) MBit/s wire rate on average.
PMD: ixgbe_dev_tx_queue_stop(): Could not disable Tx Queue 1
PMD: ixgbe_dev_tx_queue_stop(): Could not disable Tx Queue 0
[INFO]  Saving histogram to 'hist-background.csv'
[Port 42] Received 132864752 packets with 17006688256 bytes payload (including CRC).
[Port 42] Received 4.222263 (StdDev 0.000033) Mpps, 4323.596824 (StdDev 0.033699) MBit/s, 4999.158827 (StdDev 0.038964) MBit/s wire rate on average.
[Port 43] Received 132956201 packets with 17018393728 bytes payload (including CRC).
[Port 43] Received 4.222261 (StdDev 0.000027) Mpps, 4323.595412 (StdDev 0.027734) MBit/s, 4999.157196 (StdDev 0.032067) MBit/s wire rate on average.
[INFO]  Saving histogram to 'hist-foreground.csv'
[Background traffic] Samples: 15241, Average: 316.2 ns, StdDev: 12.1 ns, Quartiles: 307.2/313.6/326.4 ns
[Foreground traffic] Samples: 15318, Average: 316.1 ns, StdDev: 12.1 ns, Quartiles: 307.2/313.6/326.4 ns

**Comment by emmericp** [comment]
I don't see a problem with your output: the example uses unidirectional traffic and both flows together add up to 10 Gbit/s.
