### ISSUE TITLE
FDir filters on XL710 not working

### ISSUE THREAD

**Issue by emmericp** [emmericp/MoonGen#138]
This breaks L3 timestamping since DPDK 2.2

**Comment by jgjl** [comment]
Unfortunately, Intel says that the 710 chipset does not support hardware timestamping on non-PTP packets:
https://communities.intel.com/thread/60781
https://communities.intel.com/thread/93966

**Comment by emmericp** [comment]
Our timestamped packets are "close enough" for the XL710 to be considered PTP packets (it just checks the version field.
The code worked fine on DPDK 2.0 with the old filter API.

**Comment by jgjl** [comment]
Great! And good to know that we will be able to use our 710 cards with Moongen.

**Comment by emmericp** [comment]
I posted to the DPDK mailing list about this since I have no clue what might be wrong here.

http://dpdk.org/ml/archives/users/2016-June/000683.html

**Comment by emmericp** [comment]
i just fixed this in our new framework here: https://github.com/Phobos-Framework/phobos/commit/e2379740a175bbbb396978a08bca8cf8019c248a

however, the changes are too messy to backport. I'll port moongen to this new framework later this week or next week.

**Comment by emmericp** [comment]
fixed in https://github.com/emmericp/MoonGen/commit/4353d3e3e554498d0ee66013e06f7dd3773c1d92
