### ISSUE TITLE
Link down, assuming 10 GbE connection

### ISSUE THREAD

**Issue by thomas-schultz** [emmericp/MoonGen#143]
System: Ubuntu 16.04, Linux 4.4.0-24-generic, Intel 82599ES Dual Port SFP+ (back-to-back)

MoonGen reports Link Down, but does send traffic:

[INFO]  Waiting for devices to come up...
[INFO]  Device 0 (90:E2:BA:89:D7:B8) is DOWN: 0 MBit/s
[INFO]  Device 1 (90:E2:BA:89:D7:B9) is DOWN: 0 MBit/s
[INFO]  0 devices are up.
[WARN]  Link down, assuming 10 GbE connection
...
[Device: id=0] Sent 11464271 packets, current rate 11.46 Mpps, 5869.68 MBit/s, 7703.96 MBit/s wire rate.
[Device: id=1] Received 11464497 packets, current rate 11.46 Mpps, 5869.69 MBit/s, 7703.97 MBit/s wire rate.
[Device: id=0] Sent 22931716 packets, current rate 11.47 Mpps, 5871.51 MBit/s, 7706.30 MBit/s wire rate.
[Device: id=1] Received 22931944 packets, current rate 11.47 Mpps, 5871.51 MBit/s, 7706.30 MBit/s wire rate.
...

**Comment by emmericp** [comment]
How are they showing up on startup? Correctly identified as 82599?

**Comment by emmericp** [comment]
should be fixed in https://github.com/emmericp/MoonGen/commit/4353d3e3e554498d0ee66013e06f7dd3773c1d92
