### ISSUE TITLE
NYI: unsupported C type conversion

### ISSUE THREAD

**Issue by paulin007** [emmericp/MoonGen#145]
Hi,

When I try to retrieve the IPv6 address in "union ip6_address" format, I get a "Not Yet Implemented" function.
The NYI is caused by this line:
https://github.com/emmericp/MoonGen/blob/master/lua/include/proto/ip6.lua#L56

Any idea on how I can achieve the same result without falling into a NYI ?

![schermata 2016-07-18 alle 10 00 25](https://cloud.githubusercontent.com/assets/11475598/16910117/0b781d8a-4cd7-11e6-9bf5-a3116257a7fe.png)

**Comment by emmericp** [comment]
you can access it directly in the script and use the raw data if that's better for your usecase
