### ISSUE TITLE
Could not run main script: lua/include/dpdk.lua:16: bad argument #1 to 'lshift' (number expected, got cdata)

### ISSUE THREAD

**Issue by santiagorr** [emmericp/MoonGen#146]
Hi,

I am trying to test the current MoonGen version, but I got the same error when I try to run, at least, three example scripts:

 % sudo ./build/MoonGen examples/tx-multi-core.lua 0 10000 1
Could not run main script: lua/include/dpdk.lua:16: bad argument #1 to 'lshift' (number expected, got cdata)
Lua error: attempt to call a nil value

same results with ./examples/dump.lua and ./examples/pcap/rx-to-pcap.lua

Maybe the problem is mine, but I cannot figure out where it is. I have tested a backup version based on e721722e5caa6ba778216099ed315cb9511cdedb (April 3 2016) that works well.

Some version info:

 % git show HEAD 
commit ad97b1b44f05077d06c43f79baeead0b88a810da

 % git submodule status 
 10c8386121a91f42c617b52cc669ee486a39d836 deps/doxygen-lua (v0.04-2-g10c8386)
 353723909bc7f97867c6f4476297d0470c7a845c deps/dpdk (v2.0.0-2332-g3537239)
 ce1ad870c3d9536c759ecada89717c3317d56a3d deps/luajit (v2.1.0-beta2-79-gce1ad87)

Cheers,

Santiago

**Comment by emmericp** [comment]
Looks like you are using an old version of LuaJIT.

However, the output of git submodule status looks correct...

Can you try to run make clean in LuaJIT? Alternatively, try to checkout a new clean version.

**Comment by santiagorr** [comment]
Problem solved. From one side, I had forgotten about an additional libluajit that I installed (from distribution packages), and it was interfering. And I was building without root privileges. Sorry for the noise and thanks!
