### ISSUE TITLE
Moongen Intel 82574L/82571EB

### ISSUE THREAD

**Issue by ldacol** [emmericp/MoonGen#148]
Hello, 

I am running some tests with moongen running on a Centos 7.0. Specifically I'd like to see moongen working with a 82574L, which according to the DPDK documentation is a supported chipset. However I am not having much success in running any of the example scripts except for rx-pkts-distribution.lua. 
My requirements would be transmitting from first port on this NIC and receive the same traffic from a second port on the same server. 

Same results are obtained with a NIC with an Intel 82571EB chipset (below examples refers to 82574L, however I can provide screenshots on the tests run on an Intel 82571EB

Any assistance is very much appreciated,
Thank you,
Luca

[csadmin@moongen-test ~]$ sudo lspci -v | grep Ethernet -A 1
00:19.0 Ethernet controller: Intel Corporation 82562V-2 10/100 Network Connection (rev 02)
	Subsystem: Dell Device 0238
--
03:00.0 Ethernet controller: Intel Corporation 82574L Gigabit Network Connection
	Subsystem: Intel Corporation Gigabit CT Desktop Adapter
[csadmin@moongen-test ~]$ 

[csadmin@moongen-test MoonGen]$ sudo ./setup-hugetlbfs.sh 
[csadmin@moongen-test MoonGen]$ sudo ./bind-interfaces.sh
Binding interface 0000:03:00.0 to DPDK
[csadmin@moongen-test MoonGen]$ 

[csadmin@moongen-test MoonGen]$ sudo ./build/MoonGen examples/quality-of-service-test.lua 
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
[INFO]  Found 1 usable devices:
   Device 0: 68:05:CA:12:77:B5 (unknown NIC (PCI ID 8086:10d3))
[INFO]  usage: txPort rxPort [bgRate [fgRate]]
[csadmin@moongen-test MoonGen]$ sudo ./build/MoonGen examples/quality-of-service-test.lua 0 0 1000 1000
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
[INFO]  Found 1 usable devices:
   Device 0: 68:05:CA:12:77:B5 (unknown NIC (PCI ID 8086:10d3))
[FATAL] Lua error in task master
lua/include/device.lua:227: Could not configure device 0: error -22
Stack Traceback
===============
(2) Lua method 'fatal' at file 'lua/include/log.lua:129'
	Local variables:
	 self = table: 0x41f7ebf0  {DEBUG:0, fatal:function: 0x41f7abc8, writeToLog:function: 0x41f7aba8, INFO:1 (more...)}
	 str = string: "Could not configure device 0: error -22"
(3) Lua field 'config' at file 'lua/include/device.lua:227'
	Local variables:
	 args = table: 0x41ec2518  {rxQueues:2, stripVlan:true, speed:0, dropEnable:true, mempools:table: 0x402e7a60 (more...)}
	 rss_enabled = number: 0
	 pciId = number: 2.15627e+09
	 isi40e = boolean: false
	 disablePadding = boolean: false
	 rc = number: -22
(4) Lua function 'master' at file 'examples/quality-of-service-test.lua:36' (best guess)
	Local variables:
	 txPort = number: 0
	 rxPort = number: 0
	 bgRate = number: 1000
	 fgRate = number: 1000
	 txDev = nil
	 rxDev = nil
(5) global C function 'xpcall'
(6) Lua upvalue 'slave' at file 'lua/include/main.lua:108'
	Local variables:
	 _ = string: "./build/MoonGen"
	 file = string: "examples/quality-of-service-test.lua"
	 _ = nil
	 cfgfile = nil
	 devices = table: 0x41f88540  {1:table: 0x40d8e808}
	 args = table: 0x40d8ec90  {1:0, 2:0, 3:1000, 4:1000}
(7) Lua function 'main' at file 'lua/include/main.lua:144' (best guess)
	Local variables:
	 task = string: "master"
	lua/include/device.lua:227: Could not configure device 0: error -22
[csadmin@moongen-test MoonGen]$ 

[csadmin@moongen-test MoonGen]$ sudo ./build/MoonGen examples/rx-pkts-distribution.lua 
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
[INFO]  Found 1 usable devices:
   Device 0: 68:05:CA:12:77:B5 (unknown NIC (PCI ID 8086:10d3))
[INFO]  usage: rxPort [saveInterval]
[csadmin@moongen-test MoonGen]$ sudo ./build/MoonGen examples/rx-pkts-distribution.lua 0
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
[INFO]  Found 1 usable devices:
   Device 0: 68:05:CA:12:77:B5 (unknown NIC (PCI ID 8086:10d3))
[INFO]  Waiting for devices to come up...
[INFO]  Device 0 (68:05:CA:12:77:B5) is up: 100 MBit/s
[INFO]  1 devices are up.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Device: id=0] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
[Packets counted] Received 0 packets, current rate 0.00 Mpps, 0.00 MBit/s, 0.00 MBit/s wire rate.
^C[Device: id=0] Received 0 packets with 0 bytes payload (including CRC).
[Device: id=0] Received 0.000000 (StdDev 0.000000) Mpps, 0.000000 (StdDev 0.000000) MBit/s, 0.000000 (StdDev 0.000000) MBit/s wire rate on average.
[Packets counted] Received 0 packets with 0 bytes payload (including CRC).
[Packets counted] Received 0.000000 (StdDev 0.000000) Mpps, 0.000000 (StdDev 0.000000) MBit/s, 0.000000 (StdDev 0.000000) MBit/s wire rate on average.
[csadmin@moongen-test MoonGen]$

**Comment by emmericp** [comment]
you won't be able to run the QoS example with this setup, it requires hardware filtering on payload and at least 3 queue pairs.

I'm currently working on better support for not explicitly supported NICs (showing up as unknown device like yours) which is probably the reason why the stats counters do not work properly for you.

ETA for a fix is sometime next week

**Comment by ldacol** [comment]
Thanks for the quick reply. What I am looking in reality is a simple traffic generation at line rate where I could send traffic from first port and receive on the second one to verify some QoS settings on a switch connected to the traffic generator. At most I would need to modify the ToS field of the IP packed. Again this may not be the first priority in this phase of my project. As soon as I can generate a line rate traffic I would be happy with it. I know I could use iperf3 and get the same result however I would like to explore more  moongen. 
I would appreciate if you can point out any available example or provide some directions if this test can be done with the current NICs. Otherwise I will wait for the fix.

**Comment by emmericp** [comment]
the fix for the IO statistics is already in our new framework: https://github.com/Phobos-Framework/phobos

you can try to see if you get any better result with its "pktgen.lua" example. the architecture is basically the same as moongen.


as for the test you describe: the easiest way would probably be a modified quality-of-service-test.lua. remove the hardware-timestamping task, reduce the number of queues and modify the IP tos field to your liking (ip4TOS in the :fill{} constructor or pkt.ip4.TOS in a packet)

**Comment by emmericp** [comment]
fixed in https://github.com/emmericp/MoonGen/commit/4353d3e3e554498d0ee66013e06f7dd3773c1d92
