### ISSUE TITLE
Unable to initialize RX hardware

### ISSUE THREAD

**Issue by ThomasDeiss** [emmericp/MoonGen#149]
On several  hosts, with different network cards I get the following error when starting MoonGen. The operating system is Ubuntu14.04. Actually I get the error on all hosts I tried so far. Installation of MoonGen has been according to the documentation. Maybe I am missing some simple point as another DPDK based application starts  on the hosts (and I am a newby to DPDK). Any hint would be appreciated.

~/MoonGen$ sudo ./build/MoonGen examples/inter-arrival-times.lua 0
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: No free hugepages reported in hugepages-1048576kB
[INFO]  Found 2 usable devices:
   Device 0: A0:36:9F:B9:59:27 (I350 Gigabit Network Connection)
   Device 1: 3C:FD:FE:A1:6B:C3 (Intel Corporation Ethernet 10G 2P X710 Adapter)
[WARN]  You are running Linux >= 3.14, DDIO might not be working with DPDK in this setup!
[WARN]  This can cause a huge performance impact (one memory access per packet!) preventing MoonGen from reaching line rate.
[WARN]  Try using an older kernel (we recommend 3.13) if you see a low performance or huge cache miss ratio.
PMD: igb_alloc_rx_queue_mbufs(): RX mbuf alloc failed queue_id=0
PMD: eth_igb_start(): Unable to initialize RX hardware
[FATAL] Lua error in task master
lua/include/device.lua:229: Could not configure device 0: error -12
Stack Traceback
===============
(2) Lua method 'fatal' at file 'lua/include/log.lua:129'
	Local variables:
	 self = table: 0x40aa8988  {DEBUG:0, fatal:function: 0x40aaa548, writeToLog:function: 0x40aae6c8, INFO:1 (more...)}
	 str = string: "Could not configure device 0: error -12"
(3) Lua field 'config' at file 'lua/include/device.lua:229'
	Local variables:
	 args = table: 0x40ab6f50  {rxQueues:1, rssNQueues:0, speed:0, mempools:table: 0x41ae29c0, stripVlan:true (more...)}
	 rss_enabled = number: 0
	 pciId = number: 2.15627e+09
	 isi40e = boolean: false
	 disablePadding = boolean: false
	 rc = number: -12
(4) Lua function 'master' at file 'examples/inter-arrival-times.lua:13' (best guess)
	Local variables:
	 rxPort = number: 0
	 waitTime = nil
(5) global C function 'xpcall'
(6) Lua upvalue 'slave' at file 'lua/include/main.lua:108'
	Local variables:
	 _ = string: "./build/MoonGen"
	 file = string: "examples/inter-arrival-times.lua"
	 _ = nil
	 cfgfile = nil
	 devices = table: 0x40e80c48  {1:table: 0x40e80df0, 2:table: 0x40e810a0}
	 args = table: 0x40e81818  {1:0}
(7) Lua function 'main' at file 'lua/include/main.lua:144' (best guess)
	Local variables:
	 task = string: "master"
	lua/include/device.lua:229: Could not configure device 0: error -12

**Comment by emmericp** [comment]
fixed in 117cd8338b4995bcb0960401a798ca1c0dea5605
