### ISSUE TITLE
Asymmetrical ports

### ISSUE THREAD

**Issue by ThomasDeiss** [emmericp/MoonGen#155]
I have a setup with 2 servers, each with 4 ports. The ports among the servers are connected 1:1. One server is running a software switch, reflecting frames received on port 0 on port 1, frames received on port 1 on port0 and similarly for ports 2 and 3. I have verified this with using ostinato on the 2nd server, frames appear on the expected ports.
When running MoonGen, frames appear on different ports, especially the ports do not seem to build pairs. Example command:
sudo ./build/MoonGen examples/l3-load-latency.lua -r 1000 -s 1280 2 1
Following TX -> RX ports work: 0 -> 2, 2 -> 1, 1 -> 3, 3 -> 0. In all other combinations no frames are received. 
Is there any explanation for this behavior? Is there anything in the setup I have to do differently? Any hint would be appreciated. Thanks.

**Comment by emmericp** [comment]
The examples are only examples - you'll have to write a custom script for your setup.

Have a look at l3-load-latency.lua, you probably only have to modify the command line options and the number of tasks started for your scenario.

**Comment by ThomasDeiss** [comment]
Eventually I could not solve the issue. I continued then to use l2-load-latency where this issue does not show up.
