### ISSUE TITLE
Multiple DPDK applications

### ISSUE THREAD

**Issue by 616slayer616** [emmericp/MoonGen#163]
I'm trying to run Moongen and another DPDK application together.

When I try to start a second instance of moongen there will be no hugepages left because the first instance took them all.

When I try to start openvswitch with dpdk first and moongen afterwards, moongen will print:

"Cannot create lock on '/var/run/.rte_config'. Is another primary process running?"

According to [https://github.com/pktgen/Pktgen-DPDK/issues/28](https://github.com/pktgen/Pktgen-DPDK/issues/28) this has to do with the --file-prefix option.
But I don't see a way to set this option in moongen.

Thanks

**Comment by santiagorr** [comment]
El 14/03/17 a las 02:16, Patrick escribió:
>    I'm trying to run Moongen and another DPDK application together.
> 
>    When I try to start a second instance of moongen there will be no
>    hugepages left because the first instance took them all.
> 
>    When I try to start openvswitch with dpdk first and moongen afterwards,
>    moongen will print:
> 
>    "Cannot create lock on '/var/run/.rte_config'. Is another primary process
>    running?"
> 
>    According to [1]pktgen/Pktgen-DPDK#28 this has to do with the
>    --file-prefix option.
>    But I don't see a way to set this option in moongen.

Hi,

Both applications would also need to handle a master and slave process.
Take a look at:
http://dpdk.org/doc/guides/prog_guide/multi_proc_support.html
c.f, the --proc-type argument.

AFAIK, Moongen doesn't implement this (yet?), but Paul Emmerich could
confirm.

Cheers,

  -- Santiago

**Comment by emmericp** [comment]
you can pass arbitrary DPDK options to DPDK by modifying the file `dpdk-conf.lua` in libmoon, there's even an example for your exact use case: https://github.com/libmoon/libmoon/blob/master/dpdk-conf.lua#L21-L24

also, you will probably have to use the blacklist and/or whitelist features

**Comment by 616slayer616** [comment]
ok this seems to work thank you very much!

**Comment by AqsaKashaf** [comment]
Can I give different fileprefix to different MoonGen instances?
