### ISSUE TITLE
Packets sent but not received

### ISSUE THREAD

**Issue by 616slayer616** [emmericp/MoonGen#164]
I'm running the default load latency script like so:
 ./build/MoonGen examples/l3-load-latency.lua 0 1

Sending seems to work but the other interface does not receive anything.

The script logs this:
[Device: id=0] TX: 14.86 Mpps, 7610 Mbit/s (9988 Mbit/s with framing)
[Device: id=1] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)

I have the same issue with other scripts (for example l2 load latency).

The two interfaces are connected to the same layer2 switch and connections with OVS DPKD work.

RX should show the same throughput right?

**Comment by emmericp** [comment]
This indicates that you are not sending packets back to MoonGen.

Did you verify that your device under test forwards packets correctly?

**Comment by 616slayer616** [comment]
I'm not sure if that counts as verified but I tried binding the interfacesame to ovs dpdk and sent traffic back and forth successfully.
