### ISSUE TITLE
Packet losses during simple transmission tests

### ISSUE THREAD

**Issue by davidfernandes1212** [emmericp/MoonGen#166]
Hi !

**System**
CPU : Intel Core i3-6100 (3.70 GHz, 2 cores, 2 threads/core)
NIC : X540-AT2 with 2x10Gbe ports
OS : Linux Ubuntu Server 16.04 (kernel 4.4)

**Issue**
I directly connected an RJ45 cat6 cable between the 2 physical ports of the NIC and tested to transmit from one physical port and to receive at the second one. I performed the same test several times during the night and the results show a random behavior. For most of the tests there is no losses but for some of them I observe packet losses. The number of lost packets is very variable. In the next 2 examples I sent 10 million packets of 124 bytes at 3000 Mbits/s :

_Example 1 :_

> [Port 61235] TX: 2.85 (StdDev 0.00) Mpps, 2916 (StdDev 0) Mbit/s (3371 Mbit/s with framing), total 10000000 packets with 1280000000 bytes (incl. CRC)
> [Port 61235] RX: 2.85 (StdDev 0.00) Mpps, 2916 (StdDev 0) Mbit/s (3371 Mbit/s with framing), total 9999962 packets with 1279995136 bytes (incl. CRC)
>  Lost Packets = 38

_Example 2 :_

> [Port 61235] TX: 2.85 (StdDev 0.00) Mpps, 2916 (StdDev 0) Mbit/s (3371 Mbit/s with framing), total 10000000 packets with 1280000000 bytes (incl. CRC)
> [Port 61235] RX: 2.84 (StdDev 0.00) Mpps, 2913 (StdDev 4) Mbit/s (3368 Mbit/s with framing), total 9963130 packets with 1275280640 bytes (incl. CRC)
>  Lost Packets = 36870

In the worst case I observed that more than the half of the transmitted packets were lost.
Do you have any explanation about that ? You can find next the code of the transmitting and the receiving functions I used. Thank you very much.

```
-- Transmitting function 
function loadSlave(queue, port, pktSize, pktsNum)
	mg.sleepMillis(200)
	local mem = memory.createMemPool(function(buf)
		buf:getUdpPacket():fill{
			pktLength = pktSize,
			ethSrc = ETH_SRC, 
			ethDst = ETH_DST,
			ip4Src = IP_SRC,
			ip4Dst = IP_DST,
			udpSrc = PORT_SRC,
			udpDst = port,			
		}
	end)
	local txCtr = stats:newManualTxCounter("Port " .. port, "plain")
	local bufs = mem:bufArray()
	local txPkts = 0
	while mg.running() and  txPkts < pktsNum do		
		bufs:allocN(pktSize,1)
		for i, buf in ipairs(bufs) do
			buf:setVlan(VLAN_ID,VLAN_PCP,VLAN_CFI)
			local pkt = buf:getUdpPacket()
			txPkts = txPkts + 1
		end
		local sentCount = queue:send(bufs)
		txCtr:updateWithSize(sentCount, pktSize)	
	end
	txCtr:finalize()
end
```

```
--Receiving function
function counterSlave(queue, rxPcktsExpected)
	local bufs = memory.bufArray()
	local ctrs = {}
	local rxPackets = 0
	while mg.running() do
		local rx = queue:tryRecv(bufs,2000000)		
		if rx < 1 then
			break
		end	
		for i = 1, rx do
			local buf = bufs[i]
			local pkt = buf:getUdpPacket()
			rxPackets = rxPackets +1			
			local port = pkt.udp:getDstPort()
			local ctr = ctrs[port]
			if not ctr then
				ctr = stats:newPktRxCounter("Port " .. port, "plain")
				ctrs[port] = ctr
			end
			ctr:countPacket(buf)
		end
		for k, v in pairs(ctrs) do
			v:update()
		end
		bufs:freeAll()
		end
	for k, v in pairs(ctrs) do
		v:finalize()
	end
	print (" Lost Packets = " .. rxPcktsExpected - rxPackets)
end
```

**Comment by emmericp** [comment]
Can you please post a full script for me to execute to test this?

**Comment by davidfernandes1212** [comment]
Of course : 
```

local dpdk	= require "dpdk"
local mg	= require "moongen"
local memory    = require "memory"
local device    = require "device"
local stats     = require "stats"
local log       = require "log"
local timer 	= require "timer"
local hist	= require "histogram"
local packet	= require "packet"
local ffi	= require "ffi" 
local pcap	= require "pcap"

local DEFAULT_PKT_SIZE	= 546 -- without CRC
local DEFAULT_PKTS_NUM	= 5000010
local DEFAULT_PORT_DST	= 61235
local DEFAULT_RATE	= 3000

local ETH_SRC	= "68:05:CA:44:BE:E7"
local ETH_DST	= "68:05:CA:44:BF:D8" 
local IP_SRC	= "175.20.5.123"
local IP_DST	= "192.168.0.123"
local PORT_SRC	= 61234

local VLAN_ID	= 35
local VLAN_PCP	= 3
local VLAN_CFI	= 0 

function configure(parser)
	parser:description("Generates a flow of traffic and compares it with the received one. This example requires an ixgbe NIC due to the used hardware features.")
	parser:argument("txDev", "Device to transmit from."):convert(tonumber)
	parser:argument("rxDev", "Device to receive from."):convert(tonumber)
	parser:option("-l pktSize", "Length of the packets to generate"):default(DEFAULT_PKT_SIZE):convert(tonumber):target("pktSize")
	parser:option("-n pktsNum","Number of packets to send"):default(DEFAULT_PKTS_NUM):convert(tonumber):target("pktsNum")
	parser:option("-p portDst","Destination port"):default(DEFAULT_PORT_DST):convert(tonumber):target("portDst")
	parser:option("-r --rate", "Traffic rate in Mbit/s."):default(DEFAULT_RATE):convert(tonumber):target("rate")
end

function master(args)
	local txDev, rxDev
	if args.txDev == args.rxDev then
		txDev = device.config{port = args.txDev, rxQueues = 1, txQueues = 1, dropEnable = false}
		rxDev = txDev
	else
		txDev = device.config{port = args.txDev, txQueues = 1, dropEnable = false, txDescs = 4096}
		rxDev = device.config{port = args.rxDev, rxQueues = 1, dropEnable = false, rxDescs = 4096}
	end
	device.waitForLinks()	
	txDev:getTxQueue(0):setRate(args.rate)
	mg.startTaskOnCore(1,"loadSlave", txDev:getTxQueue(0), args.portDst, args.pktSize, args.pktsNum)
	mg.startTaskOnCore(2,"counterSlave", rxDev:getRxQueue(0), args.pktsNum)
	mg.waitForTasks()
end

function loadSlave(queue, port, pktSize, pktsNum)
	mg.sleepMillis(200)
	local mem = memory.createMemPool(function(buf)
		buf:getUdpPacket():fill{
			pktLength = pktSize,
			ethSrc = ETH_SRC, 
			ethDst = ETH_DST,
			ip4Src = IP_SRC,
			ip4Dst = IP_DST,
			udpSrc = PORT_SRC,
			udpDst = port,			
		}
	end)
	local txCtr = stats:newManualTxCounter("Port " .. port, "plain")
	local bufs = mem:bufArray()
	local txPkts = 0
	while mg.running() and  txPkts < pktsNum do		
		bufs:allocN(pktSize,1)
		for i, buf in ipairs(bufs) do
			local pkt = buf:getUdpPacket()
			txPkts = txPkts + 1
		end
		local sentCount = queue:send(bufs)
		txCtr:updateWithSize(sentCount, pktSize)	
	end
	txCtr:finalize()
end

function counterSlave(queue, txPackets)
	local bufs = memory.bufArray()
	local ctrs = {}
	local rxPackets = 0
	while mg.running() do
		local rx = queue:tryRecv(bufs,2000000)		
		if rx < 1 then
			break
		end	
		for i = 1, rx do
			local buf = bufs[i]
			local pkt = buf:getUdpPacket()
			rxPackets = rxPackets +1			
			local port = pkt.udp:getDstPort()
			local ctr = ctrs[port]
			if not ctr then
				ctr = stats:newPktRxCounter("Port " .. port, "plain")
				ctrs[port] = ctr
			end
			ctr:countPacket(buf)
		end
		for k, v in pairs(ctrs) do
			v:update()
		end
		bufs:freeAll()
		end
	for k, v in pairs(ctrs) do
		v:finalize()
	end
	print (" Lost Packets = " .. txPackets - rxPackets)
end

```

**Comment by emmericp** [comment]
This works fine on my server. I've tested it with an X710 and an X550, both report 0 packets lost in several test runs.

I'm also on Ubuntu 16.04 with kernel 4.4 and my CPU is even slower than yours: Xeon E3-1235L v5 @ 2.00GHz.

Any particular parameters that cause this to fail for you?

**Comment by davidfernandes1212** [comment]
I have no idea what parameters could cause the fails. First, I thought that maybe some Ubuntu processes could start running automatically on background and cause the losses. But I have currently a light Ubuntu Server version and I give highest priority to MoonGen processes. So I don't think that is the problem. 

How many tests did you perform ? Because I only observe losses sometimes. Some examples of tests that I performed : 

> - Packets length = 58 bytes ; rate = 800 Mbps ; 1 test of 16 hours transmitting --> 9 lost packets 
> - Packets length = 58 bytes ; rate = 800 Mbps ; 200 tests of 10s --> 3 failed tests (2359, 1 and 20.000.000 lost packets respectively) 

> - Packets length = 124 bytes ; rate = 3000 Mbps ; 200 tests of 10s --> 2 failed tests (1 and 17552 lost packets respectively) 

> - Packets length = 1514 bytes ; rate = 5000 Mbps ; 1 test of 14 hours transmitting --> 1 lost packets 
> - Packets length = 1514 bytes ; rate = 5000 Mbps ; 325 tests of 10s transmitting --> 3 failed tests (1, 3 and 5.000.000 lost packets respectively)

I observed that sometimes rate control becomes unstable just when losses appear. I don't know if it could be a cause or a consequence of the packet losses.

Thanks for helping.

**Comment by emmericp** [comment]
If it's that rare, then it's probably a scheduling problem with Linux.

Intel typically recommends the isolcpus Kernel Parameter to avoid problems like this.
Might be somewhat problematic with your 2 core CPU, though.

Try pinning the tx thread on the HT-paires core with Linux.

Or better: use a CPU with more than two cores

**Comment by davidfernandes1212** [comment]
Hi Paul !

Thanks for your answers.

I followed your advice and I tested MoonGen with a more Cores integrated machine. More precisely, I tested it with a Dell FC430 (CPUs: Intel Xeon E5-2660 v3 @ 2.6GHz with 10 Cores and 2 Threads/Core) with Hyper-threading disabled. I tried as well isolating cores for MoonGen’s use with isolcpus and losses still present.

The results are the same and even worse than with the other machine. The number of failed tests (tests with at least 1 lost packet) seems to be higher.

Moreover, with this machine, I can’t achieve more than 6Gbps. Even if I put Rate Control parameter at 10 Gbps, the rate doesn’t exceed 6 Gbps.

I have no idea about what could cause that strange behavior.

**Comment by davidfernandes1212** [comment]
Could it be linked to the NIC counters or the way that I access to them? Is there any other way to access to the NIC counters? 

Thanks in advance

**Comment by emmericp** [comment]
I ran the test you sent me via email over night twice.
Not a single packet was dropped in both test runs.

Hardware:
X550 NIC, Xeon E3-1235L v5 4x 2 GHz, no HT, Ubuntu 16.04

I've also never seen such a packet drop (at low rates) in any of my tests.

Did you try to use a different NIC? Is this bug specific to MoonGen? Is it specific to the hardware rate control feature?


I'm afraid I can't help you and I'll close this as it's not reproducible.
