### ISSUE TITLE
Cannot compile moongen from github on Centos 7

### ISSUE THREAD

**Issue by ns-sundar** [emmericp/MoonGen#169]
Centos 7.3.1611 (kernel 3.10.0-514.el7.x86_64), moongen cloned from github today. Hitting the following errors in running build.sh:
---  
/root/MoonGen/libmoon/deps/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2335:2: error: initialization from incompatible pointer type [-Werror]
  .ndo_fdb_add  = igb_ndo_fdb_add,
  ^
/root/MoonGen/libmoon/deps/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2335:2: error: (near initialization for ‘igb_netdev_ops.<anonymous>.ndo_fdb_add’) [-Werror]
/root/MoonGen/libmoon/deps/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2342:2: error: initialization from incompatible pointer type [-Werror]
  .ndo_bridge_setlink = igb_ndo_bridge_setlink,
 
. . . 

Building C object libmoon/CMakeFiles/moon.dir/src/memory.c.o
/root/MoonGen/libmoon/src/device.c:2:25: fatal error: rte_ethdev.h: No such file or directory
 #include <rte_ethdev.h>
                         ^
compilation terminated.
/root/MoonGen/libmoon/src/memory.c:2:22: fatal error: rte_mbuf.h: No such file or directory
 #include <rte_mbuf.h>
--- 
The include files rte_ethdev.h and rte_mbuf.h are in fact present in dpdk/lib under librte_ether and librte_mbuf resp. 

Since both moongen and Centos 7 are stock versions, one world think they will work together out of the box. I tried a few hacks, but would appreciate an authoritative answer.

Thanks,
Sundar

**Comment by emmericp** [comment]
centos kernels often have quite a few backports and custom patches, not too surprised that it doesn't work.

you can try to disable the KNI mod, it's not used by any of the default examples anyways. just edit the DPDK config as you would normally and recompile.

```
CONFIG_RTE_KNI_KMOD=n
```
