### ISSUE TITLE
Intel x710 10Gbit/s rx/tx stats not correct

### ISSUE THREAD

**Issue by hopoaat** [emmericp/MoonGen#170]
Hi!

With latest commit id (ef3aa3f747be1860db36ae8bae7e24ddf4eb07b9) I've observed that, the 10 Gbit/s Intel X710 NIC counts the tx/rx packet incorrectly.
I've created a basic script that compares the hw, sw method for the NIC, like your compare-rate-control-mechanisms.lua script, and this also contains a comparison between the dpdk, and moongen handling.

The script:
[compare.txt](https://github.com/emmericp/MoonGen/files/916992/compare.txt)
[output.txt](https://github.com/emmericp/MoonGen/files/916971/output.txt)
Are you aware of this problem?
With older commit id: 8b427b9b44595d0a7e0d12f5399ef74e4af57188 the NIC's counters seem to work properly. However in that version I used hw rate control, and got a warning message, but could achive ~0 ppm loss.

Br,

Peter

**Comment by emmericp** [comment]
Looks like it's either not counting CRC bytes on transmit or counting it twice on rx, leading to different reported bit rates.

Further, there is a known problem with the hardware stats on the XL710 chip; resetting them doesn't work properly (either the hardware is buggy or the datasheet is wrong). 
So what we are trying to do here is keeping the initial stats and subtracting them from further measurements; this also seems to be failing as the total number of packets seems to accumulate over the test runs.
The older commit probably uses my own implementation of the counter tracking while the new one might be using DPDK.


I'll have a look at this.

**Comment by hopoaat** [comment]
Hi!

I've tried with commit id: 8b427b9b44595d0a7e0d12f5399ef74e4af57188.
Looks like the rate control is a little bit buggy both hw, and sw, but the stats seems to be OK.
I've used two X710 NICs. Loopback was used on eXtreme Switch.
At the end I've got +5 extra packet. I think it's the eXtreme Switch that sends some packets time to time on NICs.

The script:
[compare.txt](https://github.com/emmericp/MoonGen/files/923632/compare.txt)
The output:
[output.txt](https://github.com/emmericp/MoonGen/files/923633/output.txt)
Maybe it's help you a little bit.

Br,

Peter

**Comment by emmericp** [comment]
This script works fine for me, there's just a minor bug: hardware rate control and software control cannot be used at the same time, i.e., you either have to run the software test first or add

`txQueue:setRate(0)` 

in the software case.

The stats also show up fine for me with the latest version, set to 5.5 Mpps:

software:
```
[Device: id=4] TX: 5.51 (StdDev 0.00) Mpps, 2996 (StdDev 0) Mbit/s (3877 Mbit/s with framing), total 55104966 packets with 3747137688 bytes (incl. CRC)
[Device: id=5] RX: 5.51 (StdDev 0.00) Mpps, 2996 (StdDev 0) Mbit/s (3877 Mbit/s with framing), total 55104966 packets with 3747137688 bytes (incl. CRC)
[INFO]  Packet loss: 0 (0.000000%)
```

hardware:
```
[Device: id=4] TX: 5.60 (StdDev 0.00) Mpps, 3046 (StdDev 0) Mbit/s (3942 Mbit/s with framing), total 27844866 packets with 1893450888 bytes (incl. CRC)
[Device: id=5] RX: 5.60 (StdDev 0.00) Mpps, 3046 (StdDev 0) Mbit/s (3942 Mbit/s with framing), total 27844866 packets with 1893450888 bytes (incl. CRC)
[INFO]  Packet loss: 0 (0.000000%)
```

the hardware rate limiter is unfortunately somewhat off at higher rates on the X710 chip, but there is nothing that we can do about that :(


I've noticed that your NICs have a relatively old firmware: 
`FW 4.22 API 1.2 NVM 04.02.05 eetrack 8000143f`

Mine came with `FW 5.0 API 1.5 NVM 05.00.04 eetrack 800024c6`, maybe this is the source of the problem?

**Comment by hopoaat** [comment]
Hi!

Thanks for your suggestions. Worked fine!
1. Upgraded the firmware to:
`FW 5.0 API 1.5 NVM 05.00.05 eetrack 80002892`
2. and modified the script based on your comment:
[compare.txt](https://github.com/emmericp/MoonGen/files/946889/compare.txt)
After 10 mins measurements I've get these stats with latest MoonGen commit:

Software
```
[Device: id=1] TX: 9.98 (StdDev 0.26) Mpps, 5428 (StdDev 139) Mbit/s (7025 Mbit/s with framing), total 12102792030 packets with 822989858040 bytes (incl. CRC)
[Device: id=0] RX: 9.98 (StdDev 0.26) Mpps, 5109 (StdDev 131) Mbit/s (6705 Mbit/s with framing), total 12102792053 packets with 774578697138 bytes (incl. CRC)
[INFO]  Packet loss: -23 (-0.000000%)
```
Hardware
```
[Device: id=1] TX: 10.20 (StdDev 0.00) Mpps, 5548 (StdDev 0) Mbit/s (7180 Mbit/s with framing), total 6117696585 packets with 416003367780 bytes (incl. CRC)
[Device: id=0] RX: 10.20 (StdDev 0.00) Mpps, 5222 (StdDev 0) Mbit/s (6854 Mbit/s with framing), total 6117696598 packets with 391532585278 bytes (incl. CRC)
[INFO]  Packet loss: -13 (-0.000000%)
```
Packet loss negative number because of eXtreme Switch, that sends some packets timetotime.
Thanks for your help!

Br,

Peter
