### ISSUE TITLE
Error MoonGen

### ISSUE THREAD

**Issue by imehrdad2012** [emmericp/MoonGen#171]
Hello,

I am new to the MoonGen library. When I run any of the examples, I get the following error. Can you please guide me how to solve the issue? 
 sudo ./build/MoonGen examples/l2-bursts.lua 0 1
Error: "/home/vagrant/MoonGen/build/../libmoon/lua/device.lua:197: Could not configure device 0: error Invalid argument"

vagrant@vagrant:~/MoonGen$ sudo ./build/MoonGen examples/l2-bursts.lua 0 1
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 2 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100e rte_em_pmd
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e rte_em_pmd
[INFO]  Found 1 usable devices:
   Device 0: 08:00:27:15:B4:11 (Intel Corporation 82540EM Gigabit Ethernet Controller)
[WARN]  device.config() without named arguments is deprecated and will be removed. See documentation for libmoons device.config().
PMD: eth_em_rx_queue_setup(): drop_en functionality not supported by device
could not configure rx queue 0
[FATAL] Lua error in task master
/home/vagrant/MoonGen/build/../libmoon/lua/device.lua:197: Could not configure device 0: error Invalid argument
Stack Traceback
===============
(2) Lua method 'fatal' at file '/home/vagrant/MoonGen/build/../libmoon/lua/log.lua:129'
	Local variables:
	 self = table: 0x40e3af98  {DEBUG:0, fatal:function: 0x40bceec8, writeToLog:function: 0x40bceea8, INFO:1 (more...)}
	 str = string: "Could not configure device 0: error Invalid argument"
(3) Lua field 'config' at file '/home/vagrant/MoonGen/build/../libmoon/lua/device.lua:197'
	Local variables:
	 args = table: 0x40666808  {1:0, rxQueues:1, stripVlan:true, speed:0, mempools:table: 0x40bc70d8, dropEnable:true (more...)}
	 driverInfo = table: 0x40673b80  {}
	 rc = number: -22
(4) Lua function 'master' at file 'examples/l2-bursts.lua:10' (best guess)
	Local variables:
	 txPort = number: 0
(5) global C function 'xpcall'
(6) Lua upvalue 'master' at file '/home/vagrant/MoonGen/build/../libmoon/lua/main.lua:96'
	Local variables:
	 _ = string: "./build/MoonGen"
	 file = string: "examples/l2-bursts.lua"
	 args = table: 0x4016a0c0  {1:0, 2:1}
	 cfgFile = nil
	 ok = boolean: true
	 parsedArgs = table: 0x4196a518  {}
(7) Lua function 'main' at file '/home/vagrant/MoonGen/build/../libmoon/lua/main.lua:143' (best guess)
	Local variables:
	 task = string: "master"
	/home/vagrant/MoonGen/build/../libmoon/lua/device.lua:197: Could not configure device 0: error Invalid argument

**Comment by emmericp** [comment]
The emulated NIC that you are using isn't very well supported (it's > 10 years old).

Please use virtio or vmxnet NICs in VMs, they are generally better supported. But some stuff will still require real hardware.

**Comment by shashankbr11** [comment]
The usage of this command shown below is geiving me errors

sudo ./moongen-simple start "load-latency:0,1:rate=1000"

[ERROR] Invalid device number "0" for flow "load-latency"
[ERROR] Invalid device number "1" for flow "load-latency"
[ERROR] Invalid device number "rate=1000" for flow "load-latency"
[ERROR] Need to pass at least one tx or rx device
[ERROR] No valid flows remaining

Could you please guide me on the correct usage of the command?
I wish to send traffic to multicores by repeating the 0,1 as mentioned in the git page.
On lspci on my PC, I have found the device ID to be 02:00.0 and 02:00.1 for Intel 82599ES adapter and that is the one that I have bound by running the bind-interfaces.sh file.
Can you please guide on the correct usage of this id or should I have to specify the interface names?
What should be the syntax to specify a tx or rx device?
