### ISSUE TITLE
MoonGen segfault when trying to get pcap packets

### ISSUE THREAD

**Issue by adolia** [emmericp/MoonGen#173]
Hi to all.
I have a problem, when trying to extract packets from pcap:
Apr 28 12:07:34 localhost libmoon[17825]: EAL: PCI device 0000:00:19.0 on NUMA socket -1
Apr 28 12:07:34 localhost libmoon[17825]: EAL:   probe driver: 8086:153b rte_em_pmd
Apr 28 12:07:34 localhost libmoon[17825]: EAL: PCI device 0000:01:00.0 on NUMA socket -1
Apr 28 12:07:34 localhost libmoon[17825]: EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
Apr 28 12:07:34 localhost libmoon[17825]: EAL: PCI device 0000:03:00.0 on NUMA socket -1
Apr 28 12:07:34 localhost libmoon[17825]: EAL:   probe driver: 8086:1533 rte_igb_pmd
Apr 28 12:07:36 localhost kernel: lcore-slave-1[17827]: segfault at 0 ip 00007f7861c60f10 sp 00007f775bffea48 error 4 in libc-2.17.so[7f7861b16000+1b7000]

**Comment by emmericp** [comment]
what exactly are you trying to do?

can you sho your code?

**Comment by adolia** [comment]
I'm only trying to change pcap packets using replay-pcap.lua
`for i, buf in ipairs(bufs) do
	local pkt = buf:getUdpPacket()
	pkt.udp.src = math.random(0, 2^16 - 1)
	pkt.udp.dst = math.random(0, 2^16 - 1)
end
queue:sendN(bufs, n)`

**Comment by emmericp** [comment]
the buf array might not be filled completely at the end of the pcap file, so ipairs() is incorrect.

use
```
for i = 1, n do
   local buf = bufs[i]
   ...
end
```

i think this might be fixable by re-sizing the array according if necessary in libmoon

**Comment by adolia** [comment]
Thanks a lot.
