### ISSUE TITLE
Unable to bind MoonGen processes to a single core

### ISSUE THREAD

**Issue by safiyat** [emmericp/MoonGen#176]
Hi,

I was experimenting with MoonGen and thought of running all the MoonGen tasks on the same lcore.

I tried using `cores` in the dpdk-config.lua file to run the master task on a core of my choice, but then running the slave task to the same core (using `startTaskOnCore`) resulted in the sender being blocked (not sending any packets).

I then tried using `startSharedTask` along with the configuration settings to run the master task as well as the slave task on the same lcore (lcore 2) but the output of `ps` and `taskset` looked puzzling.

Output of `ps aux | grep MoonGen`:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     12392  108  0.4 1221872 17052 pts/0   Sl+  08:03   0:02 ./build/MoonGen /home/ubuntu/mg_sender_core.shared.lua --dpdk-config=/home/ubuntu/dpdk-conf.lua 0
```

Output of `ps -mo pid,tid,fname,user,psr -p $moongen_pid`:
```
  PID   TID COMMAND  USER     PSR
12392     - MoonGen  root       -
    - 12392 -        root       2
    - 12409 -        root       2
    - 12410 -        root       0
    - 12411 -        root       0
    - 12412 -        root       0
    - 12413 -        root       0
    - 12414 -        root       0
    - 12415 -        root       0
    - 12416 -        root       0
    - 12417 -        root       0
```

Output of `taskset -a -c -p $moongen_pid`:
```
pid 12392's current affinity list: 2
pid 12409's current affinity list: 2
pid 12410's current affinity list: 0
pid 12411's current affinity list: 0
pid 12412's current affinity list: 0
pid 12413's current affinity list: 0
pid 12414's current affinity list: 0
pid 12415's current affinity list: 0
pid 12416's current affinity list: 0
pid 12417's current affinity list: 0
```

The question is, what are the eight other tasks, and how do I run them on the lcore of my choice? Can it be done?

**Comment by emmericp** [comment]
sorry about that, there is a bug with shared tasks when the master core is not mapped to lcore 0: https://github.com/libmoon/libmoon/issues/22

the 8 other threads are reserved for the shared tasks and should be pinned to the lcore, the problem here is that the dpdk commandline is created incorrectly here: https://github.com/libmoon/libmoon/blob/master/lua/dpdk.lua#L163-L165

i'll see what i can do about that later this week

**Comment by emmericp** [comment]
changing the hardcoded "@0" in dpdk.lua to `cfg.cores[1]` might fix this, but I unfortunately can't test it at the moment because someone took down our test servers :(

**Comment by safiyat** [comment]
That helped. Thanks!

I tried the change you suggested. Here is the git-diff:

```patch
diff --git a/lua/dpdk.lua b/lua/dpdk.lua
index 962bf3b..f4f4bd1 100644
--- a/lua/dpdk.lua
+++ b/lua/dpdk.lua
@@ -161,8 +161,9 @@ function mod.init()
        argv[#argv + 1] = ("-c0x%08X%08X"):format(coreMaskUpper, coreMaskLower)
        -- core mapping, shared cores use the highest IDs
        local maxCore = cfg.cores[#cfg.cores]
-       local coreMapping = ("%d-%d,(%d-%d)@0"):format(cfg.cores[1], maxCore, maxCore + 1, maxCore + libmoon.config.numSharedCores)
+       local coreMapping = ("%d-%d,(%d-%d)@%d"):format(cfg.cores[1], maxCore, maxCore + 1, maxCore + libmoon.config.numSharedCores, cfg.cores[1])
        argv[#argv + 1] = ("--lcores=%s"):format(coreMapping)
+       log:info(("--lcores=%s"):format(coreMapping))

        if cfg.pciBlacklist then
                if type(cfg.pciBlacklist) == "table" then
```

The additional output concerning the `--lcores` argument that used to be `[INFO]  --lcores=1-1,(2-9)@0` is now `[INFO]  --lcores=1-1,(2-9)@1`. Thanks!
