### ISSUE TITLE
Problem running MoonGen examples

### ISSUE THREAD

**Issue by ztz1989** [emmericp/MoonGen#177]
Dear emmericp, I am new to MoonGen and today I tried to run the "quality-of-service-test.lua " example of MoonGen, but I faced an issue here. I installed MoonGen on an virtualbox VM, whose parameters are:
$ uname -a
Linux mininet-vm 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I configured 4 network interfaces with the following configuration:
$ lspci | grep net
00:03.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
00:08.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
00:09.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
00:0a.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)

I started the VM with 4 cores. 
Then run the example as follows:
$ sudo ./build/MoonGen examples/quality-of-service-test.lua 0 0 1000 1000
**The output:**   
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7effb6a00000 (size = 0x400000)
EAL: Ask a virtual area of 0x33800000 bytes
EAL: Virtual area found at 0x7eff77400000 (size = 0x33800000)
EAL: Ask a virtual area of 0xbc00000 bytes
EAL: Virtual area found at 0x7eff6b600000 (size = 0xbc00000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7effb6600000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7effb6200000 (size = 0x200000)
EAL: Ask a virtual area of 0x3fa00000 bytes
EAL: Virtual area found at 0x7eff2ba00000 (size = 0x3fa00000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7effb5c00000 (size = 0x400000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7effb5800000 (size = 0x200000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7effb5200000 (size = 0x400000)
EAL: Requesting 1024 pages of size 2MB from socket 0
EAL: TSC frequency is ~2693762 KHz
EAL: Master lcore 0 is ready (tid=b9e71980;cpuset=[0])
EAL: lcore 3 is ready (tid=b49fe700;cpuset=[3])
EAL: lcore 2 is ready (tid=b51ff700;cpuset=[2])
EAL: lcore 1 is ready (tid=b77bc700;cpuset=[1])
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100e rte_em_pmd
EAL:   Not managed by a supported kernel driver, skipped
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e rte_em_pmd
EAL:   Not managed by a supported kernel driver, skipped
EAL: PCI device 0000:00:09.0 on NUMA socket -1
EAL:   probe driver: 8086:100e rte_em_pmd
EAL:   Not managed by a supported kernel driver, skipped
EAL: PCI device 0000:00:0a.0 on NUMA socket -1
EAL:   probe driver: 8086:100e rte_em_pmd
EAL:   PCI memory mapped at 0x7effb6e00000
PMD: eth_em_dev_init(): port_id 0 vendorID=0x8086 deviceID=0x100e
[INFO]  Found 1 usable devices:
   Device 0: 08:00:27:28:B7:06 (unknown NIC (PCI ID 8086:100e))
[WARN]  You are running Linux >= 3.14, DDIO might not be working with DPDK in this setup!
[WARN]  This can cause a huge performance impact (one memory access per packet!) preventing MoonGen from reaching line rate.
[WARN]  Try using an older kernel (we recommend 3.13) if you see a low performance or huge cache miss ratio.
[FATAL] Lua error in task master
lua/include/device.lua:191: Could not configure device 0: error -22
**Stack Traceback**
===============
(2) Lua method 'fatal' at file 'lua/include/log.lua:129'
	Local variables:
	 self = table: 0x418af870  {DEBUG:0, fatal:function: 0x418a9138, writeToLog:function: 0x418a1280, INFO:1 (more...)}
	 str = string: "Could not configure device 0: error -22"
(3) Lua field 'config' at file 'lua/include/device.lua:191'
	Local variables:
	 args = table: 0x418b3348  {rxQueues:2, rssNQueues:0, speed:0, dropEnable:true, txDescs:256, txQueues:3 (more...)}
	 rss_enabled = number: 0
	 rc = number: -22
(4) Lua function 'master' at file 'examples/quality-of-service-test.lua:36' (best guess)
	Local variables:
	 txPort = number: 0
	 rxPort = number: 0
	 bgRate = number: 1000
	 fgRate = number: 1000
	 txDev = nil
	 rxDev = nil
(5) global C function 'xpcall'
(6) Lua upvalue 'slave' at file 'lua/include/main.lua:89'
	Local variables:
	 _ = string: "./build/MoonGen"
	 file = string: "examples/quality-of-service-test.lua"
	 devices = table: 0x40e27210  {1:table: 0x40e27358}
	 args = table: 0x4029ff78  {1:0, 2:0, 3:1000, 4:1000}
(7) Lua function 'main' at file 'lua/include/main.lua:125' (best guess)
	Local variables:
	 task = string: "master"
	lua/include/device.lua:191: Could not configure device 0: error -22

I really have no clue about this issue. Maybe this is a very stupid question. Could you give me some hints about it? Thanks in advance!

  Best regards
  ztz

**Comment by emmericp** [comment]
the qos test relies on hardware features (filters) that aren't supported by emulated NICs.

further, the NIC you are emulating is only very poorly supported by DPDK. I recommend virtio which is well supported in DPDK. However, the virtio support in virtualbox is sometimes quite poor (e.g., multi queues aren't supported). So the best approach is to not use virtualbox.

**Comment by ztz1989** [comment]
Hi, Emmericp. Thank you very much for the information!
