### ISSUE TITLE
Problem with l2-poisson-load-latency example 

### ISSUE THREAD

**Issue by ztz1989** [emmericp/MoonGen#178]
Dear author, I just wanted to try the l2-poisson-load-latency example and find an issue here:

**$ sudo ./build/MoonGen examples/l2-poisson-load-latency.lua 2 3**
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 40 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: PCI device 0000:04:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: PCI device 0000:05:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
[INFO]  Found 4 usable devices:
   Device 0: 5C:B9:01:88:EA:60 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
   Device 1: 5C:B9:01:88:EA:61 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
   Device 2: 00:11:0A:6B:D8:88 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
   Device 3: 00:11:0A:6B:D8:89 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
[INFO]  Waiting for devices to come up...
[INFO]  Device 2 (00:11:0A:6B:D8:88) is up: 10000 MBit/s
[INFO]  Device 3 (00:11:0A:6B:D8:89) is up: 10000 MBit/s
[INFO]  2 devices are up.
[FATAL] Lua error in task loadSlave
examples/l2-poisson-load-latency.lua:35: attempt to index upvalue 'filter' (a boolean value)
Stack Traceback
===============
(2) global C function 'xpcall'
(3) Lua upvalue 'slave' at file '/home/tzhang/MoonGen/build/../libmoon/lua/main.lua:125'
	Local variables:
	 args = table: 0x40815f88  {1:1, 2:loadSlave, 3:[Device: id=2], 4:[Device: id=3], 5:[TxQueue: id=2, qid=0] (more...)}
	 ok = boolean: true
	 taskId = number: 1
	 func = string: "loadSlave"
	 (*temporary) = table: 0x40818fb0  {}
	 (*temporary) = C function: select
	 (*temporary) = number: 2
(4) Lua function 'main' at file '/home/tzhang/MoonGen/build/../libmoon/lua/main.lua:145' (best guess)
	Local variables:
	 task = string: "slave"
	examples/l2-poisson-load-latency.lua:35: attempt to index upvalue 'filter' (a boolean value)

From this point on, the program stays here without proceeding. Could you give me some hints about it? Thanks!

**Comment by emmericp** [comment]
sorry, that exampled used a deprecated and removed API, I've fixed it in #925e15c
