### ISSUE TITLE
l2-load-latency fails to approach 10Gbit/s

### ISSUE THREAD

**Issue by ztz1989** [emmericp/MoonGen#179]
Dear Paul, today I was trying the l2-load-latency example. But I observed that it couldn't reach the 10Gbit/s speed on my machine (as shown in the output part below) using port 2 and 3. I tried this example on another machine on the same links and it worked by reaching 10G speed. I cannot figure it out why it was so slow since the two machines are inter-connected by two cables. Some information about the machine:
$ uname -a
Linux freisa 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$  dpdk-devbind.py -s
Network devices using DPDK-compatible driver
============================================
0000:04:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe
0000:04:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe
0000:05:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe
0000:05:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe

Network devices using kernel driver
===================================
0000:02:00.0 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth0 drv=tg3 unused=igb_uio *Active*
0000:02:00.1 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth1 drv=tg3 unused=igb_uio 
0000:02:00.2 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth2 drv=tg3 unused=igb_uio 
0000:02:00.3 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth3 drv=tg3 unused=igb_uio 

Other network devices
=====================
<none>

Command:
$ sudo ./build/MoonGen examples/l2-load-latency.lua 2 3

Output:
[sudo] password for tzhang: 
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 40 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: PCI device 0000:04:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: PCI device 0000:05:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
[INFO]  Found 4 usable devices:
   Device 0: 5C:B9:01:88:EA:60 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
   Device 1: 5C:B9:01:88:EA:61 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
   Device 2: 00:11:0A:6B:D8:88 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
   Device 3: 00:11:0A:6B:D8:89 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
file histogram.csv
dev1 2
dev2 3
rate 10000
[INFO]  Waiting for devices to come up...
[INFO]  Device 2 (00:11:0A:6B:D8:88) is up: 10000 MBit/s
[INFO]  Device 3 (00:11:0A:6B:D8:89) is up: 10000 MBit/s
[INFO]  2 devices are up.
[Device: id=2] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=3] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=2] TX: 4.60 Mpps, 2357 Mbit/s (3093 Mbit/s with framing)
[Device: id=3] TX: 4.67 Mpps, 2390 Mbit/s (3137 Mbit/s with framing)
[Device: id=2] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=3] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=2] TX: 4.27 Mpps, 2186 Mbit/s (2869 Mbit/s with framing)
[Device: id=3] TX: 4.27 Mpps, 2188 Mbit/s (2871 Mbit/s with framing)
[Device: id=2] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=3] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=2] TX: 4.37 Mpps, 2235 Mbit/s (2934 Mbit/s with framing)
[Device: id=3] TX: 4.37 Mpps, 2237 Mbit/s (2936 Mbit/s with framing)
....

So could you give me some hints about this? Thanks in advacne!

**Comment by emmericp** [comment]
* does it work on link 0 and 1?
* does it work if you directly connect ports 2 and 3 without a separate host
* does it work when using a different script (e.g., l3-load-latency.lua?)
* what hardware are you using? is this a NUMA system?

**Comment by ztz1989** [comment]
Hi, it doesn't work on 0, 1 either, but with l3-load-latency it works fine at 10G speed. I think my system is NUMA:
$ dmesg | grep numa
[    0.000000] mempolicy: Enabling automatic NUMA balancing. Configure with numa_balancing= or the kernel.numa_balancing sysctl

$ sudo find /proc -name numa_maps
/proc/1/task/1/numa_maps
/proc/1/numa_maps
/proc/2/task/2/numa_maps
/proc/2/numa_maps
/proc/3/task/3/numa_maps
/proc/3/numa_maps
/proc/5/task/5/numa_maps
/proc/5/numa_maps
/proc/8/task/8/numa_maps
/proc/8/numa_maps
/proc/9/task/9/numa_maps
/proc/9/numa_maps
/proc/10/task/10/numa_maps
/proc/10/numa_maps
/proc/11/task/11/numa_maps
/proc/11/numa_maps
/proc/12/task/12/numa_maps
/proc/12/numa_maps
/proc/13/task/13/numa_maps
/proc/13/numa_maps
....

$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
Stepping:              2
CPU MHz:               1200.000
CPU max MHz:           2600,0000
CPU min MHz:           1200,0000
BogoMIPS:              5195.57
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts

Currently I cannot reconnect the ports because I have no access to the machines in the lab. Is it a problem the underlying hardware? Thanks for your time.

**Comment by emmericp** [comment]
NUMA setup should be fine because your nics are on node 0 (and if it wasn't, there would be warning about that and the l3 also wouldn't work).

I suspect something weird going on with the receiving host on the other end (maybe pause frames?).
A loopback connection or connection between the two ports would be the only thing to really test that.

Otherwise, do you really need these weird L2 frames instead of L3 frames for the load packets?

**Comment by ztz1989** [comment]
Hi, Paul. Thanks again for your reply. I will try to test it with a connection between the two ports maybe next week. Currently I will stick to L3.

**Comment by sublinhado** [comment]
Maybe the problem be related to the fact that you are using the driver for 1G NICs (igb_uio). Could you try the ixgbe_uio driver?

**Comment by ztz1989** [comment]
Hi, I am not familiar with DPDK, sorry if I ask a stupid question. When I tried to bind device 2 and 3 to ixgbe, they became the devices using kernel driver.
Some outputs:

Originally:
$sudo ./dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:04:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe
0000:04:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe
0000:05:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe
0000:05:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe

Network devices using kernel driver
===================================
0000:02:00.0 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth0 drv=tg3 unused=igb_uio *Active*
0000:02:00.1 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth1 drv=tg3 unused=igb_uio 
0000:02:00.2 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth2 drv=tg3 unused=igb_uio 
0000:02:00.3 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth3 drv=tg3 unused=igb_uio 

Other network devices
=====================
<none>

Then 
$ sudo ./dpdk-devbind.py -b ixgbe 0000:05:00.1
$ sudo ./dpdk-devbind.py -b ixgbe 0000:05:00.0
$ sudo ./dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:04:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe
0000:04:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe

Network devices using kernel driver
===================================
0000:02:00.0 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth0 drv=tg3 unused=igb_uio *Active*
0000:02:00.1 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth1 drv=tg3 unused=igb_uio 
0000:02:00.2 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth2 drv=tg3 unused=igb_uio 
0000:02:00.3 'NetXtreme BCM5719 Gigabit Ethernet PCIe' if=eth3 drv=tg3 unused=igb_uio 
0000:05:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' if=eth8 drv=ixgbe unused=igb_uio 
0000:05:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' if=ens1f1 drv=ixgbe unused=igb_uio 

Other network devices
=====================
<none>

I cannot find a driver named ixgbe_uio, could you give me some hints?

**Comment by emmericp** [comment]
no, the igb_uio driver is correct.
