### ISSUE TITLE
0 Mbps rx rate when running l3-load-latency.lua

### ISSUE THREAD

**Issue by jmhelt** [emmericp/MoonGen#182]
I have a two node setup, a driver with MoonGen (latest master) installed and a router node running OVS. Each node has an Intel X520 10Gbps dual port NIC, and I'm trying to get a basic setup with MoonGen working. However, after running the installation steps without error, I am seeing a zero rx rate. Output from a run is below.
```
$ sudo ./build/MoonGen ./examples/l3-load-latency.lua 1 2
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 32 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:01:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: PCI device 0000:06:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
[INFO]  Found 3 usable devices:
   Device 0: FC:5B:39:AA:5A:A5 (Intel Corporation I350 Gigabit Network Connection)
   Device 1: 90:E2:BA:24:CF:F4 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
   Device 2: 90:E2:BA:24:CF:F5 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
[INFO]  Waiting for devices to come up...
[INFO]  Device 2 (90:E2:BA:24:CF:F5) is up: 10000 MBit/s
[INFO]  Device 1 (90:E2:BA:24:CF:F4) is up: 10000 MBit/s
[INFO]  2 devices are up.
[INFO]  Performing ARP lookup on 10.1.0.10
[INFO]  Performing ARP lookup on 10.1.0.10
[INFO]  Destination mac: 90:e2:ba:24:cf:f5
[INFO]  Destination mac: 90:e2:ba:24:cf:f5
[WARN]  Packet size 60 is smaller than minimum timestamp size 84. Timestamped packets will be larger than load packets.
[Device: id=1] TX: 14.79 Mpps, 7573 Mbit/s (9940 Mbit/s with framing)
[Device: id=2] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=1] TX: 14.88 Mpps, 7619 Mbit/s (10000 Mbit/s with framing)
[Device: id=2] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
...
``` 

What's strange is that when I tried running tcpdump on the router interfaces, I see the arp requests (both initial and refresh) but I don't see any of the traffic that MoonGen is reporting as transmitted.

Any ideas on what's going on or how to debug?  I'm suspicious of the line "PMD: bnxt_rte_pmd_init() called for (null)," but I'm not sure what to make of it.

Not sure if it matters but both nodes are running Ubuntu 16.04.1 with kernel version 4.4.0-75-generic.

**Comment by emmericp** [comment]
Can you try to directly connect the two ports and try to reproduce this to confirm that this is not a problem of your device under test?

**Comment by jmhelt** [comment]
Unfortunately, I don't have physical access to these nodes. Although I've run other networking tests with things like iperf3 without any issue.

**Comment by emmericp** [comment]
The TX counter is derived from hardware counters from the NIC, it's very unlikely that the packets don't get sent out, especially because the ARP packets seem to work.

**Comment by jmhelt** [comment]
Ok, let me try a different machine as a sanity check.

**Comment by jmhelt** [comment]
I tried setting up the same topology from scratch with two different nodes and got the same result. I'm fairly sure the packets are never making it on the wire. See the statistics below from the NICs of the DUT before and after running the test for about 10 seconds.

Before:
```
$ sudo ethtool -S enp6s0f0 | grep rx_packets
     rx_packets: 35
$ sudo ethtool -S enp6s0f1 | grep rx_packets
     rx_packets: 8128062
```
After:
```
$ sudo ethtool -S enp6s0f0 | grep rx_packets
     rx_packets: 38
$ sudo ethtool -S enp6s0f1 | grep rx_packets
     rx_packets: 8128065
```

**Comment by jmhelt** [comment]
Seems to be something specific to this test as I can see packets being transmitted to the DUT when running: `sudo ./build/MoonGen examples/benchmark/udp-throughput.lua 1 2`

**Comment by emmericp** [comment]
There are only a few differences between these two scripts:

* udp checksums vs. only IP checksums
* 3 queues vs. 1 queue
* ARP vs hardcoded mac

Can you please try to:

* change line 99 `bufs:offloadUdpChecksums()` in the load-latency example to to `bufs:offloadIPChecksums()`
* run the udp-throughput example with 3 tx queues: `(...)udp-throughput.lua 1:3 2`
* disable ARP by overriding the MAC in line 13 (unlikely to be the cause since ARP seems to work)

**Comment by jmhelt** [comment]
Sorry for the delay. I finally got a chance to try the suggestions above. Changing the checksums and disabling ARP did not seem to have any effect. I was able to see traffic flowing using the `udp-throughput.lua` script with 3 tx queues.

**Comment by jmhelt** [comment]
Interestingly `sudo ./build/MoonGen examples/benchmark/packet-sizes-rx.lua 1 2` works just fine, although prints a bunch of deprecation warnings. I'll probably just work off of this script for now since it is more or less what I need.
