### ISSUE TITLE
l3-tcp-syn-flood.lua has the wrong seq num

### ISSUE THREAD

**Issue by crackerben** [emmericp/MoonGen#183]
The packert's seq num it send like 123456789:123456795,but the right way is 123456789

**Comment by emmericp** [comment]
can you please elaborate on this?

**Comment by crackerben** [comment]
tcpdump -n -i eth1 port 1024
11:53:53.512601 IP 123.58.168.62.37234 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512601 IP 123.58.168.87.36084 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512605 IP 123.58.168.63.34074 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512607 IP 123.58.168.102.27006 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512607 IP 123.58.168.75.44200 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512607 IP 123.58.168.94.65095 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512607 IP 123.58.168.89.19632 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512607 IP 123.58.168.119.44777 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512609 IP 123.58.168.66.18561 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512610 IP 123.58.168.79.28796 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512610 IP 123.58.168.118.52402 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512608 IP 123.58.168.105.2673 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512609 IP 123.58.168.82.11447 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512609 IP 123.58.168.69.584 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6
11:53:53.512611 IP 123.58.168.88.10276 > 123.58.168.58.1024: Flags [S], seq 1:7, win 8196, length 6



[root@localhost MoonGen]# cat ./examples/l3-tcp-syn-flood.lua
local mg		= require "moongen"
local memory	= require "memory"
local device	= require "device"
local stats		= require "stats"
local log 		= require "log"

function configure(parser)
	parser:description("Generates TCP SYN flood from varying source IPs, supports both IPv4 and IPv6")
	parser:argument("dev", "Devices to transmit from."):args("*"):convert(tonumber)
	parser:option("-r --rate", "Transmit rate in Mbit/s."):default(10000):convert(tonumber)
	parser:option("-i --ip", "Source IP (IPv4 or IPv6)."):default("10.0.0.1")
	parser:option("-d --destination", "Destination IP (IPv4 or IPv6).")
	parser:option("-f --flows", "Number of different IPs to use."):default(100):convert(tonumber)
end

function master(args)
	for i, dev in ipairs(args.dev) do
		local dev = device.config{port = dev}
		dev:wait()
		dev:getTxQueue(0):setRate(args.rate)
		mg.startTask("loadSlave", dev:getTxQueue(0), args.ip, args.flows, args.destination)
	end
	mg.waitForTasks()
end

function loadSlave(queue, minA, numIPs, dest)
	--- parse and check ip addresses
	local minIP, ipv4 = parseIPAddress(minA)
	if minIP then
		log:info("Detected an %s address.", minIP and "IPv4" or "IPv6")
	else
		log:fatal("Invalid minIP: %s", minA)
	end

	-- min TCP packet size for IPv6 is 74 bytes (+ CRC)
	local packetLen = ipv4 and 60 or 74

	-- continue normally
	local mem = memory.createMemPool(function(buf)
		buf:getTcpPacket(ipv4):fill{
			ethSrc = queue,
			ethDst = "12:34:56:78:90",
			ip4Dst = dest,
			ip6Dst = dest,
			tcpSyn = 1,
                        tcpDst = "1024",
			tcpSeqNumber = 1,
                        --tcpPSH=1,
                        --tcpURG=1,
                        --tcpRST=1,
                        --tcpFIN=1,
                        --tcpFlags=0x0,
                        --tcpSeqNumber=0x1447,
                        --tcpAckNumber=1,
                        --tcpACK=1,
                        --tcpUrgentPointer=0xeffe,
			tcpWindow = 8196,
			pktLength = packetLen
		}
	end)

	local bufs = mem:bufArray(128)
	local counter = 0
	local c = 0

	local txStats = stats:newDevTxCounter(queue, "plain")
	while mg.running() do
		-- fill packets and set their size
		bufs:alloc(packetLen)
		for i, buf in ipairs(bufs) do
			local pkt = buf:getTcpPacket(ipv4)

			--increment IP
			if ipv4 then
				pkt.ip4.src:set(minIP)
				pkt.ip4.src:add(counter)
                                pkt.tcp.src = math.random(0, 2^16 - 1)
                                --pkt.tcp.seq = math.random(100000000,999999999)
			else
				pkt.ip6.src:set(minIP)
				pkt.ip6.src:add(counter)
			end
			counter = incAndWrap(counter, numIPs)

			-- dump first 3 packets
			if c < 3 then
				buf:dump()
				c = c + 1
			end
		end
		--offload checksums to NIC
		bufs:offloadTcpChecksums(ipv4)

		queue:send(bufs)
		txStats:update()
	end
	txStats:finalize()
end


---------------------------------

As you see , the seq num of the packages it sent is same, but I want the seq num like 123456789 with no ':' in it .

**Comment by emmericp** [comment]
Working as intended. This is only an example, if you want custom stuff like varying sequence numbers you have to add it yourself.

You can use `:setSeqNumber(...)` on the tcp header to change it in the transmit loop.
