### ISSUE TITLE
Generate packets between different machines

### ISSUE THREAD

**Issue by dosarudaniel** [emmericp/MoonGen#185]
I didn't find any documentation or example about how to generate packets between two different machines. Can you tell me if there is possible to do that and how should I do it? 
Thank you!

**Comment by emmericp** [comment]
Can you please elaborate on this?

**Comment by dosarudaniel** [comment]
I want to measure OpenFastPath performance using this https://github.com/OpenFastPath/ofp/wiki/OpenFastPath-Performance-Measurement-Procedure
with Moongen traffic generator. For this I need to generate packets from one node to another. 
I my case, one node represents a virtual machine. 
So I need to use a script that generates packets and sends them for Node 1 (with IP A.B.C.X/24) to Node 2 (with IP A.B.C.Y/24) for example. 
I didn't find a script to do this and I don't know if it is possible to do it. If it is how can I do it?

**Comment by emmericp** [comment]
This doesn't sound like a particularly good idea, there is no advantage when using two servers over a single server with two nics. This will create more problems than it solves.

But if you really want to: just run l3-load-latency.lua on both sides and adjust the constants in the code as necessary. But don't expect latency measurements to work, obviously.
