### ISSUE TITLE
module testlog not found

### ISSUE THREAD

**Issue by dosarudaniel** [emmericp/MoonGen#186]
When I try to run this script https://github.com/emmericp/MoonGen/blob/master/test/tests/01-send.lua I get this error: 
daniel@daniel-KVM:~/MoonGen$ sudo ~/MoonGen/build/MoonGen ./test/tests/01-send.lua
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
[FATAL] Lua error in task master
./test/tests/01-send.lua:10: module 'testlog' not found:
	no field package.preload['testlog']
	no file '/home/daniel/MoonGen/build/../libmoon/../lua/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/../lua/testlog/init.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/../lua/lib/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/../lua/lib/testlog/init.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/testlog/init.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/lib/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/lib/turbo/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/lib/testlog/init.lua'
	no file './testlog.lua'
	no file '/usr/local/share/luajit-2.1.0-beta2/testlog.lua'
	no file '/usr/local/share/lua/5.1/testlog.lua'
	no file '/usr/local/share/lua/5.1/testlog/init.lua'
	no file './test/tests/testlog.lua'
	no file './testlog.so'
	no file '/usr/local/lib/lua/5.1/testlog.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
Stack Traceback
(2) main chunk of file './test/tests/01-send.lua' at line 10
(3) upvalue C function 'xpcall'
(4) Lua upvalue 'master' at file '/home/daniel/MoonGen/build/../libmoon/lua/main.lua:71'
	Local variables:
	 _ = string: "/home/daniel/MoonGen/build/MoonGen"
	 file = string: "./test/tests/01-send.lua"
	 args = table: 0x40534e70  {}
	 cfgFile = nil
(5) Lua function 'main' at file '/home/daniel/MoonGen/build/../libmoon/lua/main.lua:143' (best guess)
	Local variables:
	 task = string: "master"
	./test/tests/01-send.lua:10: module 'testlog' not found:
	no field package.preload['testlog']
	no file '/home/daniel/MoonGen/build/../libmoon/../lua/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/../lua/testlog/init.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/../lua/lib/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/../lua/lib/testlog/init.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/testlog/init.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/lib/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/lib/turbo/testlog.lua'
	no file '/home/daniel/MoonGen/build/../libmoon/lua/lib/testlog/init.lua'
	no file './testlog.lua'
	no file '/usr/local/share/luajit-2.1.0-beta2/testlog.lua'
	no file '/usr/local/share/lua/5.1/testlog.lua'
	no file '/usr/local/share/lua/5.1/testlog/init.lua'
	no file './test/tests/testlog.lua'
	no file './testlog.so'
	no file '/usr/local/lib/lua/5.1/testlog.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by emmericp** [comment]
You can't run the unit tests standalone, sorry. They need some environment stuff and generated config.

**Comment by dosarudaniel** [comment]
Can you give more details about this, please?
