### ISSUE TITLE
packet-size.lua error

### ISSUE THREAD

**Issue by dosarudaniel** [emmericp/MoonGen#187]
I modified [this script](https://github.com/emmericp/MoonGen/blob/master/examples/benchmark/packet-sizes.lua) like this: [https://github.com/dosarudaniel/MoongenScripts/blob/master/packet-size.lua](url) but when I run it using Moongen I get Segmentation Fault at the next iteration, for the second packet size. (If I start with 64, I get Segmentation Fault at 65, If I start with 60, I get Segmentation Fault at 61 and so on):
daniel@daniel-KVM:~/MoonGen$ sudo ./build/MoonGen ./examples/benchmark/packet-sizes.lua 0
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
[WARN]  mempool cache is currently broken, this will probably crash
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 6 lcore(s)
EAL: Probing VFIO support...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:00:0a.0 on NUMA socket -1
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
[INFO]  Found 1 usable devices:
   Device 0: 00:25:90:96:61:31 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
[WARN]  device.config() without named arguments is deprecated and will be removed. See documentation for libmoons device.config().
[INFO]  Waiting for devices to come up...
[INFO]  Device 0 (00:25:90:96:61:31) is up: 10000 MBit/s
[INFO]  1 device is up.
Running test for packet size = 64
[WARN]  dpdk.launchLua() is deprecated, use moongen.startTask() instead.
[WARN]  mempool cache is currently broken, this will probably crash
[WARN]  dpdk.running() is deprecated, use moongen.running() instead.
[Device: id=0] TX: 10.39 Mpps, 5652 Mbit/s (7315 Mbit/s with framing)
[Device: id=0] TX: 10.41 Mpps, 5663 Mbit/s (7328 Mbit/s with framing)
[Device: id=0] TX: 10.44 Mpps, 5680 Mbit/s (7350 Mbit/s with framing)
[Device: id=0] TX: 10.41 Mpps, 5661 Mbit/s (7326 Mbit/s with framing)
[Device: id=0] TX: 10.28 Mpps, 5592 Mbit/s (7236 Mbit/s with framing)
[Device: id=0] TX: 10.42 Mpps, 5671 Mbit/s (7338 Mbit/s with framing)
[Device: id=0] TX: 10.42 Mpps, 5671 Mbit/s (7339 Mbit/s with framing)
[Device: id=0] TX: 10.46 Mpps, 5691 Mbit/s (7365 Mbit/s with framing)
[Device: id=0] TX: 10.38 Mpps, 5646 Mbit/s (7306 Mbit/s with framing)
[Device: id=0] TX: 10.40 (StdDev 0.06) Mpps, 5659 (StdDev 30) Mbit/s (7324 Mbit/s with framing), total 104072472 packets with 7076928096 bytes (incl. CRC)
[WARN]  dpdk.running() is deprecated, use moongen.running() instead.
Running test for packet size = 65
[WARN]  mempool cache is currently broken, this will probably crash
Segmentation fault (core dumped)

**Do you have any ideea what causes this issue and how can I solved it?**

**Comment by emmericp** [comment]
>  [WARN] mempool cache is currently broken, this will probably crash

DPDK broke this, unfortunately, no way to fix it at the moment.
Don't enable it.

In general, it's a bad idea to create to many memory pools, consider recycling it.
