### ISSUE TITLE
Device is DOWN

### ISSUE THREAD

**Issue by dosarudaniel** [emmericp/MoonGen#188]
I modified [this script](https://github.com/emmericp/MoonGen/blob/master/examples/benchmark/packet-sizes.lua) like this: [https://github.com/dosarudaniel/MoongenScripts/blob/master/packet-size.lua]( https://github.com/dosarudaniel/MoongenScripts/blob/master/packet-size.lua) but when I run it using Moongen:

sudo ./build/MoonGen ./examples/benchmark/packet-sizes.lua 0

 I get this message: 

> [WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
> [WARN]  Install libjemalloc if you encounter out of memory errors.
> [WARN]  mempool cache is currently broken, this will probably crash
> [INFO]  Initializing DPDK. This will take a few seconds...
> EAL: Detected 6 lcore(s)
> EAL: Probing VFIO support...
> EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
> PMD: bnxt_rte_pmd_init() called for (null)
> EAL: PCI device 0000:00:0a.0 on NUMA socket -1
> EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
> [INFO]  Found 1 usable devices:
>    Device 0: 00:25:90:96:61:31 (Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection)
> [WARN]  device.config() without named arguments is deprecated and will be removed. See documentation for libmoons device.config().
> [INFO]  Waiting for devices to come up...
> [ERROR] Device 0 (00:25:90:96:61:31) is DOWN: 0 MBit/s
> [INFO]  0 devices are up.
> Running test for packet size = 64
> [WARN]  dpdk.launchLua() is deprecated, use moongen.startTask() instead.
> [WARN]  mempool cache is currently broken, this will probably crash
> [WARN]  dpdk.running() is deprecated, use moongen.running() instead.

**I am don't know why Device 0 is DOWN. Before running this script I did:**

>sudo ./setup-hugetlbfs.sh
>sudo ./bind-interfaces.sh  #this command  output was: Binding interface 0000:00:0a.0 to DPDK.

**Comment by emmericp** [comment]
I can't tell you why your device is down.

**Comment by guimvmatos** [comment]
Hi, I'm with the same error:
![image](https://github.com/emmericp/MoonGen/assets/19318215/59acbc6d-a5c5-435e-8c86-76f47056b834)
Can somebody help here?
