### ISSUE TITLE
Latency measurement of tunneled traffic

### ISSUE THREAD

**Issue by pauerjanos** [emmericp/MoonGen#190]
Hi,

Among the examples, I found the script that measures the latency of UDP traffic (MoonGen/examples/timestamping-tests/timestamps-software.lua). Is it possible to measure tunneled traffic's latency (e.g. vxlan/gre) with this method? Are you planning to implement this feature, or do you have any idea how to implement it?

Thanks,
János

**Comment by emmericp** [comment]
the software timestamper does not care about the type of packet
