### ISSUE TITLE
Reading the rss hash value

### ISSUE THREAD

**Issue by ztz1989** [emmericp/MoonGen#191]
Hi, Paul. I have been using Moongen recently and I really rely on it now. I do believe we all should pay you for using MoonGen, at least I am willing to do that. 
  Currently, I want to classify packets into flows, and use the RSS hash value to distinguish each flow. 
   I just have a small question regarding the rte_mbuf. In a MoonGen script, I enabled RSS by specifying rssQueue=2 with the default RSS functions for a port. Then in the slave thread, for each of the received packet, I want to read the RSS hash value which is a valid metadata field in rte_mbuf structure. But the rss value I got was always zero. The code snippet is shown as follows:

**while lm.running() do
                local rx = queue:tryRecv(bufs, 100)
                for i = 1, rx do
                        local buf = bufs[i]
                        print(buf.hash.rss)
                        end
                end
end**

The code always prints zeros. Do you think I did something wrong? Because I wrote a similar program in DPDK and managed to get the real rss values. Do you know if there is a way to solve my issue? Thanks again for your excellent work and for your time to check this issue.

  Best regards!

**Comment by emmericp** [comment]
i think there is some driver parameter required to fill in this field, which nic are you using?

**Comment by ztz1989** [comment]
Hi, Paul. The NIC is Intel 82599ES 10-Gigabit SFI/SFP+.

**Comment by emmericp** [comment]
fixed it in the latest commit, problem was specific to ixgbe-NICs which reported a fdir filter instead
