### ISSUE TITLE
Duplicates when respond with more than one packet at a time

### ISSUE THREAD

**Issue by minmit** [emmericp/MoonGen#193]
Hi,

I have two instances of MoonGen running on two different servers. One of them is generating udp traffic, and I want the other one to swap the 5 tuple and return the traffic. I'm using the icmp-arp-responder.lua example as a starter, but this example reads one packet at a time. When I read more than one packet at a time, for performance reasons, the output stream of packets contains multiple duplicates of the original packets. If I copy the packets into a new buffer, this problem goes away but the performance degrades significantly. Do you have an insight on how to make this work without duplicates?

Thanks

**Comment by emmericp** [comment]
check out https://github.com/libmoon/libmoon/blob/master/examples/reflector.lua
