### ISSUE TITLE
ConnectX-3 Pro support by MoonGen

### ISSUE THREAD

**Issue by sr-chaudhry** [emmericp/MoonGen#194]
Hi Emmercip,

I have a queury as i have 

PowerEdge T430.

Intel Xeon E5-2620 v4 2.1GHz,20M Cache,8.0GT/s QPI,Turbo,HT,8C/16T (85W) Max Mem.
32GB RDIMM, 2400MT/s, Dual Rank, x4 Data Width
PERC H330 Integrated RAID Controller
Mellanox ConnectX-3 Pro Dual Port 10 GbE SFP+ PCIE Adapter Full Height, V2
Mellanox, Transceiver, SFP+, 10Gb, Short-Range, for use in Mellanox CX3 10Gb NW Adpt Only
Single, Hot-plug Power Supply (1+0), 495W
On-Board LOM 1GBE (Dual Port for Towers and DSS, Quad Port for Racks and Blades)

But while installing, i figured out Mellanox ConnectX-3pro is not supported by Moongen. Can you kindly confirm if i am correct. 

Because on moongen Github site, it clearly sayd the required firmware are ConnectX-4 and ConnectX-5.

Your help will be of great support.

Thanks.

**Comment by emmericp** [comment]
i don't have access to a connectx-3, so I don't know if it will work, but you can try. i don't know which firmware and ofed versions are required for it, please let me know what works for you. the instructions are here: https://github.com/libmoon/libmoon/blob/master/install-mlx.md

**Comment by pchaigno** [comment]
Works for me with firmware version 2.40.7000 and OFED Linux 4.1-1.

**Comment by sr-chaudhry** [comment]
Hi Paul,

 

So did the connectX-3 worked with this OFED Linux 4.1-1 and firmware 2.40.7000 for you? 

 

Sent: Saturday, October 21, 2017 at 4:40 PM

**Comment by pchaigno** [comment]
Yes.
