### ISSUE TITLE
Errors Build on Ubuntu Xenial

### ISSUE THREAD

**Issue by h3kr** [emmericp/MoonGen#198]
i m trying to compile MoonGen as described with ./build.sh

but i keep getting those errors 

/MoonGen/libmoon/src/memory.c:2:22: fatal error: rte_mbuf.h: No such file or directory
compilation terminated.
libmoon/CMakeFiles/moon.dir/build.make:86: recipe for target 'libmoon/CMakeFiles/moon.dir/src/memory.c.o' failed
make[2]: *** [libmoon/CMakeFiles/moon.dir/src/memory.c.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'libmoon/CMakeFiles/moon.dir/all' failed
make[1]: *** [libmoon/CMakeFiles/moon.dir/all] Error 2
Makefile:83: recipe for target 'all' failed

**Comment by emmericp** [comment]
can you please post the whole error message?

**Comment by h3kr** [comment]
rootkit@rooter:~/Documents/MoonGen$ ./build.sh
Build libmoon with MoonGen
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/home/rootkit/Documents/MoonGen/libmoon/deps/luajit/src'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/rootkit/Documents/MoonGen/libmoon/deps/luajit/src'
==== Successfully built LuaJIT 2.1.0-beta3 ====
==== Installing LuaJIT 2.1.0-beta3 to /usr/local ====
mkdir -p /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/bin /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/include/luajit-2.1 /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/share/man/man1 /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/pkgconfig /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/share/luajit-2.1.0-beta3/jit /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/share/lua/5.1 /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/lua/5.1
cd src && install -m 0755 luajit /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/bin/luajit-2.1.0-beta3
cd src && test -f libluajit.a && install -m 0644 libluajit.a /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/libluajit-5.1.a || :
rm -f /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/libluajit-5.1.so.2.1.0 /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/libluajit-5.1.so /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/libluajit-5.1.so.2
cd src && test -f libluajit.so && \
  install -m 0755 libluajit.so /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/libluajit-5.1.so.2.1.0 && \
  ldconfig -n /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib && \
  ln -sf libluajit-5.1.so.2.1.0 /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/libluajit-5.1.so && \
  ln -sf libluajit-5.1.so.2.1.0 /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/libluajit-5.1.so.2 || :
cd etc && install -m 0644 luajit.1 /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/share/man/man1
cd etc && sed -e "s|^prefix=.*|prefix=/usr/local|" -e "s|^multilib=.*|multilib=lib|" luajit.pc > luajit.pc.tmp && \
  install -m 0644 luajit.pc.tmp /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/lib/pkgconfig/luajit.pc && \
  rm -f luajit.pc.tmp
cd src && install -m 0644 lua.h lualib.h lauxlib.h luaconf.h lua.hpp luajit.h /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/include/luajit-2.1
cd src/jit && install -m 0644 bc.lua bcsave.lua dump.lua p.lua v.lua zone.lua dis_x86.lua dis_x64.lua dis_arm.lua dis_arm64.lua dis_arm64be.lua dis_ppc.lua dis_mips.lua dis_mipsel.lua dis_mips64.lua dis_mips64el.lua vmdef.lua /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/share/luajit-2.1.0-beta3/jit
==== Successfully installed LuaJIT 2.1.0-beta3 to /usr/local ====

Note: the development releases deliberately do NOT install a symlink for luajit
You can do this now by running this command (with sudo):

  ln -sf luajit-2.1.0-beta3 /home/rootkit/Documents/MoonGen/libmoon/deps/luajit/usr/local/bin/luajit

Configuration done using x86_64-native-linuxapp-gcc
== Build lib
== Build lib/librte_compat
== Build lib/librte_eal
== Build lib/librte_eal/common
== Build lib/librte_eal/linuxapp
== Build lib/librte_eal/linuxapp/eal
  CC eal.o
In file included from /usr/include/stdio.h:27:0,
                 from /home/rootkit/Documents/MoonGen/libmoon/deps/dpdk/lib/librte_eal/linuxapp/eal/eal.c:35:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
/home/rootkit/Documents/MoonGen/libmoon/deps/dpdk/mk/internal/rte.compile-pre.mk:138: recipe for target 'eal.o' failed
make[5]: *** [eal.o] Error 1
/home/rootkit/Documents/MoonGen/libmoon/deps/dpdk/mk/rte.subdir.mk:63: recipe for target 'eal' failed
make[4]: *** [eal] Error 2
/home/rootkit/Documents/MoonGen/libmoon/deps/dpdk/mk/rte.subdir.mk:63: recipe for target 'linuxapp' failed
make[3]: *** [linuxapp] Error 2
/home/rootkit/Documents/MoonGen/libmoon/deps/dpdk/mk/rte.subdir.mk:63: recipe for target 'librte_eal' failed
make[2]: *** [librte_eal] Error 2
/home/rootkit/Documents/MoonGen/libmoon/deps/dpdk/mk/rte.sdkbuild.mk:76: recipe for target 'lib' failed
make[1]: *** [lib] Error 2
/home/rootkit/Documents/MoonGen/libmoon/deps/dpdk/mk/rte.sdkroot.mk:128: recipe for target 'all' failed
make: *** [all] Error 2
make -C deps/http-parser library
make[1]: Entering directory '/home/rootkit/Documents/MoonGen/libmoon/lua/lib/turbo/deps/http-parser'
gcc  -shared -Wl,-soname=libhttp_parser.so.2.1 -o libhttp_parser.so.2.1 libhttp_parser.o
make[1]: Leaving directory '/home/rootkit/Documents/MoonGen/libmoon/lua/lib/turbo/deps/http-parser'
gcc -Ideps/http-parser/ -shared -O3 -Wall -g  -fPIC deps/http-parser/libhttp_parser.o deps/turbo_ffi_wrap.c -o libtffi_wrap.so  -lcrypto -lssl
Makefile:87: recipe for target 'all' failed
Could not compile Turbo with TLS support, disabling TLS
Install libssl-dev and OpenSSL to enable TLS support
make -C deps/http-parser library
make[1]: Entering directory '/home/rootkit/Documents/MoonGen/libmoon/lua/lib/turbo/deps/http-parser'
gcc  -shared -Wl,-soname=libhttp_parser.so.2.1 -o libhttp_parser.so.2.1 libhttp_parser.o
make[1]: Leaving directory '/home/rootkit/Documents/MoonGen/libmoon/lua/lib/turbo/deps/http-parser'
gcc -Ideps/http-parser/ -shared -O3 -Wall -g  -fPIC -DTURBO_NO_SSL=1 deps/http-parser/libhttp_parser.o deps/turbo_ffi_wrap.c -o libtffi_wrap.so 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rootkit/Documents/MoonGen/build
[  3%] Building C object libmoon/CMakeFiles/moon.dir/src/memory.c.o
/home/rootkit/Documents/MoonGen/libmoon/src/memory.c:2:22: fatal error: rte_mbuf.h: No such file or directory
compilation terminated.
libmoon/CMakeFiles/moon.dir/build.make:86: recipe for target 'libmoon/CMakeFiles/moon.dir/src/memory.c.o' failed
make[2]: *** [libmoon/CMakeFiles/moon.dir/src/memory.c.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'libmoon/CMakeFiles/moon.dir/all' failed
make[1]: *** [libmoon/CMakeFiles/moon.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Trying to bind interfaces, this will fail if you are not root
Try sudo ./bind-interfaces.sh if this step fails
modprobe: ERROR: could not insert 'uio': Operation not permitted
insmod: ERROR: could not load module ./x86_64-native-linuxapp-gcc/kmod/igb_uio.ko: No such file or directory
Could not find any inactive interfaces to bind to DPDK. Note that this script does not bind interfaces that are in use by the OS.
Delete IP addresses from interfaces you would like to use with libmoon and run this script again.
You can also use the script dpdk-devbind.py in deps/dpdk/usertools manually to manage interfaces used by libmoon and the OS.

**Comment by emmericp** [comment]
```
In file included from /usr/include/stdio.h:27:0,
from /home/rootkit/Documents/MoonGen/libmoon/deps/dpdk/lib/librte_eal/linuxapp/eal/eal.c:35:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
```

there is something seriously wrong with your compilation environment as it fails in a standard library, I can't you with that, sorry.
