### ISSUE TITLE
Moongen is sending traffic which is nowhere received

### ISSUE THREAD

**Issue by computer5student** [emmericp/MoonGen#202]
Hello,

I am new to MoonGen and I am trying to use it to measure the RTT between two applications. I have slightly changed the l3-load-latency.lua example (just different ports and IPs) to send traffic to my destination, but even though MoonGen claims that traffic is being send, I do not see traffic being received at the other host via tcpdump.

To me it looks exactly the same if I start the moongen-simple example to test this locally. Traffic is said being send but receive traffic is not being observed:

jang@santa4:~/MoonGen$ sudo ./moongen-simple start load-latency:0:0:rate=10Mp/s
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:19.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:153a net_e1000_em
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1528 net_ixgbe
EAL: PCI device 0000:01:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1528 net_ixgbe
[INFO]  Found 1 usable devices:
   Device 0: A0:36:9F:70:9E:98 (Intel Corporation Ethernet Controller 10-Gigabit X540-AT2)
[INFO]  Flow load-latency => 0x1
PMD: ixgbe_dev_link_status_print():  Port 0: Link Down
[INFO]  Waiting for devices to come up...
[INFO]  Device 0 (A0:36:9F:70:9E:98) is up: 10000 MBit/s
[INFO]  1 device is up.
[Device: id=0] TX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] TX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] TX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] TX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] TX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] TX: 7.35 Mpps, 3764 Mbit/s (4940 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Flow: dev=0 uid=0x1] TX: 7.94 Mpps, 4065 Mbit/s (5336 Mbit/s with framing)
[Device: id=0] TX: 7.74 Mpps, 3964 Mbit/s (5203 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Flow: dev=0 uid=0x1] TX: 7.72 Mpps, 3955 Mbit/s (5190 Mbit/s with framing)
[Device: id=0] TX: 7.85 Mpps, 4017 Mbit/s (5272 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Flow: dev=0 uid=0x1] TX: 7.85 Mpps, 4020 Mbit/s (5277 Mbit/s with framing)
[Device: id=0] TX: 7.83 Mpps, 4008 Mbit/s (5260 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Flow: dev=0 uid=0x1] TX: 7.83 Mpps, 4010 Mbit/s (5263 Mbit/s with framing)
[Device: id=0] TX: 7.84 Mpps, 4013 Mbit/s (5267 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Flow: dev=0 uid=0x1] TX: 7.82 Mpps, 4006 Mbit/s (5257 Mbit/s with framing)
[Device: id=0] TX: 7.81 Mpps, 3997 Mbit/s (5246 Mbit/s with framing)
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)

Is this the intended behaviour of the moongen-simple example? I am a bit confused that sending simple traffic does not seem to work while I am not being confronted with any kind of error.

OS: Ubuntu 15.04
NIC: Intel Corporation Ethernet Controller 10-Gigabit X540-AT2 (rev 01)

**Comment by pchaigno** [comment]
Is your second host directly connected to the host sending packets (i.e., no switch in-between)? Are you able to send packets using DPDK (ex. `test-pmd`)?

**Comment by emmericp** [comment]
the stats come directly from hardware counters on the NIC. So yes, packets are being sent out and there's something wrong with your setup.
