### ISSUE TITLE
Found 0 usable devices

### ISSUE THREAD

**Issue by h3kr** [emmericp/MoonGen#204]
MoonGen seems not to find any device to use in sending even that it succeeded to bind 3 NICs. is there any thing else i need to configure first ?? or to test the devices ?? 

[100%] Built target MoonGen
Trying to bind interfaces, this will fail if you are not root
Try sudo ./bind-interfaces.sh if this step fails
Binding interface 0000:01:00.0 to DPDK
Binding interface 0000:01:00.1 to DPDK
Binding interface 0000:02:00.1 to DPDK

checking with dpdk-devbind

~/MoonGen/libmoon/deps/dpdk/usertools$ sudo python dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0000:01:00.0 'NetXtreme II BCM5709 Gigabit Ethernet 1639' drv=igb_uio unused=
0000:01:00.1 'NetXtreme II BCM5709 Gigabit Ethernet 1639' drv=igb_uio unused=
0000:02:00.1 'NetXtreme II BCM5716 Gigabit Ethernet 163b' drv=igb_uio unused=

Network devices using kernel driver
===================================
0000:02:00.0 'NetXtreme II BCM5716 Gigabit Ethernet 163b' if=eno1 drv=bnx2 unused=igb_uio *Active*

seadmin@secloud-srv-r07:~/MoonGen$ sudo ./build/MoonGen examples/l3-tcp-syn-flood.lua 
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 8 lcore(s)
EAL: Probing VFIO support...
[INFO]  Found 0 usable devices:

I m using Ubuntu 16.04.3 LTS

**Comment by emmericp** [comment]
i don't think that these NICs are supported by DPDK
