### ISSUE TITLE
Software rate contol does not work with 25G NIC

### ISSUE THREAD

**Issue by janospauer** [emmericp/MoonGen#207]
Hi Paul,

I have tried to do my measurements with software rate control while there are issues with HW generating (I'm referring to the other ticket). I observed that no matter how many rateLimiter objects I use, I cannot get higher rate than 13 Mpps. The funny thing is, that it looks like it is a limit for all packet sizes.
Here's what I am talking about:
Traffic generating with 2 queues, trying to get 14 Mpps 
64B packet:
[Device: id=0] TX: 13.80 Mpps, 7507 Mbit/s (9715 Mbit/s with framing)
[Device: id=0] TX: 13.86 Mpps, 7539 Mbit/s (9757 Mbit/s with framing)
[Device: id=0] TX: 13.88 Mpps, 7551 Mbit/s (9772 Mbit/s with framing)
[Device: id=0] TX: 13.88 Mpps, 7549 Mbit/s (9770 Mbit/s with framing)
[Device: id=0] TX: 13.87 (StdDev 0.01) Mpps, 7547 (StdDev 6) Mbit/s (9766 Mbit/s with framing), total 69397280 packets with 4719015040 bytes (incl. CRC)

128B packet:
[Device: id=0] TX: 13.45 Mpps, 14198 Mbit/s (16350 Mbit/s with framing)
[Device: id=0] TX: 13.38 Mpps, 14133 Mbit/s (16274 Mbit/s with framing)
[Device: id=0] TX: 13.53 Mpps, 14288 Mbit/s (16453 Mbit/s with framing)
[Device: id=0] TX: 13.54 Mpps, 14301 Mbit/s (16467 Mbit/s with framing)
[Device: id=0] TX: 13.49 (StdDev 0.09) Mpps, 14241 (StdDev 93) Mbit/s (16398 Mbit/s with framing), total 67461472 packets with 8904914304 bytes (incl. CRC)

256B packet (This is wire rate limit now):
[Device: id=0] TX: 11.15 Mpps, 23187 Mbit/s (24970 Mbit/s with framing)
[Device: id=0] TX: 11.12 Mpps, 23122 Mbit/s (24901 Mbit/s with framing)
[Device: id=0] TX: 11.16 Mpps, 23212 Mbit/s (24997 Mbit/s with framing)
[Device: id=0] TX: 11.16 Mpps, 23214 Mbit/s (25000 Mbit/s with framing)
[Device: id=0] TX: 11.15 (StdDev 0.03) Mpps, 23183 (StdDev 52) Mbit/s (24966 Mbit/s with framing), total 55770656 packets with 14500370560 bytes (incl. CRC)

If I increase the number of rate limiters, the results don't change.
Below 13 Mpps, it works like charm.

Regards,
János

**Comment by emmericp** [comment]
yes, software rate limiting takes a heavy toll on performance because batching can't be used and you can't get performance without batches. you'll have to use multiple threads for software rate limiting.
