### ISSUE TITLE
Junk value for ratelimiter.stop terminates generation

### ISSUE THREAD

**Issue by deebhatia** [emmericp/MoonGen#208]
Hi,
I am running MoonGen on 16.04 ubuntu VM.
I am using the `cbr` ratelimiter for controlling packet rate but it behaves incorrectly. While creating a new rate limiter [here](https://github.com/emmericp/MoonGen/blob/master/lua/software-ratecontrol.lua#L76), `stop` attribute of `struct limiter_control` gets a junk value (non zero in general) causing [this](https://github.com/emmericp/MoonGen/blob/master/src/software-rate-limiter.cpp#L34) function to exit. 
I checked the value for `ctl->stop` variable while creating a new rate limiter in `lua/software-ratecontrol.lua`, it was non-zero. Updating the value to zero before starting the task `__MG_RATE_LIMITER_MAIN` seems to make the problem go away. It is somehow ignoring the initialisation done [here](https://github.com/emmericp/MoonGen/blob/master/src/software-rate-limiter.cpp#L32). 

Similar behaviour observed when using the `examples/rate-control-methods.lua` with command 
```bash
./build/MoonGen examples/rate-control-methods.lua 0 2 sw cbr 1
```

Is there anything which I am missing here?

Thanks,
Deepanshu

**Comment by emmericp** [comment]
thanks for the detailed report, I've fixed it
