### ISSUE TITLE
Unable to configure bufSize during memPool creating

### ISSUE THREAD

**Issue by adolia** [emmericp/MoonGen#210]
Hi!
I have an issue with mempool bufSize configuring, I've tried to set it in device configuring as:
`device.config{port = args.dev1, bufSize = args.bufsize}`
this value is set for device but not for memPool.
Also I've tried to pass bufSize value to createMemPool:
`local mempool = memory:createMemPool{n = 2048, bufSize = bufsize}`
But have no luck.
Any idea how can I set bufSize?

Thanks in advance.
Br,
Alex

**Comment by ashokkumarprajapati** [comment]
Hi Alex,
What issue are you getting? I am using the same method and works fine for me.
I am setting bufSize=2048 to createMemPool and I can see pool with bufferSize 2176 ( 2048 + Head Room 128) created.

**Comment by adolia** [comment]
Hi!
I think it's related to wrong memory:createMemPool usage.
memory:createMemPool is wrong, need to use memory.createMemPool.
I'll close this issue.
