### ISSUE TITLE
Cannot build examples

### ISSUE THREAD

**Issue by jrozhon** [emmericp/MoonGen#212]
Hey, I am a newbie, so please if this is a stupid question and I am missing something trivial.

I have a setup on debian 9 running on VMWare Host. Whenever I try to build any of the examples I get the following error. Could anyone give me some hints on what I am doing wrong?

Thank you.

`./build/MoonGen examples/l3-load-latency.lua 0 1
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 4 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: PCI device 0000:0b:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: PCI device 0000:13:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: PCI device 0000:1b:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
[INFO]  Found 2 usable devices:
   Device 0: 00:0C:29:11:63:EC (VMware VMXNET3 Ethernet Controller)
   Device 1: 00:0C:29:11:63:D8 (VMware VMXNET3 Ethernet Controller)
[FATAL] Lua error in task master
/usr/src/MoonGen/build/../libmoon/lua/device.lua:196: Could not configure device 0: error Invalid argument
Stack Traceback
===============
(2) Lua method 'fatal' at file '/usr/src/MoonGen/build/../libmoon/lua/log.lua:129'
	Local variables:
	 self = table: 0x41548f98  {DEBUG:0, fatal:function: 0x4110a820, writeToLog:function: 0x4110a800, INFO:1 (more...)}
	 str = string: "Could not configure device 0: error Invalid argument"
(3) Lua field 'config' at file '/usr/src/MoonGen/build/../libmoon/lua/device.lua:196'
	Local variables:
	 args = table: 0x40b94ac8  {rxQueues:3, stripVlan:true, dropEnable:true, disableOffloads:true, mempools:table: 0x4024f8c8 (more...)}
	 driverInfo = table: 0x405b3228  {disableOffloads:true}
	 rc = number: -22
(4) Lua function 'master' at file 'examples/l3-load-latency.lua:37' (best guess)
	Local variables:
	 args = table: 0x41cbea90  {rxDev:1, txDev:0, flows:4, rate:10000, size:60}
(5) global C function 'xpcall'
(6) Lua upvalue 'master' at file '/usr/src/MoonGen/build/../libmoon/lua/main.lua:96'
	Local variables:
	 _ = string: "./build/MoonGen"
	 file = string: "examples/l3-load-latency.lua"
	 args = table: 0x402cd048  {1:0, 2:1}
	 cfgFile = nil
	 ok = boolean: true
	 parsedArgs = table: 0x41cbe7a8  {1:table: 0x41cbea90}
(7) Lua function 'main' at file '/usr/src/MoonGen/build/../libmoon/lua/main.lua:146' (best guess)
	Local variables:
	 task = string: "master"
	/usr/src/MoonGen/build/../libmoon/lua/device.lua:196: Could not configure device 0: error Invalid argument
`

**Comment by emmericp** [comment]
The most likely cause for this is that your virtual NIC doesn't support multiple queues. Most examples require multiple queues and are optimized for real hardware.

VMWare should support multi-queue, so you should be able to enable this.
