### ISSUE TITLE
Constant loss with MoonGen in VM Compare to PktGen-DPDK or Simple DPDK-Receiver

### ISSUE THREAD

**Issue by ashokkumarprajapati** [emmericp/MoonGen#213]
I have been running MoonGen, DPDK-Pktgen and Simple DPDK example. DPDK Example and DPDK-Pktgen do not loss any pkts at 3Mpps, however MoonGen keeps on loosing constant 3-10K packets in 10 sec iteration.

**DUT setup:**
2 VMs (with CPU pinning and Huge Pages) on two different Compute nodes. Both VMS have NUMA enabled i.e. 2 NUMA nodes exposed in VMs.
Compute nodes are running OVS-DPDK.
NUMA node0 CPU(s):     0-3
NUMA node1 CPU(s):     4-7

**Test:**
Packets sent using MoonGen sender lua.
Packets sent: 29775233 in 10 Sec
_Packets Received:_

- PktGen-DPDK as receiver
     29775233
- B. DPDK example receiver
     29775233
- C. MoonGen Receiver (_trimmed version of **rx-pkts-distribution.lua** from examples_)
     29766527 

I have **repeated this test many times (>30)** and same results ( Loss in MoonGen receiver does vary but it always have loss).

**Debugging/Analysis Done:**
I have modified MoonGen receiver to have exact similar configuration as other 2 applications. This is done in order to identify exact issue.
I can confirm below configuration is same in all:
1. MemBuffer was created in Socket-0 with RxDescs 64512 and BufSize 2176 (2048 + Head Room)
2. RxQueue was forced to create on Socket-0 ( By small change in device.lua). Logically should not be required as MemBuffer was created in correct socket.
3. Counter Task was running on lCore 2. (Updated DPDK-Conf.lua to force pins to be used of only socket-0 using cores param)
4. Master task was running on lCore 1.

I am still not able to find exact root cause of this loss. 
Note that if MemBuffer is smaller or in wrong socket then i see similar behaviour in DPDK-receiver example too.

**Comment by emmericp** [comment]
You will lose packets before/during the initial JIT compilation, this is expected and cannot be avoided when Lua is involved in the receive logic.

We don't consider this a problem, because:

1. if you want to count packets then hardware counters are the only reliable way anyways
2. if you want to receive actual packets for a benchmark, then any benchmarking standard will specify a warm-up phase
3. if you just want to receive packets from a real link: you will be plugging into live traffic and the concept of packet loss during startup is meaningless

if you really want to receive all packets from startup on, then you'll have to write all the logic in C/C++.

**Comment by emmericp** [comment]
The JIT compilation only happens after traffic is applied.

**Comment by ashokkumarprajapati** [comment]
@emmericp Thanks for clarification.
I think you misunderstood me.
Here is flow:
1. Start receiver side a few seconds early and then run 5 sec warmup before counting actual traffic.
    Warmup traffic and actual traffic have different payload. 
    I am differentiating packets based on payload data. All warm-up packets are simply dropped.
    Total Execution Time: 75 Sec (Including Warmup-10 sec)
   **Note that it happens in same Task without stopping it.**
2. Sender has a 1 sec delay between warmup and actual traffic start. 
    Warmup time: 10 Sec
    Delay between warmup and actual traffic: 1 Sec 
    Traffic time: 60 Sec
    Total Execution Time : 71 Sec

So i guess its not an issue of JIT compilation as warmup traffic is already received. 
When looking into HOST OVS, I can see that virtual port is arbitrarily dropping traffic.

**Comment by emmericp** [comment]
Warming up with different traffic achieves nothing. The code will be recompiled because LuaJIT is a tracing JIT.
