### ISSUE TITLE
platform independent build

### ISSUE THREAD

**Issue by Nic30** [emmericp/MoonGen#215]
Hello,

I see that current build scripts are written only for x86_64 platform.
I would like rework cmake files to support different platforms as well.
This action includes support for libraries already installed on platform (dpdk, luajit) (custom findXXX.cmake).

But I see there are direct dependencies on PMDs for Intel cards.
https://github.com/libmoon/libmoon/blob/e159155e48dd4429070111a8f08ce99033936d45/CMakeLists.txt#L73

Does this mean that MoonGen does not work without Intel PMDs?
I would like to port MoonGen on NXP LS2088 (8*10G, 8*2GHz ARM A72).
(DPDK for this platform does not have Intel PMDs  ...)

**Comment by emmericp** [comment]
There's some code in MoonGen that works better on Intel NICs but in general we support any NIC supported by DPDK: https://dpdk.org/doc/nics

We currently hardcode the most common NICs in the build, but that can be changed/any PMD should be able to be added.

**Comment by Nic30** [comment]
That is great! I will make required changes in fork of your library and create Yocto package. (after two months)
