### ISSUE TITLE
RX stats of a virtio device

### ISSUE THREAD

**Issue by nemethf** [emmericp/MoonGen#216]
I have a rather complex configuration in which it seems that stats module cannot detect incoming traffic on a "Red Hat, Inc Virtio network device".  I checked that traffic indeed arrived to the port.  Also the same setup works with a igb_uio driver (in a non VM case). 

Are the rx stats supposed to work with virtio?  In that case, I'll try to come up with a concise example to demonstrate the buggy behavior.   However, the complex setup is [here](https://github.com/hsnlab/tipsy/tree/vagrant/vagrant), in which [the moongen script](https://raw.githubusercontent.com/hsnlab/tipsy/vagrant/utils/mg-flood.lua) is a slight variation of replay-pcap.lua.

Thank you.

**Comment by emmericp** [comment]
VirtIO can't count packets that are not actively being received by the virtual NIC as they are already dropped on the hypervisor by the virtual switch because the queue runs full.

You unfortunately have to explicitly receive the packets and drop them, otherwise they can't be counted.

**Comment by nemethf** [comment]
That was helpful.  Thanks again.
