### ISSUE TITLE
Failed to configure RSS queues 

### ISSUE THREAD

**Issue by daehyeok-kim** [emmericp/MoonGen#219]
Hello, 

When I tried to run examples/rss.lua to see how to configure RSS, I got the following error:

> :~/MoonGen$ sudo ./build/MoonGen ./examples/rss.lua 0 1
[sudo] password for dk:
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 16 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:02:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:02:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 15b3:1007 net_mlx4
PMD: net_mlx4: PCI information matches, using device "mlx4_0" (VF: false)
PMD: net_mlx4: 2 port(s) detected
PMD: net_mlx4: port 1 MAC address is e0:07:1b:70:0c:51
PMD: net_mlx4: port 2 MAC address is e0:07:1b:70:0c:52
[INFO]  Found 3 usable devices:
   Device 0: 98:F2:B3:8D:E7:00 (Intel Corporation I350 Gigabit Network Connection)
   Device 1: E0:07:1B:70:0C:51 (Mellanox Technologies MT27520 Family [ConnectX-3 Pro])
   Device 2: E0:07:1B:70:0C:52 (Mellanox Technologies MT27520 Family [ConnectX-3 Pro])
PMD: net_mlx4: 0x950640: TX queues number update: 0 -> 1
PMD: net_mlx4: 0x950640: number of RX queues must be a power of 2: 2 queues among 3 will be active
PMD: net_mlx4: 0x950640: RX queues number update: 0 -> 3
[FATAL] Lua error in task master
/home/dk/MoonGen/build/../libmoon/lua/device.lua:245: attempt to index global 'errors' (a nil value)
Stack Traceback
===============
(2) Lua field 'config' at file '/home/dk/MoonGen/build/../libmoon/lua/device.lua:202'
        Local variables:
         args = table: 0x41926138  {rxQueues:3, stripVlan:true, dropEnable:true, mempools:table: 0x41928e18 (more...)}
         driverInfo = table: 0x41928950  {}
         rc = number: 0
         dev = [Device: id=1]  {initialized:true, rxQueues:table: 0x40d2f128, driverInfo:table: 0x40d2f2b0 (more...)}
(3) Lua function 'master' at file './examples/rss.lua:19' (best guess)
        Local variables:
         txPort = number: 0
         rxPort = number: 1
         rxQueues = number: 2
         txDev = [Device: id=0]  {initialized:true, rxQueues:table: 0x41923fb8, driverInfo:table: 0x41924140 (more...)}
(4) global C function 'xpcall'
(5) Lua upvalue 'master' at file '/home/dk/MoonGen/build/../libmoon/lua/main.lua:96'
        Local variables:
         _ = string: "./build/MoonGen"
         file = string: "./examples/rss.lua"
         args = table: 0x40eb73a8  {1:0, 2:1}
         cfgFile = nil
         ok = boolean: true
         parsedArgs = table: 0x41b23128  {}
(6) Lua function 'main' at file '/home/dk/MoonGen/build/../libmoon/lua/main.lua:146' (best guess)
        Local variables:
         task = string: "master"
        /home/dk/MoonGen/build/../libmoon/lua/device.lua:245: attempt to index global 'errors' (a nil value)

It seems that this error occurs when I set the rssQueues option in device.config to a value other than 0. 
Could you explain why this error occurs and how to solve this? 

I am using a Mellanox CX-3 pro NIC. 

Thanks,
Daehyeok

**Comment by emmericp** [comment]
Looks like your nic doesn't like that particular configuration with an odd number of queues. 

Also, there seems to be an error when trying to print the error code when the RSS setup fails. I've fixed that here and you'll then probably get something like "Not supported".
Try using an even number of queues both for the number of RSS queues and for the total number of queues.
