### ISSUE TITLE
Layer 3 Latency measurements 

### ISSUE THREAD

**Issue by marjanradi** [emmericp/MoonGen#220]
Hi,

I am using Moongen to measure latency of ethernet and IPv4 packet forwarding. 
I could use l3-load-latency.lua in the provided examples. However, I realized it uses PTP over ethernet messages for latency measurements. So I could measure the latency of layer 2 packet forwarding in my test-bed. However, I can not measure the latency of IPv4 packet forwarding. Because when my Intel 40G NIC receives packets with IPV4 header moongen discards them and does not measure their latency.
I would appreciate it if you could let me know how can I measure the latency of packets with IPV4 header?

Best,
Marjan

**Comment by emmericp** [comment]
Your NIC might have a broken firmware, can you check the firmware version (shown by dpdk on initialization) and check Intel‘s errata sheet for the XL710?

**Comment by emmericp** [comment]
Firmware handles timestamping and it‘s broken in some versions.

Maybe we should add a warning when we detect a known broken firmware

**Comment by marjanradi** [comment]
So you mean by updating my firmware, the issue should be resolved?

**Comment by emmericp** [comment]
I checked my logs when we last saw this.
The bug was introduced in firmware 5.05, 5.04 works fine.
Please check your firmware version.

I don‘t know about other versions

**Comment by marjanradi** [comment]
Thanks. I tried to find firmware 5.04, but I was unsuccessful. Can you provide me a link to download it?

**Comment by emmericp** [comment]
We've also validated that 6.01 also works with timestamping. The commit fixing this issue adds a warning when it detects the known bad 5.05 firmware

**Comment by marjanradi** [comment]
Hi,
My first try was to use it with firmware 6.01. But when I run  l3-load-latency.lua the output is like the following and there is no measurement on the latency:
 
[Device: id=1] RX: 10.68 Mpps, 8890 Mbit/s (10599 Mbit/s with framing)
[Device: id=0] TX: 10.71 Mpps, 8915 Mbit/s (10629 Mbit/s with framing)
[Device: id=1] RX: 10.72 Mpps, 8918 Mbit/s (10633 Mbit/s with framing)
[Device: id=0] TX: 10.69 Mpps, 8896 Mbit/s (10606 Mbit/s with framing)
[Device: id=1] RX: 10.69 Mpps, 8894 Mbit/s (10605 Mbit/s with framing)
[Device: id=0] TX: 10.72 Mpps, 8915 Mbit/s (10630 Mbit/s with framing)
[Device: id=1] RX: 10.71 Mpps, 8914 Mbit/s (10628 Mbit/s with framing)
Samples: 0, Average: nan ns, StdDev: 0.0 ns, Quartiles: nan/nan/nan ns
[INFO]  Saving histogram to 'histogram.csv'

Thanks,
Marjan

**Comment by emmericp** [comment]
Can you reproduce this if your device under test is a simple cable? I've just validated that it works as expected on firmware 6.01 on two directly connected ports.
