### ISSUE TITLE
How To Git the repository completely?

### ISSUE THREAD

**Issue by zhouzhou84** [emmericp/MoonGen#226]
if I use `git clone  https://github.com/emmericp/MoonGen.git ` to download the file , but the "libmoon @ e9a933b" folder is empty,

what command should I use to download this repository completely?

**Comment by pchaigno** [comment]
`git clone --recursive https://github.com/emmericp/MoonGen` should work.

**Comment by emmericp** [comment]
build.sh also does that for you
