### ISSUE TITLE
problem when measuring latency

### ISSUE THREAD

**Issue by luzhang92** [emmericp/MoonGen#233]
Hi,
I feel a little confused when I measure the latency of packet processing. When I run the l2-load-latency.lua or l2-possion-latency.lua, it ok to output the latency 
`Samples: 32547, Average: 338.0 ns, StdDev: 20.3 ns, Quartiles: 344.0/344.0/344.0 ns`

However, When I use the l3-load-latency.lua, I cannot get the latency
`Samples: 0, Average: nan ns, StdDev: 0.0 ns, Quartiles: nan/nan/nan ns`

And another simple question, when I run the l2-load-latency.lus. It loop always, and I should ctrl+c to stop it and it return to me a average latency. and can I get a single latency?

Thank you very much.

**Comment by emmericp** [comment]
Probably a hardware limit, which NIC are you using?

Can you run `examples/timestamping-tests/test-timestamping-capabilities.lua` and paste the full output?

**Comment by luzhang92** [comment]
I use the Intel I350 1Gb NIC. 
And the output of running `examples/timestamping-tests/test-timestamping-capabilities.lua` is as followed:
`[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 6 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:05:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:05:00.2 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:05:00.3 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
[INFO]  Found 4 usable devices:
   Device 0: B4:96:91:27:AA:EC (Intel Corporation I350 Gigabit Network Connection)
   Device 1: B4:96:91:27:AA:ED (Intel Corporation I350 Gigabit Network Connection)
   Device 2: B4:96:91:27:AA:EE (Intel Corporation I350 Gigabit Network Connection)
   Device 3: B4:96:91:27:AA:EF (Intel Corporation I350 Gigabit Network Connection)
[INFO]  Waiting for devices to come up...
[INFO]  Device 1 (B4:96:91:27:AA:ED) is up: 1000 MBit/s
[INFO]  Device 0 (B4:96:91:27:AA:EC) is up: 1000 MBit/s
[INFO]  2 devices are up.
[INFO]  Testing timestamping L2 PTP packets without rx filtering for 5 seconds.
Samples: 41946, Average: 47000.8 ns, StdDev: 30819.2 ns, Quartiles: 27800.0/37752.0/47368.0 ns

[INFO]  Testing timestamping L2 PTP packets with rx filtering for 5 seconds.
Samples: 40791, Average: 51137.2 ns, StdDev: 34357.4 ns, Quartiles: 28872.0/37376.0/45008.0 ns

[INFO]  Testing timestamping L2 PTP packets without rx filtering for 5 seconds.
[INFO]  Adding VLAN tag, this is not supported on some NICs.
[WARN]  Failed to timestamp packet on transmission
[WARN]  Failed to timestamp packet on transmission
[WARN]  Failed to timestamp packet on transmission
[WARN]  Failed to timestamp packet on transmission
[WARN]  Failed to timestamp packet on transmission
[WARN]  Failed to timestamp packet on transmission
`

**Comment by emmericp** [comment]
i350 doesn't support the hardware filters used by the script to fish out the timestamped packets; you'll need a NIC from the ixgbe or i40e family for that

**Comment by luzhang92** [comment]
Sorry to bother you.
I can't understand why when I run the l2-load-latency.lua. It can measure the latency?
