### ISSUE TITLE
Can MoonGen specify payload content. 

### ISSUE THREAD

**Issue by YangZhou1997** [emmericp/MoonGen#234]
FYI. 

I would like to specify dozens of bytes in the packet payload and not sure if MoonGen has provided this kind of interface. 

Any suggestion is highly appreciated!

**Comment by emmericp** [comment]
All packet types have `pkt.payload` which is a uint8/32/64 union, e.g.:

```
local buf = pkt:getUdpPacket()
buf.payload.uint64[0] = 0x1234567812345678ULL
buf.payload.uint32[2] = 0x12345678
```

If you need something more complex check out custom protocols: https://github.com/libmoon/libmoon/tree/master/lua/proto (start with newProtocolTemplate)
