### ISSUE TITLE
Card not detected

### ISSUE THREAD

**Issue by eddie4** [emmericp/MoonGen#239]
Hello,

I have been trying for a few days to get moongen to work. But i keep running into issues. It seems like this should work from where i am standing. I have attempted both ubuntu 16.04 and 18.04 but i keep running into issues that the card is detected in DPDK but not detected in moongen.

card looks to be supported it's an BCM57800 

```
root@kvm344:~/MoonGen# python libmoon/deps/dpdk/usertools/dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:01:00.1 'NetXtreme II BCM57800 1/10 Gigabit Ethernet 168a' drv=igb_uio unused=
0000:01:00.2 'NetXtreme II BCM57800 1/10 Gigabit Ethernet 168a' drv=igb_uio unused=
0000:01:00.3 'NetXtreme II BCM57800 1/10 Gigabit Ethernet 168a' drv=igb_uio unused=
Network devices using kernel driver
===================================
0000:01:00.0 'NetXtreme II BCM57800 1/10 Gigabit Ethernet 168a' if=eno1 drv=bnx2x unused=igb_uio *Active*

```

moongen output. Note it does have 2MB hugepages just not 1GB ones
```
root@kvm344:~/MoonGen# ./build/MoonGen ./examples/l3-tcp-syn-flood.lua 0 -r 100 -d xxxx -f 100
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 32 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
[INFO]  Found 0 usable devices:
[FATAL] Lua error in task master
/root/MoonGen/build/../libmoon/lua/device.lua:100: there are only 0 ports, tried to configure port id 0
```

Any advice you can give would be appreciated. 

ps. The required packages in the howto are missing: Python dpdk and libtbb-dev

**Comment by emmericp** [comment]
it's disabled by default in DPDK; compile DPDK with CONFIG_RTE_LIBRTE_BNX2X_PMD=n

**Comment by eddie4** [comment]
Thanks for the quick response. 

I have purged the apt version of dpdk from the system

I have build DPDK that is included in libmoon with CONFIG_RTE_LIBRTE_BNX2X_PMD=**y** and during the compile i see it getting included however I still have the same issue with the same output as above.

**Comment by eddie4** [comment]
Bought an Intel x520 works instantly. You can resolve this issue.
