### ISSUE TITLE
timestamping all rx packets is not supported by the hardware or driver

### ISSUE THREAD

**Issue by qjiajia** [emmericp/MoonGen#242]
Hi:
I tried to use moonsniffer to grab the package, but it kept coming up with the following error, as shown in the figure below. My network card model is x70, is it the reason that the network card model I use is not compatible with yours? Is there any way to solve it?

[INFO]  Found 2 usable devices:
   Device 0: 6C:92:BF:5B:C5:16 (Intel Corporation Ethernet Controller X710 for 10GbE SFP+)
   Device 1: 6C:92:BF:5B:C5:57 (Intel Corporation Ethernet Controller X710 for 10GbE SFP+)
[INFO]  Waiting for devices to come up...
[INFO]  Device 1 (6C:92:BF:5B:C5:57) is up: 10000 MBit/s
[INFO]  Device 0 (6C:92:BF:5B:C5:16) is up: 10000 MBit/s
[INFO]  2 devices are up.
[FATAL] Lua error in task master
/home/nupt5/MoonGen/build/../libmoon/lua/device.lua:477: timestamping all rx packets is not supported by the hardware or driver

I would like to express my deep appreciation for your Suggestions.

**Comment by emmericp** [comment]
x710 does not support this feature, only very few nics do, consult the datasheets for details
