### ISSUE TITLE
Enabling RSS without enabling RETA

### ISSUE THREAD

**Issue by x0ul** [emmericp/MoonGen#246]
From what I see libmoon's device.lua ties enabling RSS (Receive-Side Steering) and enabling RETA (REdirection TAble) together. However I don't think that RETA has to necessarily be configured/used in order to use RSS.

I've made some simple changes to device.lua that enables RSS but skips calling dev:setRssQueues. When running this code transmitted flows seem to be evenly distributed across the receiver's queues.

I'm new to DPDK and networking in general, so please let me know if I'm making a mistake believing that RSS doesn't require RETA.

**Comment by emmericp** [comment]
the proper way is to set up the RETA, see datasheet
