### ISSUE TITLE
incAndWrap is slower than a naive add-and-modulo

### ISSUE THREAD

**Issue by SolalPirelli** [emmericp/MoonGen#249]
I'm trying to send 10G traffic with a single core on an `Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz`.

This works fine when my loop is:

```
                for _, buf in ipairs(bufs) do
                        local pkt = buf:getUdpPacket()
                        pkt.udp.dst = dstPort
                        dstPort = (dstPort + 1) % flowCount
                end
```

But not when I replace the add-and-modulo with `incAndWrap`:

```
                for _, buf in ipairs(bufs) do
                        local pkt = buf:getUdpPacket()
                        pkt.udp.dst = dstPort
                        dstPort = incAndWrap(dstPort, flowCount)
                end
```

The latter can only do ~12.1 Mpps, whereas the former does ~14.8 Mpps.

**Comment by emmericp** [comment]
the default is optimized to be reasonably fast across a larger range of values with predictables performance; using modulo or branches has some pathological bad cases that are not suitable as a default implementation.
