### ISSUE TITLE
Invalid after setting setVlan ()

### ISSUE THREAD

**Issue by qwe131829** [emmericp/MoonGen#252]
Sorry to disturb you！setVlan(wlanID,7,1)，I try to modify pktgen, using setVlan function to construct vlan packet based on udp with X710. However, through wireshark analysis, it is found that type is still ip4,0x800, with vlan missing in the middle. How should it be solved？

**Comment by qwe131829** [comment]
Dpdk default tx offload is off.Is this reason？

**Comment by qwe131829** [comment]
I saw that testpmd of dpdk can add double-layer vlan through offload. The x710 NIC also seems to support the simultaneous stripping of Layer 2 vlan

**Comment by emmericp** [comment]
Normal VLAN offloading works fine. You probably don't see it in wireshark because you are probably strip it somewhere on the receiving side.

We don't support QinQ offloading at the moment, pull requests welcome.
