### ISSUE TITLE
Compilation issues with Mellanox NIC (./build.sh --mlx4)

### ISSUE THREAD

**Issue by 108anup** [emmericp/MoonGen#256]
I get the following error when I run `./build.sh --mlx4`:
`/usr/bin/ld: cannot find -lrte_pmd_mlx4`
Do I need to compile / install dpdk manually?
Or do I need to export some variables? (I saw in the dpdk config in `libmoon/deps/dpdk/config` that it is not compiling as shared libraries, so I don't this this would be an issue.)

I have installed OFED 4.4
and am on firmware 2.42
Mellanox Connect X3 (OEM - Dell)

**Comment by 108anup** [comment]
I also get many errors like this in the compilation output, I am not sure if this is due to the unavailability of the library or this causes the library to not compile:

`MoonGen/libmoon/deps/dpdk/drivers/net/mlx4/mlx4_flow.c:829:7: error: implicit declaration of function ‘ibv_exp_create_cq’ [-Werror=implicit-function-declaration]
  cq = ibv_exp_create_cq(priv->ctx, 1, NULL, NULL, 0,`

**Comment by 108anup** [comment]
BTW: Using Ubuntu 16.04.6 with kernel: 4.4.0-142-generic

**Comment by 108anup** [comment]
And scrolling further up in the build output, I am also getting these errors:
`MoonGen/libmoon/src/memory.c:2:22: fatal error: rte_mbuf.h: No such file or directory
compilation terminated.
MoonGen/libmoon/src/device.c:2:25: fatal error: rte_ethdev.h: No such file or directory
compilation terminated.
`

**Comment by 108anup** [comment]
Stumbled upon similar issue: https://github.com/emmericp/MoonGen/issues/169 , the solution says to disable KNI mod `CONFIG_RTE_KNI_KMOD=n` but I checked and it is already disabled.

**Comment by emmericp** [comment]
please post the first error message you get while compiling DPDK

**Comment by emmericp** [comment]
looks like either a header is missing or the wrong version for the mlx4 driver, try a version that is compatible with this DPDK version, see our readme-mlx file for versions that we've tested

**Comment by 108anup** [comment]
The headers are there in: `MoonGen/libmoon/deps/dpdk/lib/librte_ether ` and I am using mlx4 driver version 4.4 which has been tested according to https://github.com/libmoon/libmoon/blob/master/install-mlx.md . I can try again with mlx4 version 4.1, but I am not sure if that will solve the issue.

**Comment by 108anup** [comment]
Okay, so I manually installed the .debs mentioned in the README rather than installing whole OFED driver. Despite having installed the driver, installing the .deb made some version downgrades (I never installed a higher driver version though). After this I am not getting the above mentioned errors. Thanks!
