### ISSUE TITLE
throughput: bad argument #1 to 'new' (cannot convert 'nil' to 'uint64_t')

### ISSUE THREAD

**Issue by zahid1121** [emmericp/MoonGen#262]
Unable to pass through these issues. Can someone help please!

> sudo ./MoonGen ../rfc2544/master.lua --txport 0 --rxport 1 --rths 10 --din 4 -dout 4 --asksshpass true --sshuser jlixfeld --host localhost --snmpcomm mycomm 

**unable to load snmp module
unable to load mikrotik ssh module
unable to load freeBSD ssh module
unable to load linux ssh module**
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 1af4:1000 net_virtio
EAL: PCI device 0000:00:09.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 1af4:1000 net_virtio
[INFO]  Found 2 usable devices:
   Device 0: 08:00:27:2A:86:F4 (Red Hat, Inc Virtio network device)
   Device 1: 08:00:27:89:AB:33 (Red Hat, Inc Virtio network device)
[INFO]  Waiting for devices to come up...
[INFO]  Device 1 (08:00:27:89:AB:33) is up: 10000 MBit/s
[INFO]  Device 0 (08:00:27:2A:86:F4) is up: 10000 MBit/s
[INFO]  2 devices are up.
[WARN]  dpdk.launchLua() is deprecated, use moongen.startTask() instead.
frame size(byte),duration(s),max loss rate(%),rate threshold(packets),rate(mpps) iter1,spkts(byte) iter1,rpkts(byte) iter1
configure: add to interface nil ip 198.18.1.1/24continue (y/n)? unable to load snmp module
unable to load mikrotik ssh module
unable to load freeBSD ssh module
unable to load linux ssh module
[WARN]  l2 filter error: Operation not supported
[WARN]  l2 filter error: Operation not supported

continue (y/n)? y
configure: add to interface nil ip 198.19.1.1/24continue (y/n)? y
[FATAL] Lua error in task master
../rfc2544/benchmarks/throughput.lua:162: bad argument #1 to 'new' (cannot convert 'nil' to 'uint64_t')
Stack Traceback
===============
(2) Lua method 'bench' at file '../rfc2544/benchmarks/throughput.lua:162'
	Local variables:
	 self = table: 0x41669bf0  {undoStack:table: 0x41bfd5e8, rxQueues:table: 0x41669d88, duration:10, initialized:true (more...)}
	 frameSize = number: 64
	 binSearch = table: 0x41bfd810  {}
	 pktLost = boolean: true
	 maxLinkRate = number: 10000
	 rate = nil
	 lastRate = nil
(3) Lua function 'master' at file '../rfc2544/master.lua:169' (best guess)
	Local variables:
	 arguments = table: 0x41c00a38  {}
	 txPort = number: 1
	 rxPort = number: 0
	 rateThreshold = number: 100
	 btbThreshold = number: 100
	 duration = number: 10
	 maxLossRate = number: 0.001
	 dskip = nil
	 numIterations = nil
	 dut = table: 0x41c00a60  {}
	 rxDev = [Device: id=0]  {initialized:true, rxQueues:table: 0x41bfce38, driverInfo:table: 0x40d89a18 (more...)}
	 txDev = [Device: id=1]  {initialized:true, rxQueues:table: 0x41fd73b0, driverInfo:table: 0x40d89a18 (more...)}
	 folderName = string: "testresults_2019-11-20_11-48"
	 report = table: 0x40004ba0  {filename:testresults_2019-11-20_11-48/rfc_2544_testreport.tex, frameloss:table: 0x402fafc8 (more...)}
	 results = table: 0x41669bc8  {}
	 thBench = table: 0x41669bf0  {undoStack:table: 0x41bfd5e8, rxQueues:table: 0x41669d88, duration:10, initialized:true (more...)}
	 rates = table: 0x41bfd4e0  {}
	 file = file (0x7f446ecb7380)
	 (for generator) = C function: builtin#6
	 (for state) = table: 0x407975b0  {1:64, 2:128, 3:256, 4:512, 5:1024, 6:1280, 7:1518}
	 (for control) = number: 1
	 _ = number: 1
	 frameSize = number: 64
(4) global C function 'xpcall'
(5) Lua upvalue 'master' at file '/home/cuckoo/MoonGen/build/../libmoon/lua/main.lua:96'
	Local variables:
	 _ = string: "./MoonGen"
	 file = string: "../rfc2544/master.lua"
	 args = table: 0x412f9728  {1:--txport, 2:0, 3:--rxport, 4:1, 5:--rths, 6:10, 7:--din, 8:4, 9:-dout (more...)}
	 cfgFile = nil
	 ok = boolean: true
	 parsedArgs = table: 0x40799c30  {}
(6) Lua function 'main' at file '/home/cuckoo/MoonGen/build/../libmoon/lua/main.lua:146' (best guess)
	Local variables:
	 task = string: "master"
	../rfc2544/benchmarks/throughput.lua:162: bad argument #1 to 'new' (cannot convert 'nil' to 'uint64_t')

**Comment by emmericp** [comment]
The rfc2544 module is unmaintained at the moment, sorry

**Comment by zahid1121** [comment]
OK. Can you please recommend me any other opensource tool for rfc2544?
