### ISSUE TITLE
Two Questions regarding throughput measurements

### ISSUE THREAD

**Issue by harshgondaliya** [emmericp/MoonGen#270]
I have two conceptual questions regarding throughput results shown in l3-load-latency.lua test:

1. What does` with framing `mean in the below output?
```
[Device: id=1] RX: 1.95 Mpps, 1000 Mbit/s (1313 Mbit/s with framing)
[Device: id=0] TX: 1.95 Mpps, 1000 Mbit/s (1313 Mbit/s with framing)

```
2. As I increase packet size (84, 104 .... 204), the result of Mpps decreases and Mbits increases.
I want to understand the reason behind these two trends, especially about the increment in Mbits. 
Because, for a given configuration, the total number of bits transferred per second should remain the same, I feel.

**Comment by emmericp** [comment]
1. Framing refers to overhead on layer 1, i.e., a full link will show the line rate with framing but not without framing.

2. Depends on the NIC and rate control mechanism you are using. Hardware rate control is unfortunately not consistent between different vendors. For example, some NICs account for the CRC checksum some don't

**Comment by harshgondaliya** [comment]
Ok got it. Thanks a lot.
