### ISSUE TITLE
Cannot replay the pcap file in loop mode

### ISSUE THREAD

**Issue by LibinLiu0189** [emmericp/MoonGen#296]
I use the latest MoonGen version and meet the same problem. It cannot solve the problem using the solution below.

$ sudo ./build/MoonGen ./examples/pcap/replay-pcap.lua 0 trace/caida16.pcap -r 1 -l
Like the command above, I run it and only the first time, the trace is played according to the pcap file, in the following, the sending rate is 0 Mbps and not packets are sent. 

Could you help check this? Thanks.

Fix that.
Change line 65 from "if rateLimiter then" to "if rateLimiter and n > 0 then".

Junzhi

_Originally posted by @Gavindeed in https://github.com/emmericp/MoonGen/issues/240#issuecomment-479721181_

**Comment by GrehXscape** [comment]
Do I need to set the prev back to 0 while resetting pcap file?
