### ISSUE TITLE
How to configure the link speed for DPDK NIC?

### ISSUE THREAD

**Issue by yyu4** [emmericp/MoonGen#298]
Hi,

I am using x540 NIC to test a 100Mbps network latency. Firstly I need to measure the x540 NIC self latency, i.e. to test the latency of back-to-back connection between two ports of x540. And the 100Mbps link speed is required. 
My question is how to configure x540 link speed, instead of auto-negotiation?

thanks,
-Yi

**Comment by vipinpv85** [comment]
can you share the following details like

1. OS version
2. Nic firmware
3. driver being - igb_uio or vfio-pci or uio_pci_generic
4. DPDK version
5. shared or static library
6. sample application in use (testpmd, skeleton, l2fwd) etc?

**Comment by yyu4** [comment]
Thank you @vipinpv85 .
Your suggestion of "rte_eth_dev_configure" is the right answer for me. I was running "./build/MoonGen" bash with scripts like "l3-load-latency" etc. After configuring line 131 of MoonGen/libmoon/src/device.c to "./link_speeds = ETH_LINK_SPEED_100M," the NIC works at 100Mbps for me now.
Best,
-Yi
