### ISSUE TITLE
Dynamic rate limiting

### ISSUE THREAD

**Issue by danushkam** [emmericp/MoonGen#305]
Hello,

I need to change rate dynamically, based on a feedback received from a different (remote) process. Can MoonGen support (or be extended to support) something like that?

Thank you!

**Comment by emmericp** [comment]
We had some conference demo thingy with a web UI to control the rate, but I can't find it right now. Anyways, it's based on the integrated webserver, see https://github.com/libmoon/libmoon/blob/master/examples/webserver.lua

You can call the rate limit setter from a different thread in the callback of the webserver handler
