### ISSUE TITLE
issue while building moongen

### ISSUE THREAD

**Issue by rohit172001-eng** [emmericp/MoonGen#306]
In spite of manually binding interfaces to dpdk using dpdk-devbind.py

![image](https://user-images.githubusercontent.com/56271857/113862198-bcfd4b00-97c5-11eb-8291-68dbdaba79ec.png)
![image](https://user-images.githubusercontent.com/56271857/113862256-cd152a80-97c5-11eb-8638-e8c90d30d55b.png)

Still I'm stuck with below error

![image](https://user-images.githubusercontent.com/56271857/113862348-e6b67200-97c5-11eb-894f-69253ac8c292.png)

**Comment by emmericp** [comment]
I think the script just tells you this error even if there are already nics bound, so ignore that

**Comment by rohit172001-eng** [comment]
Thank you sir, can you also please help me up with these queries
1) Do we need external adapters to run dpdk in virtual machine or in my local machine.
![image](https://user-images.githubusercontent.com/56271857/117581167-1afcb580-b119-11eb-9231-3fdeb0c296c8.png)
2) In spite of  having supported adapters I'm getting the following error, I've also successfully binded the NICs, but showing valid port array as 0.
![image](https://user-images.githubusercontent.com/56271857/117581343-e63d2e00-b119-11eb-9cc4-7fc192033dbd.png)


sudo ./moongen-simple start load-latency:0:1:rate=10Mp/s,time=3m
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
[INFO]  Found 0 usable devices:
[ERROR] Invalid device number "0" for flow "load-latency".
[ERROR] Invalid device number "1" for flow "load-latency".
[ERROR] Need to pass at least one tx or rx device.
[ERROR] No valid flows remain

sudo ./build/MoonGen examples/l3-load-latency.lua 0 1
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
[INFO]  Found 0 usable devices:
[FATAL] Lua error in task master
/home/ubuntu/MoonGen/build/../libmoon/lua/device.lua:100: there are only 0 ports, tried to configure port id 0
Stack Traceback
===============
(2) Lua method 'fatal' at file '/home/ubuntu/MoonGen/build/../libmoon/lua/log.lua:129'
    Local variables:
     self = table: 0x411bcf98  {DEBUG:0, fatal:function: 0x4020bae0, writeToLog:function: 0x4020bac0, INFO:1 (more...)}
     str = string: "there are only 0 ports, tried to configure port id 0"
(3) Lua field 'config' at file '/home/ubuntu/MoonGen/build/../libmoon/lua/device.lua:100'
    Local variables:
     args = table: 0x41f1b9f0  {rxQueues:3, txQueues:3, port:0}
(4) Lua function 'master' at file 'examples/l3-load-latency.lua:37' (best guess)
    Local variables:
     args = table: 0x4191f1a8  {rxDev:1, txDev:0, flows:4, rate:10000, size:60}
(5) global C function 'xpcall'
(6) Lua upvalue 'master' at file '/home/ubuntu/MoonGen/build/../libmoon/lua/main.lua:96'
    Local variables:
     _ = string: "./build/MoonGen"
     file = string: "examples/l3-load-latency.lua"
     args = table: 0x408824b0  {1:0, 2:1}
     cfgFile = nil
     ok = boolean: true
     parsedArgs = table: 0x4191eec0  {1:table: 0x4191f1a8}
(7) Lua function 'main' at file '/home/ubuntu/MoonGen/build/../libmoon/lua/main.lua:146' (best guess)
    Local variables:
     task = string: "master"
    /home/ubuntu/MoonGen/build/../libmoon/lua/device.lua:100: there are only 0 ports, tried to configure port id 0
