### ISSUE TITLE
i40evf_dev_init(): Init vf failed

### ISSUE THREAD

**Issue by sv3n-mu3ll3r** [emmericp/MoonGen#314]
Hi Team,
I compiled MoonGen on Debian (Linux Hochwasser 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux) running in a ESX host. SR-IOV is configured, interface is connected:

Network devices using DPDK-compatible driver
============================================
0000:13:00.0 'X722 Virtual Function 37cd' drv=igb_uio unused=

But when I run MoonGen, then it fails.
Can anyone please help me with this?
Thanks a lot, sVen

[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:13:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:37cd net_i40e_vf
i40evf_init_vf(): init_adminq failed: -53
i40evf_dev_init(): Init vf failed
EAL: Requested device 0000:13:00.0 cannot be used
[INFO]  Found 0 usable devices:
[FATAL] Lua error in task master
/home/sven/MoonGen/build/../libmoon/lua/device.lua:100: there are only 0 ports, tried to configure port id 0
Stack Traceback
===============
(2) Lua method 'fatal' at file '/home/sven/MoonGen/build/../libmoon/lua/log.lua:129'
	Local variables:
	 self = table: 0x41e13f98  {DEBUG:0, fatal:function: 0x41154788, writeToLog:function: 0x41154768, INFO:1 (more...)}
	 str = string: "there are only 0 ports, tried to configure port id 0"
(3) Lua field 'config' at file '/home/sven/MoonGen/build/../libmoon/lua/device.lua:100'
	Local variables:
	 args = table: 0x41799018  {txQueues:4, port:0}
(4) Lua function 'master' at file 'attacks/00.my_L3_TCP_all_flags_cleared-flood.lua:18' (best guess)
	Local variables:
	 args = table: 0x41795c90  {ip:10.103.6.29, rate:100000, destination:10.103.2.80, dev:table: 0x41796600 (more...)}
	 (for generator) = C function: builtin#6
	 (for state) = table: 0x41796600  {1:0}
	 (for control) = number: 1
	 i = number: 1
	 dev = number: 0
(5) global C function 'xpcall'
(6) Lua upvalue 'master' at file '/home/sven/MoonGen/build/../libmoon/lua/main.lua:96'
	Local variables:
	 _ = string: "./build/MoonGen"
	 file = string: "attacks/00.my_L3_TCP_all_flags_cleared-flood.lua"
	 args = table: 0x40eb8a80  {1:-i, 2:10.103.6.29, 3:-d, 4:10.103.2.80, 5:-f, 6:0, 7:0}
	 cfgFile = nil
	 ok = boolean: true
	 parsedArgs = table: 0x417959c0  {1:table: 0x41795c90}
(7) Lua function 'main' at file '/home/sven/MoonGen/build/../libmoon/lua/main.lua:146' (best guess)
	Local variables:
	 task = string: "master"
	/home/sven/MoonGen/build/../libmoon/lua/device.lua:100: there are only 0 ports, tried to configure port id 0

**Comment by sv3n-mu3ll3r** [comment]
ouch, my ESX host didn't even give me my Mellanox card. Please forget about this issue.

**Comment by Ramla-I** [comment]
Hi, did you figure out what the issue was?
