### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by tbohren** [emmericp/MoonGen#318]
Hi, I installed MoonGen on an Ubuntu 18.04 machine. Everything went fine until the last step of the installation process, where you start the load-latency example. I'm always getting the following error, no matter if I use MoonGen or moongen-simple (and also with the other examples):
"./build/MoonGen: error while loading shared libraries: libtbbmalloc.so.2: cannot open shared object file: No such file or directory"

However, I found the missing files under "MoonGen/build/libmoon/tbb_cmake_build/tbb_cmake_build_subdir_release". Now my question is at which location the files should actually be, such that I no longer get above error?

**Comment by nextl00p** [comment]
Hello, does it work when you load the library using `LD_PRELOAD`?

**Comment by tbohren** [comment]
Yes, thank you. I'm new to linux and did not know this trick.
