### ISSUE TITLE
MoonGen doesn't generate packets

### ISSUE THREAD

**Issue by lapnd** [emmericp/MoonGen#41]
Hi Paul Emmerich,
I'm trying to use MooGen to generate packets on Fedora 21, kernel 3.17.4-301-fc21.
After building as intructions, the test run as
./MoonGen ../examples/l2-load-latency.lua 0 1
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Detected lcore 4 as core 4 on socket 0
EAL: Detected lcore 5 as core 8 on socket 0
EAL: Detected lcore 6 as core 9 on socket 0
EAL: Detected lcore 7 as core 10 on socket 0
EAL: Detected lcore 8 as core 11 on socket 0
EAL: Detected lcore 9 as core 16 on socket 0
EAL: Detected lcore 10 as core 17 on socket 0
EAL: Detected lcore 11 as core 18 on socket 0
EAL: Detected lcore 12 as core 19 on socket 0
EAL: Detected lcore 13 as core 20 on socket 0
EAL: Detected lcore 14 as core 24 on socket 0
EAL: Detected lcore 15 as core 25 on socket 0
EAL: Detected lcore 16 as core 26 on socket 0
EAL: Detected lcore 17 as core 27 on socket 0
EAL: Detected lcore 18 as core 0 on socket 1
EAL: Detected lcore 19 as core 1 on socket 1
EAL: Detected lcore 20 as core 2 on socket 1
EAL: Detected lcore 21 as core 3 on socket 1
EAL: Detected lcore 22 as core 4 on socket 1
EAL: Detected lcore 23 as core 8 on socket 1
EAL: Detected lcore 24 as core 9 on socket 1
EAL: Detected lcore 25 as core 10 on socket 1
EAL: Detected lcore 26 as core 11 on socket 1
EAL: Detected lcore 27 as core 16 on socket 1
EAL: Detected lcore 28 as core 17 on socket 1
EAL: Detected lcore 29 as core 18 on socket 1
EAL: Detected lcore 30 as core 19 on socket 1
EAL: Detected lcore 31 as core 20 on socket 1
EAL: Detected lcore 32 as core 24 on socket 1
EAL: Detected lcore 33 as core 25 on socket 1
EAL: Detected lcore 34 as core 26 on socket 1
EAL: Detected lcore 35 as core 27 on socket 1
EAL: Detected lcore 36 as core 0 on socket 0
EAL: Detected lcore 37 as core 1 on socket 0
EAL: Detected lcore 38 as core 2 on socket 0
EAL: Detected lcore 39 as core 3 on socket 0
EAL: Detected lcore 40 as core 4 on socket 0
EAL: Detected lcore 41 as core 8 on socket 0
EAL: Detected lcore 42 as core 9 on socket 0
EAL: Detected lcore 43 as core 10 on socket 0
EAL: Detected lcore 44 as core 11 on socket 0
EAL: Detected lcore 45 as core 16 on socket 0
EAL: Detected lcore 46 as core 17 on socket 0
EAL: Detected lcore 47 as core 18 on socket 0
EAL: Detected lcore 48 as core 19 on socket 0
EAL: Detected lcore 49 as core 20 on socket 0
EAL: Detected lcore 50 as core 24 on socket 0
EAL: Detected lcore 51 as core 25 on socket 0
EAL: Detected lcore 52 as core 26 on socket 0
EAL: Detected lcore 53 as core 27 on socket 0
EAL: Detected lcore 54 as core 0 on socket 1
EAL: Detected lcore 55 as core 1 on socket 1
EAL: Detected lcore 56 as core 2 on socket 1
EAL: Detected lcore 57 as core 3 on socket 1
EAL: Detected lcore 58 as core 4 on socket 1
EAL: Detected lcore 59 as core 8 on socket 1
EAL: Detected lcore 60 as core 9 on socket 1
EAL: Detected lcore 61 as core 10 on socket 1
EAL: Detected lcore 62 as core 11 on socket 1
EAL: Detected lcore 63 as core 16 on socket 1
EAL: Support maximum 64 logical core(s) by configuration.
EAL: Detected 64 lcore(s)
EAL: Setting up memory...
EAL: Ask a virtual area of 0x3fc00000 bytes
EAL: Virtual area found at 0x7f9996600000 (size = 0x3fc00000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f99e2c00000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f99e2800000 (size = 0x200000)
EAL: Requesting 512 pages of size 2MB from socket 1
EAL: TSC frequency is ~2300000 KHz
EAL: Master core 63 is ready (tid=e55d7840)
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL:   0000:01:00.0 not managed by VFIO driver, skipping
EAL:   0000:01:00.0 not managed by UIO driver, skipping
EAL: PCI device 0000:01:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL:   0000:01:00.1 not managed by VFIO driver, skipping
EAL:   0000:01:00.1 not managed by UIO driver, skipping
EAL: PCI device 0000:01:00.2 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL:   0000:01:00.2 not managed by VFIO driver, skipping
EAL:   0000:01:00.2 not managed by UIO driver, skipping
EAL: PCI device 0000:01:00.3 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL:   0000:01:00.3 not managed by VFIO driver, skipping
EAL:   0000:01:00.3 not managed by UIO driver, skipping
EAL: PCI device 0000:81:00.0 on NUMA socket 1
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL:   0000:81:00.0 not managed by VFIO driver, skipping
EAL:   PCI memory mapped at 0x7f99e5521000
EAL:   PCI memory mapped at 0x7f99e55df000
EAL: PCI device 0000:81:00.1 on NUMA socket 1
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL:   0000:81:00.1 not managed by VFIO driver, skipping
EAL:   PCI memory mapped at 0x7f99e54a1000
EAL:   PCI memory mapped at 0x7f99e549d000
Found 2 usable ports:
   Ports 0: 90:E2:BA:7C:3C:7C (82599EB 10-Gigabit SFI/SFP+ Network Connection)
   Ports 1: 90:E2:BA:7C:3C:7D (82599EB 10-Gigabit SFI/SFP+ Network Connection)
Waiting for ports to come up...
Port 0 (90:E2:BA:7C:3C:7C) is up: full-duplex 10000 MBit/s
Port 1 (90:E2:BA:7C:3C:7D) is up: full-duplex 10000 MBit/s

It hangout here, nothing happen.
I had tried to change the source/destination MAC in the l2-load-latency.lua at function loadSlave(port, queue)
--Source MAC address
data[0] = 0x90;
data[1] = 0xe2;
data[2] = 0xba;
data[3] = 0x7c;
data[4] = 0x3c;
data[5] = 0x7c;

--Destination MAC address (this is the MAC address of NIC in DUT device)
data[6] = 0x90;
data[7] = 0xe2;
data[8] = 0xba;
data[9] = 0x7c;
data[10] = 0x30;
data[11] = 0xcc;

But the issue is remained.
Could you please give me some hints?
Thank and Best Regards.
Lap

**Comment by emmericp** [comment]
Hi,

I think this is a NUMA issue as your NIC seems to be attached to node 1 and you are running on node 0 by default.

This configuration is currently buggy (and not recommended as you can get serious performance issues when going over QPI for every single packet).

It should work with a warning, though.

You can change your core mapping in lua/dpdk-conf.lua.

-- 
Paul

**Comment by lapnd** [comment]
Thank Emmerich, It works!
