### ISSUE TITLE
Rename 'DPDK' module to 'MoonGen' 

### ISSUE THREAD

**Issue by emmericp** [emmericp/MoonGen#56]

**Comment by wenhuizhang** [comment]
While building, 
error: unrecognized command line option ‘-std=gnu++11’

**Comment by emmericp** [comment]
Please use gcc 4.7 or later

**Comment by wenhuizhang** [comment]
sounds great~, thanks

On Sun, Jul 26, 2015 at 5:25 PM, Paul Emmerich <notifications@github.com>
wrote:

> Please use gcc 4.7 or later
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emmericp/MoonGen/issues/56#issuecomment-125041843>.
>



-- 
V/R,

Wenhui Zhang

Email: wenhui@gwmail.gwu.edu
           Telephone: 1-(703) 424 3193
