### ISSUE TITLE
Does moongen run in a VM?

### ISSUE THREAD

**Issue by kinordlu** [emmericp/MoonGen#58]
Hi emmericp and others,

First of all, apologies, if this is the wrong place to ask questions. Anyway, we really like your moongen project, and it seems to work fine with the two 82599 Intel 10Gbit cards we have. However, In our cloud environment we would like to explore the possibility to run moongen in a VM. It would be OK to use sriov and pci-passthrough etc. features to speed things up in a VM.

* Do you have any experience on running moongen in VM?

* How difficult you think it would be to support VMs?

* Do you foresee problems / performance issues in VM?

Thanks for your help.

--KimN

**Comment by emmericp** [comment]
Hi,

we have never tested using a VF device. There are some differences between the PF and VF of a 82599 (or similiar) NIC.

I expect that our "driver" needs some work to support this. So basic functionality should be available but features like rate control and timestamping will probably fail. It might be as simple as adding the VF VID/PID to the list of known devices, but I expect to run into some troubles with the VF

I'll add it to my todo list, but might take a while as there are quite some things with a higher priority...


Paul

**Comment by waza-ari** [comment]
+1 one this, would like to run MoonGen in a virtualized environment, for example on VMs on an ESXi server

**Comment by benerudolph** [comment]
At least using KVM and virtio for other NICs you'll need to whitelist your NICs for DPDK, see #123.

**Comment by emmericp** [comment]
virtio works in https://github.com/emmericp/MoonGen/commit/4353d3e3e554498d0ee66013e06f7dd3773c1d92
