### ISSUE TITLE
Performance degradation, can't achieve more than 12.75 mpps

### ISSUE THREAD

**Issue by pavel-odintsov** [emmericp/MoonGen#59]
Hello, Paul!

I tested your toolkit and found it awesome! :) Nice work!

But I can't achieve speed more than 12.75 mpps with syn flood generation on ixgbe card:
```bash
build/MoonGen examples/l3-tcp-syn-flood.lua 5 10.0.0.1 16000000 10000
```

Output here:
```bash
Sent 465553792 packets, current rate 12.75 Mpps, 6530.30 MBit/s, 8571.02 MBit/s wire rate
Sent 466829312 packets, current rate 12.75 Mpps, 6530.30 MBit/s, 8571.01 MBit/s wire rate
Sent 468104832 packets, current rate 12.75 Mpps, 6530.30 MBit/s, 8571.02 MBit/s wire rate
Sent 469380352 packets, current rate 12.75 Mpps, 6530.30 MBit/s, 8571.02 MBit/s wire rate
Sent 470655872 packets, current rate 12.75 Mpps, 6530.30 MBit/s, 8571.02 MBit/s wire rate
Sent 471931392 packets, current rate 12.75 Mpps, 6530.30 MBit/s, 8571.02 MBit/s wire rate
Sent 473206912 packets, current rate 12.75 Mpps, 6530.30 MBit/s, 8571.02 MBit/s wire rate
```

From receiving side (builded with netmap) numbers are same:
```bash
319.001576 main_thread [1448] 12177834 pps (12190292 pkts in 1001023 usec)
320.002597 main_thread [1448] 12176882 pps (12189315 pkts in 1001021 usec)
321.003613 main_thread [1448] 12175354 pps (12187724 pkts in 1001016 usec)
322.004634 main_thread [1448] 12187307 pps (12199738 pkts in 1001020 usec)
323.005654 main_thread [1448] 12175676 pps (12188107 pkts in 1001021 usec)
324.006671 main_thread [1448] 12181778 pps (12194167 pkts in 1001017 usec)
325.007688 main_thread [1448] 12171620 pps (12183999 pkts in 1001017 usec)
```

perf top snapshot:
```bash
Samples: 277K of event 'cycles', Event count (approx.): 21570454368
  55.60%  MoonGen                  [.] ixgbe_xmit_pkts
  16.91%  MoonGen                  [.] alloc_mbuf
   9.48%  MoonGen                  [.] rte_delay_us
   5.52%  MoonGen                  [.] calc_ipv4_pseudo_header_checksums
   1.15%  MoonGen                  [.] send_all_packets
```

htop:
```bash
 1  [                                                                0.0%]     Tasks: 27, 62 thr, 59 kthr; 2 running
  2  [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||100.0%]     Load average: 0.11 0.21 0.41 
  3  [|                                                               0.5%]     Uptime: 3 days, 05:50:08
  4  [                                                                0.0%]
  Mem[||||||                                                   694/32205MB]
  Swp[                                                            0/8190MB]
```

I'm using Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz, DPDK 2.0.0. Could you help me?

**Comment by pavel-odintsov** [comment]
Checked it with dpdk2.0 branch and got same issue.

**Comment by scholzd** [comment]
Hey,
as i have written this script i can add a few points (sorry in advance, i don't have much time right now).
I have just tested the script on our system and got the exact same results.
The script itself is not up to date and uses an old API (which is my best guess for the performance loss ATM).
The only scripts that are updated at the moment are the qos test and l3-multi-destinations.lua.
The latter is basically the same as the tcp syn script, but uses UDP instead. I just tested it and it works fine (~9.7 gbit). You could use this one and change the respective parts (getTcp... instead of getUdp..., updating the fill() part and TcpChecksum offloading should be everything) until i have a closer look at the problem.

Later this evening i will have another look at the tcp syn flood script.

Regards,
Dominik

**Comment by scholzd** [comment]
Update: the script works fine, the statistics dump is off.
The script uses 78 b packets but the line that prints statistics to the terminal uses 64 b packets:
printf("Sent %d packets, current rate %.2f Mpps, %.2f MBit/s, %.2f MBit/s wire rate", totalSent, mpps, mpps * 64 * 8, mpps * 84 * 8)
Adjust the 64 and 84 to the correct values matching the packet size and it should work fine.

Dominik

**Comment by emmericp** [comment]
the script should be updated to use the new counters in stats.lua
also, ipv4 should use 64 byte pakets

**Comment by pavel-odintsov** [comment]
Hello, folks!

Thanks you for fast answers, I really appreciate it!

I tried to change: ```local packetLen = 78 - 4``` to ```local packetLen = 60```

And run MoonGen again. But it generates packets on same speed:
```bash
Sent 1351725952 packets, current rate 12.93 Mpps, 6618.17 MBit/s, 8686.35 MBit/s wire rate
Sent 1353023232 packets, current rate 12.97 Mpps, 6641.73 MBit/s, 8717.27 MBit/s wire rate
Sent 1354321152 packets, current rate 12.98 Mpps, 6645.28 MBit/s, 8721.93 MBit/s wire rate
Sent 1355617536 packets, current rate 12.96 Mpps, 6637.34 MBit/s, 8711.52 MBit/s wire rate
Sent 1356911488 packets, current rate 12.94 Mpps, 6624.94 MBit/s, 8695.23 MBit/s wire rate
Sent 1358204288 packets, current rate 12.93 Mpps, 6618.94 MBit/s, 8687.36 MBit/s wire rate
Sent 1359497728 packets, current rate 12.93 Mpps, 6622.33 MBit/s, 8691.81 MBit/s wire rate
```

Speed in MBit/s looks weird but it's not so important for me. My main goal check my toolkit on wire speed.

Should I try new API version or maybe you have another ideas?

**Comment by emmericp** [comment]
Works for me when I reduce the packet size.

CPU: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

Tried to clock it down to emulate your slower CPU and it achieved line rate with frequencies >= 1.7 GHz

So it should work for you, even when paying the ~20% overhead of DPDK 2.0.


However, your CPU is really old so I'm not sure how that factors in. Let's say it is 20% slower than mine, then it would be too slow in combination with the overhead of DPDK 2.0. (FWIW I get an IPC of 2.5 in this example)

Fixing this for slow CPUs by adding multi-core support is left as an exercise for you ;)
hint: add another tx queue, start the task twice and you are done. Should be about 3 lines of code.

**Comment by pavel-odintsov** [comment]
Hello!

Thanks so much. I changed CPU to Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz and could achieve wire speed:
```bash
[Device: id=0] Sent 3664639900 packets, current rate 14.83 Mpps, 7593.81 MBit/s, 9966.88 MBit/s wire rate.
[Device: id=0] Sent 3679470938 packets, current rate 14.83 Mpps, 7593.47 MBit/s, 9966.43 MBit/s wire rate.
[Device: id=0] Sent 3694303512 packets, current rate 14.83 Mpps, 7594.26 MBit/s, 9967.47 MBit/s wire rate.
[Device: id=0] Sent 3709135268 packets, current rate 14.83 Mpps, 7593.82 MBit/s, 9966.88 MBit/s wire rate.
[Device: id=0] Sent 3723965218 packets, current rate 14.83 Mpps, 7592.91 MBit/s, 9965.69 MBit/s wire rate
```
