### ISSUE TITLE
CMake settings do not correctly set `g++` as the compiler for C++ files.

### ISSUE THREAD

**Issue by alex-laties** [emmericp/MoonGen#66]
I ran into compilation issues with MoonGen when using Scientific Linux 6 and their devtoolset-2 package for gcc, as well as pulling CMake 2.8.8 from [this repo](http://pkgs.repoforge.org/cmake/).

CMake defaulted to using `gcc` when compiling C++ files. This lead to a lot of `undefined reference` errors, as the standard C++ library was not being included.

The fix was to add an explicit `SET(CMAKE_CXX_COMPILER "/path/to/g++")` in the `CMakeLists.txt`.

I don't know if this really counts as an issue against the project itself, but more as a troubleshooting thing that might be nice to have in the documentation.

Cheers!

**Comment by wenhuizhang** [comment]
Hi， check if g++ and gcc are updated with version higher than 4.7

$g++ --version

$gcc --version

if not, please add the repository using:

$sudo add-apt-repository ppa:ubuntu-toolchain-r/test

then, to install it use:

$sudo apt-get update

$sudo apt-get install g++-4.7

and then change the default compiler use update-alternatives:

$sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7

$sudo update-alternatives --config gcc

**Comment by wenhuizhang** [comment]
yep, I am agree with @alex-laties

**Comment by alex-laties** [comment]
Hey @wenhuizhang, the gcc/g++ versions in this case was 4.8.2, patch 15 from RedHat Enterprise Linux.

Scientific Linux 6 is based on RHEL6, not debian/ubuntu, so using the ubuntu package management toolchain would not help in this case sadly.
