### ISSUE TITLE
run quality-of-service-test.lua example met error.

### ISSUE THREAD

**Issue by jiamo** [emmericp/MoonGen#74]
engine@engine:~/Git/MoonGen$ sudo ./build/MoonGen ./examples/quality-of-service-test.lua 0 1
    EAL: Detected lcore 0 as core 0 on socket 0
    EAL: Detected lcore 1 as core 1 on socket 0
    EAL: Support maximum 64 logical core(s) by configuration.
    EAL: Detected 2 lcore(s)
    EAL:   cannot open VFIO container, error 2 (No such file or directory)
    EAL: VFIO support could not be initialized
    EAL: Setting up memory...
    EAL: Ask a virtual area of 0xb800000 bytes
    EAL: Virtual area found at 0x7ff10fc00000 (size = 0xb800000)
    EAL: Ask a virtual area of 0x200000 bytes
    EAL: Virtual area found at 0x7ff10f800000 (size = 0x200000)
    EAL: Ask a virtual area of 0x200000 bytes
    EAL: Virtual area found at 0x7ff10f400000 (size = 0x200000)
    EAL: Ask a virtual area of 0x3c00000 bytes
    EAL: Virtual area found at 0x7ff10b600000 (size = 0x3c00000)
    EAL: Ask a virtual area of 0x200000 bytes
    EAL: Virtual area found at 0x7ff10b200000 (size = 0x200000)
    EAL: Ask a virtual area of 0x200000 bytes
    EAL: Virtual area found at 0x7ff10ae00000 (size = 0x200000)
    EAL: Ask a virtual area of 0x3400000 bytes
    EAL: Virtual area found at 0x7ff107800000 (size = 0x3400000)
    EAL: Ask a virtual area of 0x400000 bytes
    EAL: Virtual area found at 0x7ff107200000 (size = 0x400000)
    EAL: Ask a virtual area of 0x3c00000 bytes
    EAL: Virtual area found at 0x7ff103400000 (size = 0x3c00000)
    EAL: Ask a virtual area of 0x200000 bytes
    EAL: Virtual area found at 0x7ff103000000 (size = 0x200000)
    EAL: Requesting 185 pages of size 2MB from socket 0
    EAL: TSC frequency is ~2599187 KHz
    EAL: Master core 0 is ready (tid=1d503880)
    EAL: Core 1 is ready (tid=2fff700)
    EAL: PCI device 0000:02:01.0 on NUMA socket -1
    EAL:   probe driver: 8086:100f rte_em_pmd
    EAL:   0000:02:01.0 not managed by UIO driver, skipping
    EAL: PCI device 0000:03:00.0 on NUMA socket -1
    EAL:   probe driver: 15ad:7b0 rte_vmxnet3_pmd
    EAL:   PCI memory mapped at 0x7ff11d525000
    EAL:   PCI memory mapped at 0x7ff11d524000
    EAL:   PCI memory mapped at 0x7ff11d522000
    EAL: PCI device 0000:0b:00.0 on NUMA socket -1
    EAL:   probe driver: 15ad:7b0 rte_vmxnet3_pmd
    EAL:   PCI memory mapped at 0x7ff11d521000
    EAL:   PCI memory mapped at 0x7ff11d520000
    EAL:   PCI memory mapped at 0x7ff11d51e000
    Found 2 usable ports:
       Ports 0: 00:0C:29:4C:D9:04 (unknown NIC (PCI ID 15ad:7b0))
       Ports 1: 00:0C:29:4C:D9:0E (unknown NIC (PCI ID 15ad:7b0))
    [WARNING] You are using a depreciated method for invoking device config. config(...) should be used with named arguments. For details review the file 'device.lua'
    could not configure tx queue 0
    [ERROR] Lua error in task master
    lua/include/device.lua:180: could not configure device 0: error -22
    Stack Traceback
    ===============
    (2) Lua global 'errorf' at file 'lua/include/utils.lua:11'
    	Local variables:
    	 str = string: "could not configure device %d: error %d"
    (3) Lua field 'config' at file 'lua/include/device.lua:180'
    	Local variables:
    	 args = table: 0x41ff56f8  {1:0, 2:1, 3:3, rxQueues:1, rssNQueues:0, speed:0, dropEnable:true, txDescs:256 (more...)}
    	 rss_enabled = number: 0
    	 rc = number: -22
    (4) Lua function 'master' at file './examples/quality-of-service-test.lua:38' (best guess)
    	Local variables:
    	 txPort = number: 0
    	 rxPort = number: 1
    	 bgRate = number: 1500
    	 fgRate = number: 100
    	 txDev = nil
    	 rxDev = nil
    (5) global C function 'xpcall'
    (6) Lua upvalue 'slave' at file 'lua/include/main.lua:63'
    	Local variables:
    	 _ = string: "./build/MoonGen"
    	 file = string: "./examples/quality-of-service-test.lua"
    	 devices = table: 0x4001f110  {1:table: 0x40011b50, 2:table: 0x400ada38}
    	 args = table: 0x400a10e8  {1:0, 2:1}
    (7) Lua function 'main' at file 'lua/include/main.lua:99' (best guess)
    	Local variables:
    	 task = string: "master"
    	lua/include/device.lua:180: could not configure device 0: error -22

**Comment by emmericp** [comment]
Looks like you are using some kind of virtual VMware NIC.

We currently focus on high-speed packet generation which is only possible on real hardware as emulated NICs are typically extremely slow.

It probably fails because these drivers often don't support essential features like multiple queues. This would need to be fixed in DPDK and/or the emulated hardware.
