### ISSUE TITLE
Device configuration issue in lua script

### ISSUE THREAD

**Issue by sum-it** [emmericp/MoonGen#77]
Hello,

I was trying to use MoonGen. I however had some trouble in running quality-of-service-test.lua script. IThough everything has built successfully. My nics are bind to dpdk but while running the script it says : 

[WARNING] You are using a depreciated method for invoking device config. config(...) should be used with named arguments. For details review the file 'device.lua'
[ERROR] Lua error in task master
lua/include/device.lua:180: could not configure device 0: error -22
Stack Traceback
===============
(2) Lua global 'errorf' at file 'lua/include/utils.lua:11'
	Local variables:
	 str = string: "could not configure device %d: error %d"
(3) Lua field 'config' at file 'lua/include/device.lua:180'
	Local variables:
	 args = table: 0x41443f28  {1:0, 2:2, 3:3, rxQueues:2, rssNQueues:0, speed:0, dropEnable:true, txDescs:256 (more...)}
	 rss_enabled = number: 0
	 rc = number: -22
(4) Lua function 'master' at file 'examples/quality-of-service-test.lua:34' (best guess)
	Local variables:
	 txPort = number: 0
	 rxPort = number: 0
	 bgRate = number: 100
	 fgRate = number: 10
	 txDev = nil
	 rxDev = nil
(5) global C function 'xpcall'
(6) Lua upvalue 'slave' at file 'lua/include/main.lua:63'
	Local variables:
	 _ = string: "./build/MoonGen"
	 file = string: "examples/quality-of-service-test.lua"
	 devices = table: 0x4079b890  {1:table: 0x4079b9d8, 2:table: 0x40ebbbb8, 3:table: 0x4198db78}
	 args = table: 0x4198ddc8  {1:0, 2:0, 3:100, 4:10}
(7) Lua function 'main' at file 'lua/include/main.lua:99' (best guess)
	Local variables:
	 task = string: "master"
	lua/include/device.lua:180: could not configure device 0: error -22

Can you help me with what is the issue here?

**Comment by emmericp** [comment]
Which NIC are you using?
Can you post the whole output (which shows the NIC).

**Comment by emmericp** [comment]
I'm gonna assume that this is some emulated or para-virtualized NIC that doesn't support multiple queues which causes the configuration to fail.

Nothing we can do. Even if we could fix it, it would be pretty pointless since the NIC would be too slow anyways.
