### ISSUE TITLE
Very stranger performance degradation

### ISSUE THREAD

**Issue by pavel-odintsov** [emmericp/MoonGen#79]
Hello, folks!

I hit performance issue again ;(

I have two servers with same issue:
1) Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz
2) Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz

Both servers uses DPDK 2.0 and Intel X520 NICs (single two port NIC per server),

I could achieve line rate with l3-tcp-syn-flood.lua some time ago. But today I have pulled all upgrades from repository and rebuild it and got performance degradation:
```bash
Sent 2542592 packets, current rate 12.75 Mpps, 6530.30 MBit/s, 8571.03 MBit/s wire rate
Sent 3818112 packets, current rate 12.75 Mpps, 6530.52 MBit/s, 8571.31 MBit/s wire rate
Sent 5093632 packets, current rate 12.75 Mpps, 6530.33 MBit/s, 8571.06 MBit/s wire rate
Sent 6369152 packets, current rate 12.75 Mpps, 6530.50 MBit/s, 8571.28 MBit/s wire rate
```

So, I tried to spread load over two queues (two logical CPUS) and haven't got success here too:
```bash
Sent 7010176 packets, current rate 6.38 Mpps, 3265.58 MBit/s, 4286.08 MBit/s wire rate
Sent 7653120 packets, current rate 6.37 Mpps, 3263.71 MBit/s, 4283.62 MBit/s wire rate
```

Finally, I got same generation speed near 12.75 mpps.

But with my patch https://github.com/emmericp/MoonGen/pull/78 I could generate 24 mpps from same server:
```bash
Port 0 sent 62716672 packets, current rate 12.37 Mpps, 6332.44 MBit/s, 8311.32 MBit/s wire rate
Port 1 sent 59574144 packets, current rate 12.37 Mpps, 6333.89 MBit/s, 8313.23 MBit/s wire rate
```

On receiving side:
```bash
We process: 24733385 pps
We process: 24744198 pps
```

What's wrong here? :)

**Comment by pavel-odintsov** [comment]
I have tried to find working commit and will track progress here. I switched to 82d595c6da9e5a686c4dec4fd63ca28bb35a5e4e and everything works perfectly:
```bash
[Device: id=0] Sent 1555482917 packets, current rate 14.82 Mpps, 7585.78 MBit/s, 9956.34 MBit/s wire rate.
[Device: id=0] Sent 1570294193 packets, current rate 14.81 Mpps, 7583.32 MBit/s, 9953.11 MBit/s wire rate.
[Device: id=0] Sent 1585106478 packets, current rate 14.81 Mpps, 7583.85 MBit/s, 9953.80 MBit/s wire rate.
[Device: id=0] Sent 1599920577 packets, current rate 14.81 Mpps, 7584.81 MBit/s, 9955.07 MBit/s wire rate.
[Device: id=0] Sent 1614732812 packets, current rate 14.81 Mpps, 7583.83 MBit/s, 9953.78 MBit/s wire rate.
```

Nice, I achieved 28mpps with two thread mode:
```bash
We process: 28164734 pps
We process: 28160643 pps
We process: 28165195 pps
We process: 28161917 pps
```

**Comment by emmericp** [comment]
> Both servers uses DPDK 2.0 and Intel X520 NICs (single two port NIC per server),

so you are on the DPDK 2.0 branch?
but you are talking about commits in the master branch that are not yet in 2.0.


I cannot reproduce this on any of my servers, I tested it with an E5-2620 v3 and an E3-1230 (the oldest CPU I have).

I can even underclock the E5 to 1.7 GHz and it can still saturate one NIC per core
(cpufrequtils somehow fails on the E3-1230, so I don't know how much cpu power is needed on that older cpu).

**Comment by pavel-odintsov** [comment]
I have used master code all time... I will try to use dpdk2.0 branch.

**Comment by pavel-odintsov** [comment]
I have switched to dpdk2.0 branch and single thread mode work perfectly!

```bash
[Device: id=0] Sent 218092075 packets, current rate 14.54 Mpps, 7446.35 MBit/s, 9773.33 MBit/s wire rate.
[Device: id=0] Sent 232627388 packets, current rate 14.54 Mpps, 7442.03 MBit/s, 9767.66 MBit/s wire rate.
[Device: id=0] Sent 247171657 packets, current rate 14.54 Mpps, 7446.64 MBit/s, 9773.72 MBit/s wire rate.
[Device: id=0] Sent 261710274 packets, current rate 14.54 Mpps, 7443.76 MBit/s, 9769.94 MBit/s wire rate.
[Device: id=0] Sent 276255433 packets, current rate 14.55 Mpps, 7447.12 MBit/s, 9774.34 MBit/s wire rate.
[Device: id=0] Sent 290790202 packets, current rate 14.53 Mpps, 7441.77 MBit/s, 9767.32 MBit/s wire rate.
[Device: id=0] Sent 305335124 packets, current rate 14.54 Mpps, 7446.94 MBit/s, 9774.11 MBit/s wire rate.
[Device: id=0] Sent 319869120 packets, current rate 14.53 Mpps, 7441.36 MBit/s, 9766.78 MBit/s wire rate.
```

But when I tried to run two threads I got performance degradation:
```bash
[Device: id=1] Sent 114679782 packets, current rate 12.77 Mpps, 6536.47 MBit/s, 8579.11 MBit/s wire rate.
[Device: id=0] Sent 127951104 packets, current rate 12.77 Mpps, 6537.81 MBit/s, 8580.88 MBit/s wire rate.
```

But on https://github.com/emmericp/MoonGen/commit/82d595c6da9e5a686c4dec4fd63ca28bb35a5e4e I could achieve 14.6 + 14.6 with same code.

**Comment by emmericp** [comment]
Then you haven't used DPDK 2.0. Please don't use the DPDK 2.0 branch (yet), there are some unresolved issues.

Can you run a git bisect to find the commit that causes the problem?

Can you also please post the output of "cat /proc/cpuinfo"? Your multi-threading problem might be caused by a weird core-ordering with hyper-threading.

**Comment by pavel-odintsov** [comment]
Here you go: https://gist.github.com/pavel-odintsov/ce01dc370afba9882745

**Comment by pavel-odintsov** [comment]
Well, I have removed all sources and pull current master version now. And could achieve 14.1 mpps with two threads.

```bash
[Device: id=0] Sent 2631713713 packets, current rate 14.15 Mpps, 7242.97 MBit/s, 9506.40 MBit/s wire rate.
[Device: id=1] Sent 2631318959 packets, current rate 14.14 Mpps, 7241.02 MBit/s, 9503.84 MBit/s wire rate.
```

Looks like it's OK. Maybe I forgot about clean when change branches.

**Comment by emmericp** [comment]
It's still not line rate, though.

Your cpuinfo looks "normal", so this is really weird....

**Comment by pavel-odintsov** [comment]
Yep, I'm completely agree about "weird".

Because I run MoonGen again and get another results:
```bash
[Device: id=1] Sent 424738353 packets, current rate 13.70 Mpps, 7015.82 MBit/s, 9208.27 MBit/s wire rate.
[Device: id=0] Sent 438629936 packets, current rate 13.71 Mpps, 7018.51 MBit/s, 9211.80 MBit/s wire rate.
```

**Comment by emmericp** [comment]
DPDK performance varies between different runs by up to 5%, no idea what causes this.
But this happens with plain C code as well, so I don't really care.
You usually don't notice that because it is usually fast enough for line rate.

Which Linux distribution are you using?

I'm testing on some servers with Debian and some with Ubuntu.

My hardware: Xeon E3-1230 (v1 and v2), Xeon E5-2620 v3, Dual-Socket Xeon E5-2640 v2
NICs: X520-T2, X540-T2, X540 onboard, XL710 (not really supported yet because I don't like them), and 82580 quad port GbE

**Comment by pavel-odintsov** [comment]
I have used Debian 8 Jessie with standard 3.16 kernel everywhere.

Why you do not like Xl710? :)
