### ISSUE TITLE
Add support for Intel X520

### ISSUE THREAD

**Issue by atheurer** [emmericp/MoonGen#84]
I have X520 adapters, which I have tested with a couple small changes, and it appears to work just fine.  I will submit pull request shortly

**Comment by emmericp** [comment]
Can you post the exact model of the NIC that you are using?

I have some X520 NICs from Intel which identify themselves as 82599EB 10-Gigabit SFI/SFP+ Network Connection (with PCI ID 0x808610FB). 

So I'm kinda surprised that there are more IDs...
The PCI ID in your patch implies that this is an Intel NIC as well.

**Comment by atheurer** [comment]
Lspci identifies this as:
Intel Corporation Ethernet 10G 2P X520 Adapter [8086:154d] (rev 01)

If you need more information, I can get someone to physically inspect it for more information (in a remote lab).

**Comment by emmericp** [comment]
This seems to be a Dell-branded version of that card...
I wonder how it differs (beside the price) from the Intel or supermicro onboard NICs to warrant a new PCI ID...
