### ISSUE TITLE
Implementing Support for other NICs

### ISSUE THREAD

**Issue by sum-it** [emmericp/MoonGen#94]
Hello,

First of all, thanks for the helping in issue #77. And sorry I couldn't reply follow on comments, I thought I would get some mailed notification for the reply, which i didn't, and hence couldn't reply your query. But you were right it was a virtual NIC. 
Now we are trying to use other devices, currently we have few of these : http://www.lannerinc.com/products/x86-network-appliances/x86-desktop-appliances/fw-7525 
We would like to run MoonGen on them for some network performance testing. Especially timestamping (PTP protocol). Can you advice something how we should go about it?

Regards
Sumit

**Comment by emmericp** [comment]
That device seems to have an i210 which isn't explicitely supported yet.
These 1 GbE NICs often have annoying restrictings for filtering and timestamping.
We already support 82580 (which are very similar) and it cannot filter on packet payload and it can only timestamp UDP port 319 which is annoying when developing an application.

I cannot really recommend using anything other than a 10 GbE NIC at the moment.

You will also run into problems with the low number of CPU cores (2 and no HT) on that device. But that's a restriction from DPDK that will be solved with the DPDK 2.0 upgrade soon.

**Comment by sum-it** [comment]
Thank you emmericp,
I will try to workaround and let you know if I could workout something desirable. :)
