### ISSUE TITLE
Core Mask for Multicore Performance 

### ISSUE THREAD

**Issue by wenhuizhang** [emmericp/MoonGen#99]
Hi, sorry for interruption, yet I was wondering how to mask Moongen to multicore please? "sudo ./build/MoonGen -c 7 ./examples/l2-load-latency.lua 0 0 10000 " does not work here.

**Comment by emmericp** [comment]
see lua/dpdk-conf.lua

**Comment by wenhuizhang** [comment]
Got you , thanks so much !

On Thu, Oct 29, 2015 at 7:40 PM, Paul Emmerich <notifications@github.com>
wrote:

> Closed #99 <https://github.com/emmericp/MoonGen/issues/99>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emmericp/MoonGen/issues/99#event-449871273>.
>



-- 
V/R,

Wenhui Zhang

Email: wenhui@gwmail.gwu.edu
           Telephone: 1-(703) 424 3193

**Comment by wenhuizhang** [comment]
Hi, sorry for bothering, yet is there anyway to improve Moongen Performance, I think I used all 16 cores, by cores = 0xffff. 

![screen shot 2015-10-28 at 11 04 06 pm](https://cloud.githubusercontent.com/assets/2313277/10838047/4edb6b90-7e97-11e5-882c-51e45e61d0a8.png)

**Comment by emmericp** [comment]
The l2 script only uses a single core by default, but you can just start more threads.
You are supposed to modify the example scripts to fit your needs. Adding more threads here is trivial, duplicating a single line is sufficient.


btw: such a low performance indicates that your system doesn't support cache access for the NIC; l2-load-latency achieves line rate even on relatively slow CPUs with < 2ghz usually.

**Comment by wenhuizhang** [comment]
Hi, I think I enabled two cores for cache access as we can see below, 

wenhui@nimbnode16:~/MoonGen$ cpuid | grep -i dca
      PLATFORM_DCA_CAP MSR bits = 1
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 1
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0
      PLATFORM_DCA_CAP MSR bits = 0

**Comment by emmericp** [comment]
DPDK does not support DCA, only DDIO which is more annoying to fix if it doesn't work.
Just use more threads.

**Comment by wenhuizhang** [comment]
By multithreading, does it mean that run more slaves "https://github.com/emmericp/MoonGen/blob/master/examples/l3-load-latency.lua#L43"

**Comment by emmericp** [comment]
okay, you'll also need to increase the number of queues. but that's another trivial change.
